export enum ShipType {
    smallCargo = 202,
    largeCargo = 203,
    lightFighter = 204,
    heavyFighter = 205,
    cruiser = 206,
    battleship = 207,
    colonyShip = 208,
    recycler = 209,
    espionageProbe = 210,
    bomber = 211,
    solarSatellite = 212,
    destroyer = 213,
    deathStar = 214,
    battlecruiser = 215,
    crawler = 217,
    reaper = 218,
    pathfinder = 219,
}
export const ShipTypes = [
    ShipType.smallCargo,
    ShipType.largeCargo,
    ShipType.lightFighter,
    ShipType.heavyFighter,
    ShipType.cruiser,
    ShipType.battleship,
    ShipType.colonyShip,
    ShipType.recycler,
    ShipType.espionageProbe,
    ShipType.bomber,
    ShipType.solarSatellite,
    ShipType.destroyer,
    ShipType.deathStar,
    ShipType.battlecruiser,
    ShipType.crawler,
    ShipType.reaper,
    ShipType.pathfinder,
];