export enum ResearchType {
    espionageTechnology = 106,
    computerTechnology = 108,
    weaponsTechnology = 109,
    shieldingTechnology = 110,
    armorTechnology = 111,
    energyTechnology = 113,
    hyperspaceTechnology = 114,
    combustionDrive = 115,
    impulseDrive = 117,
    hyperspaceDrive = 118,
    laserTechnology = 120,
    ionTechnology = 121,
    plasmaTechnology = 122,
    intergalacticResearchNetwork = 123,
    astrophysics = 124,
    gravitonTechnology = 199,
}
export const ResearchTypes = [
    ResearchType.espionageTechnology,
    ResearchType.computerTechnology,
    ResearchType.weaponsTechnology,
    ResearchType.shieldingTechnology,
    ResearchType.armorTechnology,
    ResearchType.energyTechnology,
    ResearchType.hyperspaceTechnology,
    ResearchType.combustionDrive,
    ResearchType.impulseDrive,
    ResearchType.hyperspaceDrive,
    ResearchType.laserTechnology,
    ResearchType.ionTechnology,
    ResearchType.plasmaTechnology,
    ResearchType.intergalacticResearchNetwork,
    ResearchType.astrophysics,
    ResearchType.gravitonTechnology,
];