import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const cz: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Na začátku svého průzkumu se jim */'podařilo rozluštit některé slibné souřadnice'/*, které získali ze záhadné zprávy. Ale když průzkumná loď dorazila do sektoru, o kterém se zmiňovaly souřadnice, našla posádka jenom obrovské pole trosek, které zůstalo po bitvě. Pátrání po přeživších bylo nakonec bezvýsledné.'*/,
        'Magnetické pole asteroidů rušilo skenery'/*. To, co se zdálo být slibným signálem inteligentního mimozemského života, bylo jen narušení měřicích přístrojů a nebylo možné nalézt žádné nové formy života.'*/,
        /*'Právě když průzkumná loď zachytila slibný rádiový signál, všechny */'jejich komunikační systémy náhle selhaly'/*. Vzhledem k okolnostem bylo nejen nemožné navázat kontakt s potenciálními inteligentními formami života, ale bylo by také nebezpečné v misi pokračovat. Posádka se tedy vrátila domů zklamaná, ale bez újmy.'*/,
        /*'Ve značně neprozkoumaném koutě našeho systému byla */'objevena mlhovina s určitou formou vědomí'/* ! Naši mezigalaktičtí vyslanci byli bez sebe a když byla sonda vyslána do oblak, došlo k vážnému mediálnímu cirkusu. Pokusy o komunikaci s mlhovinou však brzy odhalily, že její inteligence byla zhruba na stejné úrovni jako inteligence švába. Nadšení opadlo a bylo rozhodnuto celou epizodu v tichosti zamést pod koberec.'*/,
        /*'Při hledání nových forem života sledovala průzkumná loď nějaké záhadné signály, které se zdály */'přicházet z odvrácené strany neznámé planety'/*. Mezigalaktičtí vyslanci na palubě již vyzvedli balíček s pozdravem a aktivovali překladatelský počítač, ale ukázalo se, že signál pochází ze ztroskotané lodi. Loď je zjevně mimozemského původu, ale bohužel zde nejsou žádné známky posádky. To znamenalo, že nebyla nalezena žádná nová forma života.'*/,
        /*'Průzkumná loď už plula nějakou dobu, když vyšlo najevo, že do */'skenovacího softwaru vklouzla fatální chyba'/*. To bohužel znamenalo, že nebylo možné nalézt žádné nové formy života.'*/,
        /*'Naši mezigalaktičtí vyslanci navštívili */'planetu s extrémně čistými druhy hmyzu za předpokladu'/*, že musí být inteligentní. Tím, co objevili, byli však zklamáni. Poté, co je sledovali, jak přebírají obsah lodního kompaktoru odpadu, bylo rozhodnuto vrátit je na jejich planetu, a to i přes návrh několika členů posádky nechat si jich pár na palubě.'*/,
        /*'Výzkumníci na palubě průzkumné lodi byli u vytržení, když */'objevili neuronovou síť uprostřed pole asteroidů'/*. Proto byli o to více zklamaní, když se ukázalo, že to není nic jiného než shluk zachycených zpráv o staletých sportovních výsledcích, které si vytvořily svůj vlastní život jako nějaký vesmírný gaučový učenec. Posádka se vrátila ponížená, aniž by se dozvěděla něco významnějšího, než kdo naposledy získal nějakou cenu nebo něco jiného.'*/,
        /*'Posádka průzkumné lodi byla nadšená, */'když výsledky testů na výtrusech hub naznačovaly'/*, že našla inteligentní život. Bohužel se ukázalo, že nějaký vtipálek zmanipuloval výsledky testu, jen aby ztrapnil konkurenčního výzkumníka. Výtrusy nebyly ve skutečnosti o nic inteligentnější než ty, které se našly za zadní částí mikrovlnky v kuchyňce. Potížista byl suspendován a vysazen na nejbližší planetě, než se loď vrátila domů.'*/,
        /*'Slibné signály navedly Průzkumnou */'loď k tajemné zlaté kouli'/*, která plula sama v hlubinách vesmíru. Přes veškerou snahu mezigalaktických vyslanců na palubě se nepovedlo najít vchod nebo se s podivným objektem jakkoli spojit, než objekt náhle odskočil.'*/,
        /*'Na neprozkoumané planetě objevila průzkumná loď systém flóry, který byl mnohem inteligentnější, než se původně zdálo. Když se ho však posádka pokusila prozkoumat, objevili se */'podivní uniformovaní strážní roboti a varovali'/* je, že rostliny jsou soukromým majetkem. Ignorovali potenciální potíže s porušením mezigalaktických zákonů o vstupu na soukromý pozemek, takže výzkumníci upevnili své odhodlání a během tajné operace pod rouškou tmy extrahovali několik vzorků, než se rychle vydali na oběžnou dráhu. Bohužel byla operace očividně pro tlupu vědátorů PŘÍLIŠ tajná a na palubě lodi zjistili, že jejich riskantně získané vzorky nebyly nic jiného než běžné pokojové rostliny.'*/,
        /*'Při hledání mimozemské inteligence strávila průzkumná loď neplodné měsíce bezcílným prohledáváním galaxie, */'když konečně objevila mimozemský ekvivalent trepky'/* ! Neodpovídala přesně kritériím inteligentního života, ale po tolika monotónních měsících hledání se posádka rozhodla považovat tento objev i neinteligentního života za úspěch a vrátila se domů bez jakýchkoliv pozoruhodných zpráv.'*/,
        /*'Velmi slibné signály, které průzkumná loď sledovala, */'se bohužel ztratily v kosmické mlze'/*. Ještě chvíli pokračovali v hledání, ale nemohli najít žádné nové formy života.'*/,
        /*'Po intenzivním pátrání objevila posádka */'průzkumné lodi světélkující druh obří měňavky'/* ! Bohužel jednobuněčné organismy měly drobné problémy, když se snažily projít standardními testy inteligence. Vzhledem k tomu, jak málo pozornosti vědci věnují měňavkám, není překvapením, že tento objev byl rovněž považován za bezvýznamný.'*/,
        'Hypnotická mlha vtáhla do svého kouzla'/* celou posádku průzkumné lodi. Zdá se, že podivné barvy a vzory nějak zasahují do lidského mozku, což znamenalo, že místo hledání mimozemského života se posádka místo toho zabývala odpovědí na otázku ‚Jedí mimozemšťané skutečně zelené párky v rohlíku?‘ Netřeba dodávat, že nenašli žádné nové formy života.'*/,
        /*'Při hledání mimozemského života */'skončila průzkumná loď v kosmickém víru'/*, který vážně poškodil vnější trup. Posádku i loď zachránil riskantní letový manévr, ale průzkum museli vzdát a vrátit se s prázdnýma rukama.'*/,
        /*'Průzkumná loď narazila na starou a opuštěnou vesmírnou stanici, */'kterou kdysi obývaly nějaké dříve neznámé druhy'/*. Po intenzivnějším studiu se však brzy ukázalo, že stanice byla pouze propracovaným hoaxem od vyhynulé formy života. Posádka zničila posměšné zprávy, ale nebyla schopna objevit nic jiného významného.'*/,
        /*'Posádka narazila na osamělé a divoké planetě na */'špičkovou výzkumnou stanici řízenou umělou inteligencí'/*. Bohužel dveře na stanici byly chráněny heslem a umělá inteligence odmítla spolupracovat. Posádka se celé dny snažila rozluštit heslo a zásoby se začaly tenčit, když jeden z nenápadnějších členů posádky narazil na kombinaci a rozluštil kód. Bohužel se ukázalo, že stanice byla zklamáním a umělá inteligence nebyla nic jiného než propracovaný systém správy domácnosti. Posádka se rozhodla vrátit domů.'*/,
        /*'Technická chyba v navigačním modulu přivedla průzkumnou loď */'nebezpečně blízko k horizontu černé díry'/*. Posádka se dokázala otočit právě včas, ale skončilo to tak, že vyčerpaly zásoby paliva, a tak musela bez úspěchu přerušit hledání nových forem života.'*/,
        /*'Průzkumná loď s nadšením hlásila, že */'narazila na identickou loď z paralelního vesmíru'/*. Posádka z této dimenze měla dokonce stejná jména. Tím ale podobnosti skončily: na uvítací párty byli hosté tak nafoukaní, že je posádka brzy vyhnala z našeho vesmíru. Posádka se zklamaná, ale zároveň s úlevou vrátila domů.'*/,
        /*'Posádka průzkumné lodi byla od samého začátku rozpolcena bojem, */'až nakonec vypukla vzpoura'/*. Opuštěné členy posádky se podařilo najít a zachránit, ale oznámili, že vzbouřenci převzali kontrolu nad lodí a připojili se ke skupině vesmírných pirátů. V důsledku tohoto incidentu jsou nyní všechny posádky lodí povinny se každé čtvrtletí účastnit povinných seminářů zaměřených na posilování týmového ducha.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'Posádka průzkumné lodi úspěšně */'navázala kontakt s dosud neznámým mimozemským'/* druhem. První dojmy naznačovaly, že byli dobromyslní. Zprávy od našeho vyslance a posádky však byly stále euforičtější, a proto musíme předpokládat, že byli podrobeni nějaké hypnóze. Závěrečná zpráva, kterou jsme obdrželi, byla radostným prohlášením jménem celé posádky, že by raději zůstali s těmito přátelskými mimozemšťany. Loď a její posádka zmizeli beze stopy.'*/,
        /*'Při hledání inteligentních forem života se loď zastavila na dříve neprozkoumaném měsíci. Přinejmenším o měsíci nebylo nikdy nic hlášeno. Brzy se ukázalo proč. Posádce se podařilo vyslat nouzový signál, ale to už bylo pozdě. */'Gigantičtí magmatičtí červi probuzení příletem'/* lodi ji a její posádku během několika minut pohltili.'*/,
        /*'Průzkumné lodi se */'podařilo vystopovat inteligentní mimozemský druh'/*, ale ukázalo se, že jsou nepřátelští. Soudě podle posledního signálu vyslaného posádkou by se zdálo, že je mimozemšťané odvezli jako zajatce. Každý další pokus najít loď a její posádku selhal.'*/,
        /*'Průzkumná loď se na své cestě zastavila na neznámé planetě, aby se zásobila. Planeta byla zahalena zvláštní mlhou, kterou */'posádka rychle identifikovala jako spící plyn'/*. Při další prohlídce se ale brzy ukázalo, že plyn byl tak silný, že loď i její posádka byly nezachránitelné.'*/,
        /*'Posádka této průzkumné lodi si již vydobyla reputaci jako určitých individualistů, odvážlivců až pošetilců, a proto vypadalo, že se pro tuto misi dokonale hodí'. Možná si mysleli, */'že mohou přímo proletět polem asteroidů'/* ? Bohužel bude těžké dát dohromady odpovědi z trosek jejich lodi.'*/,
        /*'Zdá se, že průzkumná loď se */'ztratila v dosud neznámé singularitě'/*. Posádka od té doby nejevila žádné známky života.'*/,
        /*'Průzkumná letka vletěla do zálohy, */'kterou vedl agresivní mimozemský druh'/*. Zcela rozdrtili průzkumnou loď ještě předtím, než se vůbec podařilo navázat první kontakt.'*/,
        /*'Průzkumná loď zaznamenala několik slibných signálů. Ale poté, co vypátrala jejich zdroj, */'tak ten náhle přestal vysílat'/*. Byly vyslány pátrací týmy, ale nemohly najít žádnou stopu o poloze lodi. Musela se ztratit v prázdnotě.'*/,
        /*'Lodní navigátor se musel tak hluboce soustředit na sledování podivného signálu, že ztratil ze zřetele skutečnost, že operují poblíž černé díry. Loď se přiblížila příliš blízko své */'gravitační studni a navzdory maximální snaze posádky'/* nic nebránilo jejímu vtažení dovnitř. Aby se předešlo dalším zbytečným ztrátám, zpráva navrhuje, aby byly v budoucnu standardně integrovány automatické alarmy černých děr.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /byla objevena forma života .+ a byla přidána do nabídky forem života/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /schopni zlepšit naši znalost o nich o (?<xp>\d+) ZK/i,
};