import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const de: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Zu Beginn der Erkundung konnten einige */'vielversprechende Koordinaten aus einer geheimnisvollen Nachricht'/* entschlüsselt werden. Als das Erkundungsschiff jedoch den angegebenen Sektor erreichte, fand die Crew nur noch das riesige Trümmerfeld eines bewaffneten Konflikts vor. Die Suche nach Überlebenden blieb erfolglos.'*/,
        /*'Ein */'magnetisches Asteroidenfeld störte ungünstigerweise die Scanner'/*. Was wie ein vielversprechendes Signal intelligenten außerirdischen Lebens aussah, war nur eine Störung der Messinstrumente und es konnte keine neue Lebensform gefunden werden.'*/,
        /*'Gerade als das Erkundungsschiff einen vielversprechenden Funkspruch auffangen konnte, */'kam es zu einem Totalausfall sämtlicher Kommunikationssysteme'/*. Unter diesen Umständen war nicht nur jede Kontaktaufnahme mit eventuellen intelligenten Lebensformen ausgeschlossen, ein Fortführen der Mission wäre auch gefährlich gewesen. Deshalb kehrte die Crew enttäuscht, aber unversehrt zurück.'*/,
        /*'In einem noch größtenteils unerforschten Planetensystem */'wurde ein kosmischer Nebel mit Bewusstsein entdeckt'/*! Die intergalaktischen Botschafter gerieten in helle Aufregung, weshalb unter großer medialer Aufmerksamkeit eine Sonde entsandt wurde. Beim Kommunikationsversuch mit dem Nebel stellte sich aber schnell heraus, dass seine Intelligenz kaum über der von einfachen Insekten lag. Die Aufregung schwand und es wurde beschlossen, einen Mantel des Schweigens über die ganze Aktion zu breiten.'*/,
        /*'Bei der Suche nach neuen Lebensformen folgte das Erkundungsschiff einigen mysteriösen Signalen, die */'von der Rückseite eines unbekannten Planeten zu stammen'/* schienen. Die intergalaktischen Botschafter an Bord hatten schon das Begrüßungspaket geholt und den Übersetzungscomputer aktiviert, doch es stellte sich heraus, dass das Signal von einem Schiffswrack stammt. Das Schiff ist eindeutig außerirdischer Herkunft, aber von den Piloten fehlt leider jede Spur. So konnte keine neue Lebensform entdeckt werden.'*/,
        /*'Das Erkundungsschiff war einige Zeit unterwegs, bis sich herausstellte, dass sich ein */'fataler Bug in die Scan-Software eingeschlichen'/* hatte. So konnte leider keine neue Lebensform aufgespürt werden.'*/,
        /*'Leider erwies sich die insektoide Alienspezies, die unsere */'intergalaktischen Botschafter wegen der außerordentlichen Sauberkeit'/* ihres Heimatplaneten zunächst für intelligent hielten, doch als eher einfach gestrickt. Nachdem sie den Inhalt der Bord-Müllpresse gefressen hatten, wurden sie deshalb wieder auf ihrem Planeten ausgesetzt, trotz eines Votums der Crew, doch ein paar Exemplare zu behalten.'*/,
        /*'Vollkommen begeistert fanden die Forscher des Erkundungsschiffes */'ein neuronales Netzwerk mitten in einem Asteroidenfeld'/*. Die Enttäuschung war groß, als sich herausstellte, dass es sich lediglich um ein Cluster verfangener Nachrichten mit jahrhundertealten Sportergebnissen handelte, die das Eigenleben eines schlecht informierten Stammtisches entwickelt hatten. Die Crew kehrte niedergeschlagen und ohne signifikante Ergebnisse zurück.'*/,
        /*'Die Crew des Erkundungsschiffes war hellauf begeistert, als */'Untersuchungen von Schimmelsporen intelligentes Leben versprachen'/*. Leider stellte sich heraus, dass ein Witzbold die Forschungsergebnisse manipuliert hatte, um einen rivalisierenden Forscher bloßzustellen. Die untersuchten Sporen waren in Wahrheit kein bisschen intelligenter als der durchschnittliche Schimmelpilz in der Bordküche. Der Unruhestifter wurde auf den nächstbesten Planeten beurlaubt und das Schiff kehrte ergebnislos zurück.'*/,
        /*'Vielversprechende Signale führten das */'Erkundungsschiff zu einer mysteriösen goldenen Sphäre'/*, die einsam in den Tiefen des Weltalls schwebte. Trotz aller Bemühungen der intergalaktischen Botschafter an Bord konnte weder ein Eingang gefunden noch irgendwie Kontakt zu dem merkwürdigen Objekt hergestellt werden, bevor es sich mit einem Sprung davonmachte.'*/,
        /*TODO: de 'On an unexplored planet, the exploration ship discovered a */'floral system that was far more intelligent than first appeared'/*. When the crew tried to investigate, however, strange uniformed guard robots appeared and warned them that the plants were private property. Ignoring the potential difficulties for breaking intergalactic trespassing laws, the researchers steeled their resolve and extracted some samples during a covert operation under cover of darkness, before quickly making for orbit. Sadly, the operation was clearly a little TOO covert for the likes of a bunch of boffins, and back on board ship they discovered their riskily acquired samples were nothing more than regular house plants.'*/,
        /*'Bei der Suche nach außerirdischem intelligentem Leben irrte das Erkundungsschiff bereits seit Monaten durch die Galaxis, als sie */'endlich einen außerirdischen Verwandten des Pantoffeltierchens'/* fanden! Diese Lebensform war zwar nicht intelligent, aber aufgrund der langen Reise und blankliegender Nerven entschied die Crew, auch mit unintelligentem Leben vorlieb zu nehmen und ohne nennenswerte Funde zurückzukehren.'*/,
        /*'Die vielversprechenden Signale, denen das Erkundungsschiff folgte, */'verloren sich leider in einem kosmischen Nebel'/*. Die Suche wurde noch eine Weile fortgesetzt, aber es konnten keine neuen Lebensformen entdeckt werden.'*/,
        /*TODO: de 'After intensive searching, the crew of the exploration ship discovered a */'luminescent species of giant amoeba'/*! Sadly the single-celled organisms had some issues trying to pass the standard intelligence tests. Given how little attention is paid to amoebae by researchers, it is little surprise that this discovery was similarly considered insignificant.'*/,
        /*'Ein hypnotischer Nebel zog die gesamte Crew des Erkundungsschiffes in seinen Bann. Die fremdartigen Farben und Muster scheinen auf ungünstige Weise mit dem menschlichen Gehirn zu interferieren, wodurch die Besatzung statt der Suche nach außerirdischem Leben der Beantwortung der Frage „*/'Essen Aliens eigentlich grüne Hotdogs'/*?“ nachging. Überflüssig zu erwähnen, dass sie keine neue Lebensform fanden.'*/,
        /*TODO: de 'While searching for extra-terrestrial life, the Exploration Ship ended up in */'a cosmic vortex that severely damaged the outer hull'/*. The crew and ship were saved by a risky flight manoeuvre, but they had to give up the exploration and return empty-handed.'*/,
        /*'Das Erkundungsschiff stieß auf eine */'alte verlassene Raumstation, die von bisher unbekannten Lebewesen'/* bewohnt wurde. Nach eingehender Untersuchung musste man allerdings feststellen, dass es sich um den ausgeklügelten Scherz einer bereits ausgestorbenen Lebensform handelte. Die Crew zerstörte die hämischen Botschaften, konnte ansonsten aber nichts entdecken.'*/,
        /*TODO: de 'The crew came across a */'high-tech AI-driven research station'/* on a lonely and savage planet. Unfortunately, the door to the station was password protected, and the AI refused to cooperate. The crew spent days trying to decipher the password, and the supplies were starting to dwindle, when one of the more inconspicuous crew members hit upon the combination and cracked the code. Sadly, the station turned out to be a disappointment, and the AI was nothing more than an elaborate home management system. The crew decided to return home.'*/,
        /*TODO: de 'A technical error in the navigation module took the Exploration Ship */'dangerously close to the event horizon of a black hole'/*. The crew were able to turn around just in time but ended up draining their fuel supplies and so had to break off the search for new lifeforms without success.'*/,
        /*'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*TODO: de 'On its search for intelligent lifeforms, the ship stopped over on a previously unexplored moon. At least, the moon had never been reported upon. It soon became clear why. The crew managed to get off a distress signal, but by then it was too late. Awoken by the ship’s arrival, */'gigantic magma worms devoured the ship'/* and its crew within in a matter of minutes.'*/,
        /*TODO: de 'The exploration ship managed to track down an intelligent alien species, but they turned out to be hostile. Judging by the last signal sent by the crew, it would */'appear that the aliens took them away as prisoners'/*. Every further attempt to locate the ship and its crew has failed.'*/,
        /*'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /Bei den Koordinaten .+ wurde die Lebensform .+ gefunden und der Lebensformverwaltung hinzugefügt/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Dennoch konnten unsere Botschafter unser Wissen über sie um (?<xp>\d+) Erfahrung verbessern/g,
};