import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const dk: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'I starten af deres udforskning, var de i */'stand til at dechifrere nogen lovende koordinater'/*, som de havde fået fra en mystisk besked. Men da Udforsknings Skibet nået sektoren som koordinaterne nævnede, alt hvad besætningen fandt var en gigantisk ruinmark, der blev efterladt efter en kamp. Søgningen efter overlevende var i sidste ende frugtesløs.'*/,
        /*'Et */'magnetisk asteroidefelt forstyrrede scannerne'/*. Hvad der så ud som en lovende signal på intelligent underjordisk liv, var blot en forstyrrelse i måleinstrumenterne og ingen nye livsforme kunne blive fundet.'*/,
        /*'Lige da Udforsknings Skibet havde opsnappet en lovende radio signal, gik */'alle deres kommunikations systemer lige pludseligt'/* ned. På baggrund af omstændighederne, var det ikke kun umuligt at skabe kontakt med potentielle intelligente livsforme, men det ville også have været farligt at fortsætte misionen. Så besætningen vente hjem skuffede, men uskadte.'*/,
        /*'En stjernetåge med en form for bevidsthed er blevet opdaget i et */'stort uudforsket hjørne af vores system'/* ! Vores intergalaktiske udsendinge var ude af sig selv, og der var et seriøst medie cirkus da sonden blev sendt ind i skyen. Dog har forsøg på at kommunikere med stjernetågen snart afsløret, at dens intelligens var omkring den samme som en kakerlaks. Spændingen ebbede ud, og det blev besluttet at hele episoden skulle stille og roligt blive fejet ind under gulvtæppet.'*/,
        /*'I søgningen efter nye livsformer, fulgte Udforsknings Skibet nogen mystiske signaler der så ud til at */'komme fra den fjerne side af en ukendt planet'/*. De intergalaktiske udsendte ombord, havde allerede modtaget hilse pakken og aktiverede oversættelses computeren, men det viste sig at signalet kom fra en skibsvrag. Skibet er helt klart af underjordisk oprindelse, men desværre er der ingen tegn på en besætning. Dette betyder at ingen nye livsform blev fundet.'*/,
        /*'Udforsknings Skibet har været undervejs i nogen tid, da det kom frem at en */'fatal fejl havde sluppet sig ind i scannings softwaren'/*. Dette betød desværre, at ingen nye livsforme kunne findes.'*/,
        /*'Vores intergalaktiske udsendte besøgte en */'planet med en ekstremt ren insektoid art'/*, og regnede med at de må være intelligente, men blev skuffet af det de havde opdagede. Efter at se dem knase igennem indholdet af et skibs affalds komprimator, blev det besluttet at sende dem tilbage til deres planet, på trods af at nogen besætnings medlemmer forslog at holde et par. af dem ombord.'*/,
        /*'Forskerne ombord på udforsknings skibet var */'ekstatiske over at opdage et neuralt netværk'/*, i midten af et asteroide felt. Derfor var de skuffede, da det viste sig at være ikke andet end en klynge af opsnappede nyhedsindslag om århundreder gammle sports resultater, som har udviklet dens eget liv som en eller anden rum sofa ekspert. Besætningen vendte nedtrykt tilbage, uden at lære noget mere betydningsfuldt end hvem der sidst vandt en eller anden aske.'*/,
        /*'Udforsknings skibets besætning var over månen, da resultaterne af testene fra */'svampesporerne antydede at de havde fundet intelligent'/* liv. Desværre, viste det sig at en eller anden joker havde manipulerede med test resultaterne, bare for at udmyge en rivaliserende forsker. Sporene var i virkeligheden ikke mere intelligente end dem man finder bagved en mikroovn i galleriet. Ballademageren blev suspenderet og efterladt på den nærmeste planet, før skibet vendte hjem.'*/,
        /*'Lovende signaler guidede Udforsknings Skibet */'til en mystisk gyldne kugle'/*, der svævede alene i rummets dyb. På trods af alle anstrengelserne fra de intergalaktiske udsendte ombord, var de ikke i stand til at finde en indgang eller skabe nogen form for kontakt med det mærkelige objekt, før den lige pludselig sprang væk.'*/,
        /*'På en uudforsket planet, opdagede udforsknings skibet en blomstret system der var langt mere intelligent end det først så ud som om. Da besætningen prøvede at undersøge det, kom der dog */'mærkelige uniformere robot vagter frem'/*, og advarede dem om at planterne var privat ejendom. Ved at ignorere de potentielle vanskeligheder med at bryde intergalaktiske lovovertrædelser, stålsatte forskerne deres beslutsomhed og tog nogle prøver under en hemmelig operation i ly af mørket, før de hurtigt gik i kredsløb. Desværre, var operationen helt klart lidt FOR hemmelig for et folk som en flok boffiner, og tilbage om bord på skibet opdagede de, at deres risikabelt erhvervede prøver ikke var andet end almindelige stueplanter.'*/,
        /*'På deres søgning efter underjordisk intelligens, har udforsknings skibet allerede brugt frugtesløse måneder på at gennemsøge galaksen målløst, da de endelig opdagede den */'fremmede ækvivalent til et paramecium'/* ! Den passede ikke ligefrem til kriterierne for et intelligent liv, men efter så mange monotone måneders søgen, besluttede besætningen at betragte denne opdagelse af selv uintelligent liv som en succes, og vendte hjem uden nogen bemærkelsesværdige nyheder.'*/,
        /*'De meget lovende signaler som Udforsknings Skibet havde forfulgt, */'blev desværre tabt i en kosmisk tåge'/*. De fortsatte søgningen i en del tid endnu, men de kunne ikke finde nogen nye livsformer.'*/,
        /*'Efter intens søgning, opdagede besætningen af udforsknings skibet en */'selvlysende art af gigantiske amøber'/* ! Desværre, havde den enkeltcelle organisme nogen problemer med at prøve at bestå standard intelligens testen. Givet hvor lidt opmærksomhed der bliver givet til amøberne af forskerne, er det lidt overraskende at denne opdagelse bare blev betragtet som ubetydelig.'*/,
        /*'En hypnotisk tåge drev hele besætningen af Udforsknings Skibet under en besværgelse. De mærkelige farver og designs så ud til at blande sig med den menneskelige hjerne på en eller anden måde, hvilket betød at i stedet for søgningen efter underjordisk liv, beskæftigede besætningen sig i stedet med at besvare spørgsmålet ‘*/'Spiser de fremmede faktisk grønne hotdogs'/*?’ Det er overflødigt at sige, at de ikke fandt nogen nye livsformer.'*/,
        /*'Mens der blev søgt efter underjordisk liv, endte */'Udforsknings Skibet i en kosmisk hvirvel'/*, der beskadigede det ydre skrog alvorligt. Besætningen og skibet blev redet af en risikabel manøvre, men de blev nød til at opgive udforskningen og vende tilbage tomhændet.'*/,
        /*'Udforsknings skibet kom frem til en gammel og forladt rumstation, der engang var */'bemandet af nogen tidligere ukendte arter'/*. Efter noget mere intens forskning, blev det dog snart klart at stationen var blot en udførlig fup fra en uddød livsform. Besætningen ødelage de latterlige beskeder, men var ikke i stand til at opdage noget andet af betydning.'*/,
        /*'Besætningen stødte på en */'høj teknologisk AI drevet forsknings station'/* på en ensom og brutal planet. Desværre, var døren til stationen password beskyttet, og AI nægtede at samarbejde. Besætningen brugte dage på at prøve på at afkode password, og forsyningerne begyndte at forsvinde, da en af de mere upåfaldende besætnings medlemmer ramte kombinationen og knækkede koden. Desværre, viste stationen sig at være en skuffelse, og AI var ikke andet end en omfattende hjemmestyrings system. Besætningen besluttede at vende hjem.'*/,
        /*'En teknisk fejl i navigations modulet tog Udforsknings Skibet faretruende tæt på */'begivenhedshorisonten ved et sort hul'/*. Besætningen var i stand til at vende rundt i time, men endte med at dræne deres brændstofs forsyninger, og blev nød til at afslutte søgningen efter nye livsforme uden succes.'*/,
        /*'Udforsknings skibet rapporterede med spænding, at de har stødt på et */'identisk skib fra et parallelt univers'/*. Besætningen fra denne dimension havde endda de samme navne. Men lighederne stoppede der: til velkomst festen, var gæsterne så slemme at besætningen snart blev nød til at fordrive dem fra vores univers. Skuffet, men samtidigt lettede, vendte besætningen hjem.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'Udforsknings skibets besætning var splittet på grund af kampene fra starten, */'indtil et mytteri til sidst brød ud'/*. De strandede besætnings medlemmer blev lokaliserede og redet, men de rapporterede at mytteristerne har taget kontrol over skibet og har skabt et bånd med rum piraterne. Som et resultat af denne hændelse, er alle skibs besætninger nu forpligtet til at deltage i obligatoriske team building seminarer hvert kvartal.'*/,
        /*'Besætningen af udforsknings skibet */'skabte kontakt med succes til en tidligere ukendt fremmede art'/* . Første indtryk tydede på, at de var velvillige. Dog, blev rapporterne fra vores udsendte og besætningen mere og mere euforiske, hvilket er derfor vi må antage, at de var udsat for en eller anden form for hypnose. Den endelige rapport vi modtog, var en glædelig proklamation på vegne af hele besætningen om, at de ville foretrække at blive hos disse venlige rumvæsener. Skibet og dens besætning forsvandt uden et spor.'*/,
        /*'På dens søgning efter intelligente livsformer, stoppede skibet over på en tidligere uudforsket måne. I det mindre, er der ikke nogen der har rapporteret om månen før. Det blev snart klart hvorfor. Besætningen formået at slippe af med et nødsignal, men på det tidspunkt var det for sent. Vækket af skibets ankomst, */'fortærede gigantiske magma orme skibet og dens'/* besætning indeni, indenfor et par. minutter.'*/,
        /*'Udforsknings skibet har formået at finde en intelligent fremmed art, */'men de viste sig at være fjendtlige'/*. At dømme efter det sidste signal der blev sendt af besætningen, ville det se ud som om at rumvæsnerne tog dem væk som fanger. Hver yderligere forsøg på at lokalisere skibet og dens besætning er mislykkedes.'*/,
        /*'Udforsknings skibet stoppede på en ukendt planet på sin rejse for at fylde op med forsyninger. Planeten var indhyllet i en mærkelig tåge, som besætningen hurtigt */'var i stand til at identificere som en sovegas'/*. Men ved nærmere eftersyn, viste det sig hurtigt, at gassen var så stærk, at både skibet og dens besætning ikke var til at redde.'*/,
        /*'Denne udforsknings skibs besætning har allerede fået sig et ry for at have en maverick outfit, modige i en grad af at være dumdristige, hvilket er derfor de så ud som at være det perfekte match til denne mission. Måske troede de at de bare */'kunne flyve lige igennem asteroide feltet'/* ? Desværre, vil det være svært at sammensætte svar fra vraget af deres skib.'*/,
        /*'Det ser ud til at udforsknings */'skibet er blevet tabt i et hidtil ukendt singularitet'/*. Der har ikke været noget tegn på liv fra besætningen siden da.'*/,
        /*'Udforsknings flåden fløj ind i et */'bagholdsangreb fra en krigerisk fremmed art'/* . De pulveriserede udforsknings skibet før den første kontakt overhovedet kunne etableres.'*/,
        /*'Udforsknings skibet har detekteret nogen lovende signaler. Men efter at have fundet kilden til signalet, */'holdte den lige pludselig op med at sende'/*. Søgnings teamet blev sendt afsted, men de kunne ikke finde nogen spor af skibets lokation. Den må være tabt i tomrummet.'*/,
        /*'Skibets navigatør må have været så dybt koncentreret om at følge den mærkelige signal, at */'han glemte at de opererede tæt på et sort hul'/* . Skibet kantede for tæt på sin gravitationsbrønd, og på trods af besætningens bedste indsats, var der ikke noget der stoppede dem i at blive trækket ind. For at undgå flere af sådan nogen unødvendige tab, forslår rapporten at automatiske sort huls alarmer skal blive integreret som en standard i fremtiden.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /og blev tilføjet til Livsformer menuen/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /forbedre vores viden omkring dem med (?<xp>\d+) XP/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*LOCA: dk 'The Exploration Ship has found some artefacts */'but cannot recover them as your storage is full',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'Udforsknings Skibet har */'fundet et lille antal artefakter',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Udforsknings Skibet har */'fundet en stor mængde artefakter',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*'Udforsknings Skibet har */'fundet en kæmpe bjerg af artefakter',
        },
        numberOfArtifacts: /Artefakter fundet: (?<artifacts>\d+)/i,
    },
};