import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const dk: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'I starten af deres udforskning, var de i */'stand til at dechifrere nogen lovende koordinater'/*, som de havde fået fra en mystisk besked. Men da Udforsknings Skibet nået sektoren som koordinaterne nævnede, alt hvad besætningen fandt var en gigantisk ruinmark, der blev efterladt efter en kamp. Søgningen efter overlevende var i sidste ende frugtesløs.'*/,
        /*'Et */'magnetisk asteroidefelt forstyrrede scannerne'/*. Hvad der så ud som en lovende signal på intelligent underjordisk liv, var blot en forstyrrelse i måleinstrumenterne og ingen nye livsforme kunne blive fundet.'*/,
        /*'Lige da Udforsknings Skibet havde opsnappet en lovende radio signal, gik */'alle deres kommunikations systemer lige pludseligt'/* ned. På baggrund af omstændighederne, var det ikke kun umuligt at skabe kontakt med potentielle intelligente livsforme, men det ville også have været farligt at fortsætte misionen. Så besætningen vente hjem skuffede, men uskadte.'*/,
        /*'En stjernetåge med en form for bevidsthed er blevet opdaget i et */'stort uudforsket hjørne af vores system'/* ! Vores intergalaktiske udsendinge var ude af sig selv, og der var et seriøst medie cirkus da sonden blev sendt ind i skyen. Dog har forsøg på at kommunikere med stjernetågen snart afsløret, at dens intelligens var omkring den samme som en kakerlaks. Spændingen ebbede ud, og det blev besluttet at hele episoden skulle stille og roligt blive fejet ind under gulvtæppet.'*/,
        /*'I søgningen efter nye livsformer, fulgte Udforsknings Skibet nogen mystiske signaler der så ud til at */'komme fra den fjerne side af en ukendt planet'/*. De intergalaktiske udsendte ombord, havde allerede modtaget hilse pakken og aktiverede oversættelses computeren, men det viste sig at signalet kom fra en skibsvrag. Skibet er helt klart af underjordisk oprindelse, men desværre er der ingen tegn på en besætning. Dette betyder at ingen nye livsform blev fundet.'*/,
        /*'Udforsknings Skibet har været undervejs i nogen tid, da det kom frem at en */'fatal fejl havde sluppet sig ind i scannings softwaren'/*. Dette betød desværre, at ingen nye livsforme kunne findes.'*/,
        /*TODO: dk 'Leider erwies sich die insektoide Alienspezies, die unsere */'intergalaktischen Botschafter wegen der außerordentlichen Sauberkeit'/* ihres Heimatplaneten zunächst für intelligent hielten, doch als eher einfach gestrickt. Nachdem sie den Inhalt der Bord-Müllpresse gefressen hatten, wurden sie deshalb wieder auf ihrem Planeten ausgesetzt, trotz eines Votums der Crew, doch ein paar Exemplare zu behalten.'*/,
        /*TODO: dk 'Vollkommen begeistert fanden die Forscher des Erkundungsschiffes */'ein neuronales Netzwerk mitten in einem Asteroidenfeld'/*. Die Enttäuschung war groß, als sich herausstellte, dass es sich lediglich um ein Cluster verfangener Nachrichten mit jahrhundertealten Sportergebnissen handelte, die das Eigenleben eines schlecht informierten Stammtisches entwickelt hatten. Die Crew kehrte niedergeschlagen und ohne signifikante Ergebnisse zurück.'*/,
        /*'Udforsknings skibets besætning var over månen, da resultaterne af testene fra */'svampesporerne antydede at de havde fundet intelligent'/* liv. Desværre, viste det sig at en eller anden joker havde manipulerede med test resultaterne, bare for at udmyge en rivaliserende forsker. Sporene var i virkeligheden ikke mere intelligente end dem man finder bagved en mikroovn i galleriet. Ballademageren blev suspenderet og efterladt på den nærmeste planet, før skibet vendte hjem.'*/,
        /*'Lovende signaler guidede Udforsknings Skibet */'til en mystisk gyldne kugle'/*, der svævede alene i rummets dyb. På trods af alle anstrengelserne fra de intergalaktiske udsendte ombord, var de ikke i stand til at finde en indgang eller skabe nogen form for kontakt med det mærkelige objekt, før den lige pludselig sprang væk.'*/,
        /*'På en uudforsket planet, opdagede udforsknings skibet en blomstret system der var langt mere intelligent end det først så ud som om. Da besætningen prøvede at undersøge det, kom der dog */'mærkelige uniformere robot vagter frem'/*, og advarede dem om at planterne var privat ejendom. Ved at ignorere de potentielle vanskeligheder med at bryde intergalaktiske lovovertrædelser, stålsatte forskerne deres beslutsomhed og tog nogle prøver under en hemmelig operation i ly af mørket, før de hurtigt gik i kredsløb. Desværre, var operationen helt klart lidt FOR hemmelig for et folk som en flok boffiner, og tilbage om bord på skibet opdagede de, at deres risikabelt erhvervede prøver ikke var andet end almindelige stueplanter.'*/,
        /*'På deres søgning efter underjordisk intelligens, har udforsknings skibet allerede brugt frugtesløse måneder på at gennemsøge galaksen målløst, da de endelig opdagede den */'fremmede ækvivalent til et paramecium'/* ! Den passede ikke ligefrem til kriterierne for et intelligent liv, men efter så mange monotone måneders søgen, besluttede besætningen at betragte denne opdagelse af selv uintelligent liv som en succes, og vendte hjem uden nogen bemærkelsesværdige nyheder.'*/,
        /*'De meget lovende signaler som Udforsknings Skibet havde forfulgt, */'blev desværre tabt i en kosmisk tåge'/*. De fortsatte søgningen i en del tid endnu, men de kunne ikke finde nogen nye livsformer.'*/,
        /*'Efter intens søgning, opdagede besætningen af udforsknings skibet en */'selvlysende art af gigantiske amøber'/* ! Desværre, havde den enkeltcelle organisme nogen problemer med at prøve at bestå standard intelligens testen. Givet hvor lidt opmærksomhed der bliver givet til amøberne af forskerne, er det lidt overraskende at denne opdagelse bare blev betragtet som ubetydelig.'*/,
        /*'En hypnotisk tåge drev hele besætningen af Udforsknings Skibet under en besværgelse. De mærkelige farver og designs så ud til at blande sig med den menneskelige hjerne på en eller anden måde, hvilket betød at i stedet for søgningen efter underjordisk liv, beskæftigede besætningen sig i stedet med at besvare spørgsmålet ‘*/'Spiser de fremmede faktisk grønne hotdogs'/*?’ Det er overflødigt at sige, at de ikke fandt nogen nye livsformer.'*/,
        /*'Mens der blev søgt efter underjordisk liv, endte */'Udforsknings Skibet i en kosmisk hvirvel'/*, der beskadigede det ydre skrog alvorligt. Besætningen og skibet blev redet af en risikabel manøvre, men de blev nød til at opgive udforskningen og vende tilbage tomhændet.'*/,
        /*'Udforsknings skibet kom frem til en gammel og forladt rumstation, der engang var */'bemandet af nogen tidligere ukendte arter'/*. Efter noget mere intens forskning, blev det dog snart klart at stationen var blot en udførlig fup fra en uddød livsform. Besætningen ødelage de latterlige beskeder, men var ikke i stand til at opdage noget andet af betydning.'*/,
        /*'Besætningen stødte på en */'høj teknologisk AI drevet forsknings station'/* på en ensom og brutal planet. Desværre, var døren til stationen password beskyttet, og AI nægtede at samarbejde. Besætningen brugte dage på at prøve på at afkode password, og forsyningerne begyndte at forsvinde, da en af de mere upåfaldende besætnings medlemmer ramte kombinationen og knækkede koden. Desværre, viste stationen sig at være en skuffelse, og AI var ikke andet end en omfattende hjemmestyrings system. Besætningen besluttede at vende hjem.'*/,
        /*'En teknisk fejl i navigations modulet tog Udforsknings Skibet faretruende tæt på */'begivenhedshorisonten ved et sort hul'/*. Besætningen var i stand til at vende rundt i time, men endte med at dræne deres brændstofs forsyninger, og blev nød til at afslutte søgningen efter nye livsforme uden succes.'*/,
        /*TODO: dk 'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
        /*'Udforsknings skibets besætning var splittet på grund af kampene fra starten, */'indtil et mytteri til sidst brød ud'/*. De strandede besætnings medlemmer blev lokaliserede og redet, men de rapporterede at mytteristerne har taget kontrol over skibet og har skabt et bånd med rum piraterne. Som et resultat af denne hændelse, er alle skibs besætninger nu forpligtet til at deltage i obligatoriske team building seminarer hvert kvartal.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*TODO: dk 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*'På dens søgning efter intelligente livsformer, stoppede skibet over på en tidligere uudforsket måne. I det mindre, er der ikke nogen der har rapporteret om månen før. Det blev snart klart hvorfor. Besætningen formået at slippe af med et nødsignal, men på det tidspunkt var det for sent. Vækket af skibets ankomst, */'fortærede gigantiske magma orme skibet og dens'/* besætning indeni, indenfor et par. minutter.'*/,
        /*'Udforsknings skibet har formået at finde en intelligent fremmed art, */'men de viste sig at være fjendtlige'/*. At dømme efter det sidste signal der blev sendt af besætningen, ville det se ud som om at rumvæsnerne tog dem væk som fanger. Hver yderligere forsøg på at lokalisere skibet og dens besætning er mislykkedes.'*/,
        /*TODO: dk 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*TODO: dk 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*TODO: dk 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*TODO: dk 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*'Udforsknings skibet har detekteret nogen lovende signaler. Men efter at have fundet kilden til signalet, */'holdte den lige pludselig op med at sende'/*. Søgnings teamet blev sendt afsted, men de kunne ikke finde nogen spor af skibets lokation. Den må være tabt i tomrummet.'*/,
        /*TODO: dk 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /*TODO: dk *//Bei den Koordinaten .+ wurde die Lebensform .+ gefunden und der Lebensformverwaltung hinzugefügt/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /*TODO: dk *//Dennoch konnten unsere Botschafter unser Wissen über sie um (?<xp>\d+) Erfahrung verbessern/g,
};