import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const en: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'At the start of their exploration, they were able to decipher some promising coordinates they’d obtained from a mysterious message. But when the Exploration Ship reached the sector the coordinates mentioned, */'all the crew found was a gigantic debris field left behind after a battle'/*. The search for survivors was ultimately fruitless.'*/,
        /*'A */'magnetic asteroid field was disrupting the scanners'/*. What appeared to be a promising signal of intelligent extra-terrestrial life was just a disruption in the measurement instruments and no new lifeforms could be found.'*/,
        /*'Just as the Exploration Ship intercepted a promising radio signal, all of their communication systems suddenly went down. Given the circumstances, it was not only */'impossible to make contact with potential intelligent lifeforms'/*, but it would also have been dangerous to continue the mission. So the crew returned home disappointed, but unharmed.'*/,
        /*'A */'nebula with some form of consciousness has been discovered'/* in a largely unexplored corner of our system! Our intergalactic emissaries were beside themselves, and there was a serious media circus when the probe was sent into the cloud. Attempts to communicate with the nebula however soon revealed that its intelligence was somewhere on a par with that of a cockroach. The excitement ebbed away, and it was decided to quietly sweep the whole episode under the carpet.'*/,
        /*'Searching for new lifeforms, the Exploration Ship */'followed some mysterious signals that seemed to be coming from the far side of an unknown planet'/*. The intergalactic envoys on board had already retrieved the greeting pack and activated the translation computer, but it turned out that the signal was coming from a shipwreck. The ship is clearly of extra-terrestrial origin, but unfortunately there’s no signs of a crew. This meant no new lifeform was found.'*/,
        /*'The Exploration Ship had been underway for sometime when */'it came to light that a fatal bug had slipped into the scanning software'/*. This unfortunately meant that no new lifeforms could be found.'*/,
        /*'Our intergalactic emissaries visited a */'planet with an extremely clean insectoid species'/*, assuming they must be intelligent, but was disappointed by what they discovered. After watching them munch through the contents of the ship’s trash compactor, it was decided to return them to their planet, despite a few crewmates’ suggestion to keep a couple on board.'*/,
        /*'The researchers on board the exploration ship were ecstatic to */'discover a neural network in the middle of an asteroid field'/*. Which is why they were all the more disappointed when it turned out to be nothing more than a cluster of intercepted news reports about centuries old sports results, which had developed a life of its own like some kind of space couch pundit. The crew returned downtrodden, without learning anything more significant than who last won some ashes or other.'*/,
        /*'The crew of the exploration ship were over the moon when the */'results of tests on the fungal spores suggested they had found intelligent life'/*. Sadly, it turned out that some joker had manipulated the test results just to embarrass a rival researcher. The spores were in reality no more intelligent than those found behind the back of the microwave in the galley. The troublemaker was suspended and dropped off at the nearest planet, before the ship returned home.'*/,
        /*'Promising signals guided the Exploration Ship to */'a mysterious golden sphere floating alone in the depths of space'/*. Despite all the efforts of the intergalactic envoys on board, they were unable to find an entrance or make any sort of contact with the strange object before it suddenly jumped away.'*/,
        /*'On an unexplored planet, the exploration ship discovered a */'floral system that was far more intelligent than first appeared'/*. When the crew tried to investigate, however, strange uniformed guard robots appeared and warned them that the plants were private property. Ignoring the potential difficulties for breaking intergalactic trespassing laws, the researchers steeled their resolve and extracted some samples during a covert operation under cover of darkness, before quickly making for orbit. Sadly, the operation was clearly a little TOO covert for the likes of a bunch of boffins, and back on board ship they discovered their riskily acquired samples were nothing more than regular house plants.'*/,
        /*'On their search for extraterrestrial intelligence, the */'exploration ship had already spent fruitless months aimlessly scouring the galaxy'/*, when they finally discovered the alien equivalent of a paramecium! It didn’t exactly fit the criteria of intelligent life, but after so many monotonous months of searching, the crew decided to consider this discovery of even unintelligent life a success, and returned home without any notable news.'*/,
        /*'The highly promising signals that the Exploration Ship */'tracked were sadly lost in a cosmic fog'/*. They continued the search for a while longer, but they couldn’t find any new lifeforms.'*/,
        /*'After intensive searching, the crew of the exploration ship discovered a */'luminescent species of giant amoeba'/* ! Sadly the single-celled organisms had some issues trying to pass the standard intelligence tests. Given how little attention is paid to amoebae by researchers, it is little surprise that this discovery was similarly considered insignificant.'*/,
        /*'A hypnotic fog drew the entire crew of the Exploration Ship under its spell. The strange colours and designs seem to interfere with the human brain somehow, which meant that instead of searching for extra-terrestrial life, the crew instead concerned themselves with answering the question ‘*/'Do aliens actually eat green hotdogs'/*?’ Needless to say that they didn’t find any new lifeforms.'*/,
        /*'While searching for extra-terrestrial life, the Exploration Ship ended up in */'a cosmic vortex that severely damaged the outer hull'/*. The crew and ship were saved by a risky flight manoeuvre, but they had to give up the exploration and return empty-handed.'*/,
        /*'The exploration ship came upon an */'old and abandoned space station that was once manned by some previously unknown species'/*. After more intensive study, however, it soon became clear that the station was merely an elaborate hoax from an extinct lifeform. The crew destroyed the derisory messages, but were unable to discover anything else of note.'*/,
        /*'The crew came across a */'high-tech AI-driven research station'/* on a lonely and savage planet. Unfortunately, the door to the station was password protected, and the AI refused to cooperate. The crew spent days trying to decipher the password, and the supplies were starting to dwindle, when one of the more inconspicuous crew members hit upon the combination and cracked the code. Sadly, the station turned out to be a disappointment, and the AI was nothing more than an elaborate home management system. The crew decided to return home.'*/,
        /*'A technical error in the navigation module took the Exploration Ship */'dangerously close to the event horizon of a black hole'/*. The crew were able to turn around just in time but ended up draining their fuel supplies and so had to break off the search for new lifeforms without success.'*/,
        /*'The exploration ship reported with excitement that they had */'encountered an identical ship from a parallel universe'/*. The crew from this dimension even had the same names. But the similarities stopped there: at the welcome party, the guests were so boorish that the crew soon expelled them from our universe. Disappointed, yet simultaneously relieved, the crew returned home.'*/,
        /*'The crew of the exploration ship was riven by infighting from the off, */'until eventually a mutiny broke out'/*. The marooned crew members were located and rescued, but they reported that the mutineers had taken control of the ship and joined a band of space pirates. As a result of this incident, all ship crews are now obliged to take part in mandatory team-building seminars every quarter.'*/
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'The crew of the exploration ship successfully made contact with a previously unknown alien species. */'First impressions suggested they were benevolent'/*. However the reports from our emissary and the crew became increasingly euphoric, which is why we must assume that they were subject to some kind of hypnosis. The final report we received was a joyous proclamation on behalf of the entire crew that they would prefer to remain with these friendly aliens. The ship and its crew have disappeared without trace.'*/,
        /*'On its search for intelligent lifeforms, the ship stopped over on a previously unexplored moon. At least, the moon had never been reported upon. It soon became clear why. The crew managed to get off a distress signal, but by then it was too late. Awoken by the ship’s arrival, */'gigantic magma worms devoured the ship'/* and its crew within in a matter of minutes.'*/,
        /*'The exploration ship managed to track down an intelligent alien species, but they turned out to be hostile. Judging by the last signal sent by the crew, it would */'appear that the aliens took them away as prisoners'/*. Every further attempt to locate the ship and its crew has failed.'*/,
        /*'The exploration ship stopped at an unknown planet on its journey to stock up on supplies. The planet was shrouded in a strange fog, which */'the crew were quickly able to identify as sleeping gas'/*. But upon further inspection, it soon became apparent that the gas was so strong that both the ship and her crew were unsalvageable.'*/,
        /*'The crew of this exploration ship had already earned themselves a reputation as a somewhat maverick outfit, brave to the extent of being foolhardy, which is why they looked to be the perfect match for this mission. Maybe they thought */'they could just fly straight through the asteroid field'/*? Sadly, it will be difficult to piece together answers from the wreckage of their ship.'*/,
        /*'It appears that the */'exploration ship has been lost in a hitherto'/* unknown singularity. There has been no sign of life from the crew since.'*/,
        /*'The exploration fleet flew into */'an ambush laid by a belligerent alien species'/*. They utterly pulverised the exploration ship before initial contact could even be established.'*/,
        /*'The exploration ship detected some promising signals. But after hunting down the source of signal, */'it suddenly stopped transmitting'/*. Search teams were dispatched, but couldn’t find any trace of the ship’s location. It must be lost to the void.'*/,
        /*'The ship’s navigator must have been so deeply concentrated on following the strange signal that he lost sight of the fact that they were operating near a black hole. The ship edged too close to its gravitational well, and despite the crew’s best efforts, */'there was nothing to stop them being dragged inside'/*. To avoid any more such unnecessary losses, the report suggests that automatic black hole alarms be integrated as standard in future.'*/,
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /and added to the Lifeforms menu/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /our envoys were able to improve our knowledge about them by (?<xp>\d+) XP/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*'The Exploration Ship has found some artefacts */'but cannot recover them as your storage is full',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'The Exploration Ship has */'found a small number of artefacts',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'The Exploration Ship has */'found a large quantity of artefacts',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*LOCA: en 'The Exploration Ship has'found a huge quantity of artefacts'*/'------------------------------------------------------------------------------------------------------------------------------',
        },
        numberOfArtifacts: /Artefacts found: (?<artifacts>\d+)/i,
    }
};