import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const es: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Al principio de la exploración, se pudieron */'descifrar unas coordenadas muy prometedoras a partir de un mensaje misterioso'/* . Sin embargo, cuando la nave de exploración llegó al sector indicado, la tripulación únicamente encontró un campo de escombros inmenso resultante de un conflicto armado. No se pudieron encontrar supervivientes.'*/,
        /*'Un */'campo de asteroides magnético interfirió inoportunamente'/* con los escáneres. Lo que parecía una señal prometedora de vida extraterrestre inteligente no era más que una alteración en los instrumentos de medición. No se pudo encontrar ninguna nueva forma de vida.'*/,
        /*'Justo cuando la nave de exploración pudo detectar un mensaje de radio muy prometedor, se */'produjo un error total de los sistemas de comunicación'/* . Bajo estas circunstancias, no solo resultó imposible contactar con formas de vida potencialmente inteligentes, sino que proseguir con la misión habría sido peligroso. Por tanto, la tripulación regresó, decepcionada pero ilesa.*/,
        /*'¡Se descubrió */'una nébula cósmica consciente en un sistema planetario prácticamente'/* inexplorado! Los embajadores intergalácticos, entusiasmados, enviaron una sonda. La atención mediática era inmensurable. Los primeros intentos de comunicación evidenciaron un bajo nivel de inteligencia, similar al de los insectos terrestres. La emoción decayó rápidamente y la embajada corrió un tupido velo.'*/,
        /*'Mientras buscaba nuevas formas de vida, la nave de exploración descubrió unas señales misteriosas que parecían */'proceder de la cara oculta de un planeta desconocido'/* . Los embajadores intergalácticos que iban a bordo prepararon el paquete de bienvenida y el traductor informático, pero al final la señal resultó provenir de los restos de una nave destruida. La nave era claramente de origen alienígena, pero no quedaba ni rastro de los pilotos, lamentablemente. Por eso no se pudo detectar forma de vida alguna.'*/,
        /*'La nave de exploración llevaba ya algún tiempo desarrollando su misión cuando se */'produjo un error grave en el software de escaneado'/* . Por desgracia, no se pudo detectar ninguna forma de vida.'*/,
        /*'¡Vaya! La especie */'alienígena insectoide supuestamente inteligente'/* resultó ser bastante simple. Nuestro equipo de embajadores intergalácticos se basó en la increíble limpieza observada en su planeta de origen para realizar sus estimaciones. La verdad afloró cuando devoraron el contenido del compactador de basura de nuestra nave. Alguien de la tripulación votó a favor de conservar un par de ejemplares, pero la decisión final fue devolverlos a su planeta.'*/,
        /*'Los investigadores de la nave de exploración */'hallaron una red neuronal en medio de un campo de asteroides'/* . Cuando se dieron cuenta de que no era más que un cúmulo de señales desviadas que contenían algunos mensajes con noticias deportivas de hace cientos de años de un grupo de parroquianos de un bar, la decepción fue enorme. La tripulación regresó decaída y con las manos vacías.'*/,
        /*'La tripulación de la nave de exploración no cabía en sí de gozo: */'las esporas de moho que estaban investigando parecían arrojar indicios'/* de vida inteligente. Poco después comprobaron que algún gracioso había manipulado los resultados experimentales para poner en evidencia a un investigador rival. En realidad, las esporas eran tan inteligentes como el moho de cualquier cocina terrícola. El culpable acabó despedido y desembarcó en el siguiente planeta y la tripulación regresó sin resultados.'*/,
        /*'Unas señales prometedoras condujeron a la nave de exploración hacia una */'misteriosa esfera dorada que flotaba solitaria'/* en las profundidades del espacio. A pesar de todos los esfuerzos de los embajadores intergalácticos a bordo, no se pudo encontrar ninguna entrada ni realizar ningún contacto con el extraño objeto antes de que desapareciese de un salto.'*/,
        /*'La nave de exploración recorrió un planeta desconocido y descubrió un sistema botánico más inteligente de lo habitual. La tripulación se disponía a analizarlo cuando */'apareció una misteriosa guardia robótica en uniforme indicando'/* que se encontraban en propiedad privada. Los investigadores no estaban dispuestos a rendirse a pesar de la amenaza de enfrentarse a acciones legales intergalácticas, así que extrajeron muestras durante una operación secreta en medio de una noche envuelta en la niebla. A continuación, pusieron pies en polvorosa. Como no se veía nada, las muestras que se llevaron resultaron ser de plantas normales y corrientes.'*/,
        /*'¡La nave de exploración llevaba meses vagando por la galaxia en busca de vida inteligente */'cuando se encontró con un pariente alienígena del paramecio'/* ! No era una forma de vida inteligente, pero, entre los nervios y el cansancio del viaje, la tripulación se dio por satisfecha y decidió regresar sin descubrimientos significativos.'*/,
        /*'Las prometedoras señales que siguió la nave de */'exploración se perdieron en una niebla cósmica'/* . La búsqueda continuó durante un tiempo, pero no fue posible descubrir nuevas formas de vida.'*/,
        /*'Tras una búsqueda larga e intensa, ¡la tripulación de la nave de */'exploración halló un tipo de ameba gigante luminiscente'/* ! El test estándar de identificación de inteligencia extraterrestre resultó ser demasiado complejo para las amebas. Si a eso le sumamos el hecho de que las amebas siguen siendo una especie incomprendida entre los círculos de investigación, no es de extrañar que el descubrimiento se clasificase como irrelevante.'*/,
        /*'Una niebla hipnótica cautivó a la totalidad de la tripulación de una nave de exploración. Los patrones y colores alienígenas parecían interferir con el cerebro humano de forma poco propicia, de modo que, en lugar de dedicarse a buscar vida alienígena, la tripulación de la nave se obsesionó con responder esta pregunta: "¿*/'Los alienígenas comen perritos calientes de color verde'/* ?". Huelga decir que no dieron con ninguna forma de vida nueva.'*/,
        /*'Durante la búsqueda de vida extraterrestre, la nave de exploración quedó */'atrapada en un vórtice cósmico que dañó gravemente'/* su casco exterior. Gracias a una arriesgada maniobra de vuelo, la nave y la tripulación se pudieron salvar, pero tuvo que abandonar la exploración y regresar con las manos vacías.'*/,
        /*'La nave de exploración se topó con una */'vieja estación espacial abandonada y habitada por seres'/* hasta ahora desconocidos. Tras una investigación exhaustiva, la tripulación determinó que se trataba de una broma rebuscada que había dejado allí alguna forma de vida ya extinta. La tripulación destruyó el emisor de señales y se marchó con las manos vacías.'*/,
        /*'La tripulación descubrió un */'centro de investigación de última generación en medio'/* de un planeta inexplorado. Parecía estar controlado y vigilado por una inteligencia artificial. Se necesitaba una contraseña para abrir la puerta principal y la IA rechazaba toda vía de comunicación. Tras varios días y múltiples intentos, justo cuando escaseaban las provisiones, un miembro de la tripulación consiguió descifrar el enigma la contraseña. En el interior de las instalaciones, comprobaron que la IA no era más que un elaborado sistema de gestión de hogar, así que la tripulación, decepcionada, puso rumbo a casa.'*/,
        /*'Debido a un fallo técnico en el módulo de navegación, la nave de */'exploración se acercó peligrosamente al horizonte de sucesos de un agujero negro'/* . La tripulación consiguió por los pelos alejarse de él, pero utilizó todos sus suministros de combustible en el proceso y, por tanto, tuvo que abortar la búsqueda de nuevas formas de vida.'*/,
        /*'La nave de exploración informó con entusiasmo sobre el */'descubrimiento de un vehículo idéntico procedente de un universo espejo'/* . ¡Hasta los nombres de los miembros de la tripulación de la otra dimensión eran los mismos! Sin embargo, pronto empezaron a surgir diferencias: los invitados del otro universo asistieron a la fiesta de bienvenida, pero se comportaron de forma muy grosera y se les invitó a regresar a su hogar. Nuestra nave de exploración puso rumbo a casa con sentimientos encontrados: una gran decepción y al mismo tiempo una cierta sensación de alivio...'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'La tripulación de la nave de exploración tuvo que lidiar con numerosos conflictos internos. */'Al final, se desató un motín'/* . Los miembros de la tripulación expulsados fueron rescatados, pero informaron de que el otro bando había tomado el control de la nave para unirse a una banda de piratas espaciales. A raíz de este incidente, se han organizado seminarios para fomentar el espíritu de grupo que son obligatorios para todas las tripulaciones.'*/,
        /*'La tripulación de la nave de exploración logró */'establecer contacto con una especie alienígena desconocida hasta la fecha'/* . En un primer momento, no parecía una civilización hostil. Sin embargo, los mensajes de nuestra tripulación y embajadores empezaron a volverse demasiado eufóricos. Asumimos que habían entrado en algún tipo de trance hipnótico. Las últimas señales de vida consistieron en un alegre anuncio de parte de toda la tripulación: "¡Nos quedamos a vivir PARA SIEMPRE con esta especie TAN MARAVILLOSA!". Nunca volvimos a saber de ellos.'*/,
        /*'En su misión de búsqueda de formas de vida inteligentes, la nave hizo una pequeña parada en una luna inexplorada. Pronto quedó claro por qué no había datos previos sobre el cuerpo celeste. La tripulación consiguió enviar una señal de socorro, pero ya era demasiado tarde. */'Los colosales gusanos magmáticos'/* , asustados por el estruendo del aterrizaje, devoraron la nave y a toda la tripulación en cuestión de minutos.'*/,
        /*'La nave de exploración detectó una especie alienígena inteligente, pero resultó ser hostil. La */'última transmisión de la tripulación indica que fueron capturados'/* por los alienígenas. Se ha intentado averiguar el paradero de la nave y su tripulación en vano.'*/,
        /*'La nave de exploración hizo una parada en un planeta desconocido para reponer suministros. El planeta estaba envuelto en una neblina misteriosa que la */'tripulación identificó inicialmente como un gas con propiedades soporíferas'/* . El gas resultó ser tan potente que la nave y la tripulación se perdieron para siempre.'*/,
        /*'La tripulación de esta nave de exploración era famosa por sus atrevidas maniobras. Una tripulación tan intrépida era perfecta para una misión como esta. Seguro que pensaron que podrían */'atravesar el campo de asteroides sin mayor problema'/* . Una maniobra demasiado temeraria... solo hemos encontrado los restos de la nave.'*/,
        /*'La nave de exploración */'parece haberse perdido en una singularidad desconocida'/* hasta la fecha. No se ha hallado ni rastro de la tripulación.'*/,
        /*'La flota de exploración */'cayó en una emboscada de una especie alienígena hostil'/* durante su misión. Sospechamos que se trata de una especie inteligente, pero se mostró extremadamente agresiva y destruyó la nave de exploración antes de que pudiéramos establecer contacto.'*/,
        /*'La nave de exploración había captado una señal prometedora. Seguimos el rastro energético */'hasta que se perdió la conexión y no se pudo restablecer'/* . Las unidades exploradoras enviadas no hallaron pistas sobre el paradero de la nave. Debe haberse perdido en la inmensidad del espacio.'*/,
        /*'Los informes apuntan a que el tripulante de navegación se distrajo rastreando señales cósmicas y */'perdió de vista las mediciones del agujero negro cercano'/* . La nave quedó atrapada en el campo gravitatorio y resultó succionada. La tripulación no pudo hacer nada. Estamos estudiando la implementación de señales de aviso automáticas al acercarse a agujeros negros para evitar tragedias similares en el futuro.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /Se ha encontrado la forma de vida .+ en las coordenadas .+ y se ha añadido la administración de la forma de vida/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Sin embargo, nuestros embajadores han conseguido mejorar nuestros conocimiento sobre ellos en (?<xp>\d+) de experiencia/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*LOCA: es 'The Exploration Ship has found some artefacts */'but cannot recover them as your storage is full',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*LOCA: es 'The Exploration Ship has */'found a small number of artefacts',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*LOCA: es 'The Exploration Ship has */'found a large quantity of artefacts',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*LOCA: es 'The Exploration Ship has'found a huge quantity of artefacts'*/'------------------------------------------------------------------------------------------------------------------------------',
        },
        numberOfArtifacts: /*LOCA: es *//Artefacts found: (?<artifacts>\d+)/i,
    },
};