import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const es_ar: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*LOCA: es-ar'Zu Beginn der Erkundung konnten einige */'vielversprechende Koordinaten aus einer geheimnisvollen Nachricht'/* entschlüsselt werden. Als das Erkundungsschiff jedoch den angegebenen Sektor erreichte, fand die Crew nur noch das riesige Trümmerfeld eines bewaffneten Konflikts vor. Die Suche nach Überlebenden blieb erfolglos.'*/,
        /*LOCA: es-ar'Ein */'magnetisches Asteroidenfeld störte ungünstigerweise die Scanner'/*. Was wie ein vielversprechendes Signal intelligenten außerirdischen Lebens aussah, war nur eine Störung der Messinstrumente und es konnte keine neue Lebensform gefunden werden.'*/,
        /*LOCA: es-ar'Gerade als das Erkundungsschiff einen vielversprechenden Funkspruch auffangen konnte, */'kam es zu einem Totalausfall sämtlicher Kommunikationssysteme'/*. Unter diesen Umständen war nicht nur jede Kontaktaufnahme mit eventuellen intelligenten Lebensformen ausgeschlossen, ein Fortführen der Mission wäre auch gefährlich gewesen. Deshalb kehrte die Crew enttäuscht, aber unversehrt zurück.'*/,
        /*LOCA: es-ar'In einem noch größtenteils unerforschten Planetensystem */'wurde ein kosmischer Nebel mit Bewusstsein entdeckt'/* ! Die intergalaktischen Botschafter gerieten in helle Aufregung, weshalb unter großer medialer Aufmerksamkeit eine Sonde entsandt wurde. Beim Kommunikationsversuch mit dem Nebel stellte sich aber schnell heraus, dass seine Intelligenz kaum über der von einfachen Insekten lag. Die Aufregung schwand und es wurde beschlossen, einen Mantel des Schweigens über die ganze Aktion zu breiten.'*/,
        /*LOCA: es-ar'Bei der Suche nach neuen Lebensformen folgte das Erkundungsschiff einigen mysteriösen Signalen, die */'von der Rückseite eines unbekannten Planeten zu stammen'/* schienen. Die intergalaktischen Botschafter an Bord hatten schon das Begrüßungspaket geholt und den Übersetzungscomputer aktiviert, doch es stellte sich heraus, dass das Signal von einem Schiffswrack stammt. Das Schiff ist eindeutig außerirdischer Herkunft, aber von den Piloten fehlt leider jede Spur. So konnte keine neue Lebensform entdeckt werden.'*/,
        /*'La nave de exploración llevaba ya algún tiempo desarrollando su misión cuando se */'produjo un error grave en el software de escaneado'/* . Por desgracia, no se pudo detectar ninguna forma de vida.'*/,
        /*'¡Vaya! La especie */'alienígena insectoide supuestamente inteligente resultó ser bastante simple'/* . Nuestro equipo de embajadores intergalácticos se basó en la increíble limpieza observada en su planeta de origen para realizar sus estimaciones. La verdad afloró cuando devoraron el contenido del compactador de basura de nuestra nave. Alguien de la tripulación votó a favor de conservar un par de ejemplares, pero la decisión final fue devolverlos a su planeta.'*/,
        /*LOCA: es-ar'Vollkommen begeistert fanden die Forscher des Erkundungsschiffes */'ein neuronales Netzwerk mitten in einem Asteroidenfeld'/*. Die Enttäuschung war groß, als sich herausstellte, dass es sich lediglich um ein Cluster verfangener Nachrichten mit jahrhundertealten Sportergebnissen handelte, die das Eigenleben eines schlecht informierten Stammtisches entwickelt hatten. Die Crew kehrte niedergeschlagen und ohne signifikante Ergebnisse zurück.'*/,
        /*'La tripulación de la nave de exploración no cabía en sí de gozo: */'las esporas de moho que estaban investigando parecían arrojar indicios de vida inteligente'/* . Poco después comprobaron que algún gracioso había manipulado los resultados experimentales para poner en evidencia a un investigador rival. En realidad, las esporas eran tan inteligentes como el moho de cualquier cocina terrícola. El culpable acabó despedido y desembarcó en el siguiente planeta y la tripulación regresó sin resultados.'*/,
        /*LOCA: es-ar'Vielversprechende Signale führten das */'Erkundungsschiff zu einer mysteriösen goldenen Sphäre'/*, die einsam in den Tiefen des Weltalls schwebte. Trotz aller Bemühungen der intergalaktischen Botschafter an Bord konnte weder ein Eingang gefunden noch irgendwie Kontakt zu dem merkwürdigen Objekt hergestellt werden, bevor es sich mit einem Sprung davonmachte.'*/,
        /*LOCA: es-ar'Das Erkundungsschiff entdeckte auf einem unbekannten Planeten ein Pflanzensystem, das deutlich intelligenter als gewöhnlich erschien. Als die Crew es untersuchen wollte, wurden sie von */'mysteriösen Wachrobotern in Uniform aufgehalten'/*, die darauf hinwiesen, dass dies Privateigentum sei. Die Forscher gaben trotz Androhung intergalaktischer Gerichtsverfahren nicht auf und extrahierten in einer Nacht-und-Nebel-Aktion Proben, um sich dann schnell aus dem Staub zu machen. Offenbar war es zu dunkel und neblig, denn die gesicherten Funde stellten sich auf dem Schiff als gewöhnliche Zimmerpflanzen heraus.'*/,
        /*'¡La nave de exploración llevaba meses vagando por la galaxia en busca de vida inteligente */'cuando se encontró con un pariente alienígena del paramecio'/* ! No era una forma de vida inteligente, pero, entre los nervios y el cansancio del viaje, la tripulación se dio por satisfecha y decidió regresar sin descubrimientos significativos.'*/,
        /*'Las prometedoras señales que siguió la nave de */'exploración se perdieron en una niebla cósmica'/* . La búsqueda continuó durante un tiempo, pero no fue posible descubrir nuevas formas de vida.'*/,
        /*LOCA: es-ar'Nach intensiver Suche fand die Crew des */'Erkundungsschiffes eine lumineszente Riesenamöbenart'/* ! Leider hatten die Amöben Schwierigkeiten bei der Bearbeitung des standardisierten Tests zur Identifikation außerirdischer Intelligenz. Deshalb und weil in Forscherkreisen Amöben leider immer noch verkannt werden, wurde diese Entdeckung als nicht relevant eingestuft.'*/,
        /*LOCA: es-ar'Ein hypnotischer Nebel zog die gesamte Crew des Erkundungsschiffes in seinen Bann. Die fremdartigen Farben und Muster scheinen auf ungünstige Weise mit dem menschlichen Gehirn zu interferieren, wodurch die Besatzung statt der Suche nach außerirdischem Leben der Beantwortung der Frage „*/'Essen Aliens eigentlich grüne Hotdogs'/*?“ nachging. Überflüssig zu erwähnen, dass sie keine neue Lebensform fanden.'*/,
        /*'Durante la búsqueda de vida extraterrestre, la nave de */'exploración quedó atrapada en un vórtice cósmico que dañó gravemente su casco exterior'/* . Gracias a una arriesgada maniobra de vuelo, la nave y la tripulación se pudieron salvar, pero tuvo que abandonar la exploración y regresar con las manos vacías.'*/,
        /*LOCA: es-ar'Das Erkundungsschiff stieß auf eine */'alte verlassene Raumstation, die von bisher unbekannten Lebewesen'/* bewohnt wurde. Nach eingehender Untersuchung musste man allerdings feststellen, dass es sich um den ausgeklügelten Scherz einer bereits ausgestorbenen Lebensform handelte. Die Crew zerstörte die hämischen Botschaften, konnte ansonsten aber nichts entdecken.'*/,
        /*LOCA: es-ar'Auf einem wilden Planeten */'entdeckte die Crew eine hochmoderne Forschungsstation'/*, die von einer künstlichen Intelligenz gesteuert und bewacht wurde. Die Tür zur Station war allerdings durch ein Passwort geschützt und die KI verweigerte die Kommunikation. Nachdem nach tagelangen Ratespielen die Vorräte knapp wurden, gelang es einem bisher eher unscheinbaren Mitglied der Crew, das Passworträtsel zu entschlüsseln. Im Inneren der Anlage stellte sich aber leider heraus, dass die KI nur ein elaboriertes Home-Management-System war und die Crew machte sich enttäuscht auf den Heimweg.'*/,
        /*'Debido a un fallo técnico en el módulo de navegación, la */'nave de exploración se acercó peligrosamente al horizonte de sucesos de un agujero negro'/* . La tripulación consiguió por los pelos alejarse de él, pero utilizó todos sus suministros de combustible en el proceso y, por tanto, tuvo que abortar la búsqueda de nuevas formas de vida.'*/,
        /*LOCA: es-ar'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*LOCA: es-ar'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
        /*LOCA: es-ar'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*LOCA: es-ar'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /*LOCA: es-ar'Das Erkundungsschiff schaffte es zwar, eine intelligente Alienspezies aufzuspüren, */'diese erwies sich jedoch als feindselig'/*. Dem letzten Funkspruch der Crew ist zu entnehmen, dass sie von den Außerirdischen als Gefangene abtransportiert wurden. Jeglicher Versuch, den weiteren Verbleib des Schiffes und seiner Besatzung aufzuklären, blieb leider erfolglos.'*/,
        /*LOCA: es-ar'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*LOCA: es-ar'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*LOCA: es-ar'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*LOCA: es-ar'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*LOCA: es-ar'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*LOCA: es-ar'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /Se ha encontrado la forma de vida .+ en las coordenadas .+ y se ha añadido/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /nuestros embajadores han conseguido mejorar nuestros conocimiento sobre ellos en (?<xp>\d+) de experiencia/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*LOCA: es-ar 'The Exploration Ship has found some artefacts */'but cannot recover them as your storage is full',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*LOCA: es-ar 'The Exploration Ship has */'found a small number of artefacts',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*LOCA: es-ar 'The Exploration Ship has */'found a large quantity of artefacts',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*LOCA: es-ar 'The Exploration Ship has */'found a huge quantity of artefacts',
        },
        numberOfArtifacts: /*LOCA: es-ar *//Artefacts found: (?<artifacts>\d+)/i,
    },
};