import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const fr: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Au début de l`exploration, quelques */'coordonnées ont été décryptées à partir d`un mystérieux message'/* . Quand le vaisseau d`exploration a atteint le secteur indiqué, l`équipage n`a trouvé que l`immense champ de ruines d`un combat armé. Les recherches de survivants sont restées vaines. '*/,
        /*LOCA: fr 'Ein */'magnetisches Asteroidenfeld störte ungünstigerweise die Scanner'/*. Was wie ein vielversprechendes Signal intelligenten außerirdischen Lebens aussah, war nur eine Störung der Messinstrumente und es konnte keine neue Lebensform gefunden werden.'*/,
        /*LOCA: fr 'Gerade als das Erkundungsschiff einen vielversprechenden Funkspruch auffangen konnte, */'kam es zu einem Totalausfall sämtlicher Kommunikationssysteme'/*. Unter diesen Umständen war nicht nur jede Kontaktaufnahme mit eventuellen intelligenten Lebensformen ausgeschlossen, ein Fortführen der Mission wäre auch gefährlich gewesen. Deshalb kehrte die Crew enttäuscht, aber unversehrt zurück.'*/,
        /*'Une */'nébuleuse cosmique dotée d`une conscience'/* a été découverte dans un système planétaire encore en grande partie inexploré ! Les ambassadeurs intergalactiques étaient ravis et ont envoyé une sonde dans un contexte très médiatisé. En essayant de communiquer avec la nébuleuse, il s`est rapidement avéré que son intelligence ne dépassait guère celle de simples insectes. L`excitation s`est estompée et toute l`affaire a été rapidement oubliée.'*/,
        /*LOCA: fr 'Bei der Suche nach neuen Lebensformen folgte das Erkundungsschiff einigen mysteriösen Signalen, die */'von der Rückseite eines unbekannten Planeten zu stammen'/* schienen. Die intergalaktischen Botschafter an Bord hatten schon das Begrüßungspaket geholt und den Übersetzungscomputer aktiviert, doch es stellte sich heraus, dass das Signal von einem Schiffswrack stammt. Das Schiff ist eindeutig außerirdischer Herkunft, aber von den Piloten fehlt leider jede Spur. So konnte keine neue Lebensform entdeckt werden.'*/,
        /*'Le vaisseau d`exploration a voyagé pendant un certain temps */'jusqu`à qu`un bug fatal ne se glisse dans le logiciel'/* d`analyse. Aucune forme de vie n`a été trouvée.'*/,
        /*'Malheureusement, l`espèce extraterrestre insectoïde, */'que nos ambassadeurs intergalactiques ont d`abord crue intelligente'/* en raison de l`extraordinaire propreté de leur planète d`origine, s`est révélée plutôt simple d`esprit. Après avoir dévoré le contenu du compacteur de déchets de bord, ils ont été relâchés sur leur planète, après un vote de l`équipage pour en garder tout de même quelques spécimens.'*/,
        /*'Les chercheurs du vaisseau d`exploration ont trouvé un */'réseau neuronal au milieu d`un champ d`astéroïdes'/* . La déception a été grande en découvrant qu`il ne s`agissait que d`une bulle de fake news mêlées à des résultats sportifs vieux de plusieurs siècles qu`avaient développée des habitués de la désinformation. L`équipage est rentré abattu et sans résultats significatifs. '*/,
        /*LOCA: fr 'Die Crew des Erkundungsschiffes war hellauf begeistert, als */'Untersuchungen von Schimmelsporen intelligentes Leben versprachen'/*. Leider stellte sich heraus, dass ein Witzbold die Forschungsergebnisse manipuliert hatte, um einen rivalisierenden Forscher bloßzustellen. Die untersuchten Sporen waren in Wahrheit kein bisschen intelligenter als der durchschnittliche Schimmelpilz in der Bordküche. Der Unruhestifter wurde auf den nächstbesten Planeten beurlaubt und das Schiff kehrte ergebnislos zurück.'*/,
        /*'Des signaux ont guidé le vaisseau d`exploration */'vers une mystérieuse sphère dorée en orbite'/* , seule, dans les confins de l`espace. Malgré tous les efforts des ambassadeurs intergalactiques à bord, ils n`ont trouvé aucune entrée et aucun contact n`a pu être établi avec cet étrange objet avant qu`il ne s`éloigne soudainement. '*/,
        /*LOCA: fr 'Das Erkundungsschiff entdeckte auf einem unbekannten Planeten ein Pflanzensystem, das deutlich intelligenter als gewöhnlich erschien. Als die Crew es untersuchen wollte, wurden sie von */'mysteriösen Wachrobotern in Uniform aufgehalten'/*, die darauf hinwiesen, dass dies Privateigentum sei. Die Forscher gaben trotz Androhung intergalaktischer Gerichtsverfahren nicht auf und extrahierten in einer Nacht-und-Nebel-Aktion Proben, um sich dann schnell aus dem Staub zu machen. Offenbar war es zu dunkel und neblig, denn die gesicherten Funde stellten sich auf dem Schiff als gewöhnliche Zimmerpflanzen heraus.'*/,
        /*LOCA: fr 'Bei der Suche nach außerirdischem intelligentem Leben irrte das Erkundungsschiff bereits seit Monaten durch die Galaxis, als sie */'endlich einen außerirdischen Verwandten des Pantoffeltierchens'/* fanden! Diese Lebensform war zwar nicht intelligent, aber aufgrund der langen Reise und blankliegender Nerven entschied die Crew, auch mit unintelligentem Leben vorlieb zu nehmen und ohne nennenswerte Funde zurückzukehren.'*/,
        /*LOCA: fr 'Die vielversprechenden Signale, denen das Erkundungsschiff folgte, */'verloren sich leider in einem kosmischen Nebel'/*. Die Suche wurde noch eine Weile fortgesetzt, aber es konnten keine neuen Lebensformen entdeckt werden.'*/,
        /*'Après d`intensives recherches, l`équipage du vaisseau d`exploration a */'trouvé une espèce d`amibe géante luminescente'/* . Malheureusement, les amibes n`ont pas réussi le test standardisé d`identification de l`intelligence extraterrestre. Pour cette raison, et parce que les amibes sont malheureusement encore méconnues dans les milieux de la recherche, cette découverte a été jugée non pertinente.'*/,
        /*LOCA: fr 'Ein hypnotischer Nebel zog die gesamte Crew des Erkundungsschiffes in seinen Bann. Die fremdartigen Farben und Muster scheinen auf ungünstige Weise mit dem menschlichen Gehirn zu interferieren, wodurch die Besatzung statt der Suche nach außerirdischem Leben der Beantwortung der Frage „*/'Essen Aliens eigentlich grüne Hotdogs'/*?“ nachging. Überflüssig zu erwähnen, dass sie keine neue Lebensform fanden.'*/,
        /*LOCA: fr 'Bei der Suche nach außerirdischem Leben */'geriet das Erkundungsschiff in einen kosmischen Vortex'/*, der die Außenhülle schwer beschädigte. Durch ein riskantes Flugmanöver konnten Crew und Schiff gerettet werden, mussten jedoch die Erkundung aufgeben und ohne Ergebnisse zurückkehren.'*/,
        /*LOCA: fr 'Das Erkundungsschiff stieß auf eine */'alte verlassene Raumstation, die von bisher unbekannten Lebewesen'/* bewohnt wurde. Nach eingehender Untersuchung musste man allerdings feststellen, dass es sich um den ausgeklügelten Scherz einer bereits ausgestorbenen Lebensform handelte. Die Crew zerstörte die hämischen Botschaften, konnte ansonsten aber nichts entdecken.'*/,
        /*LOCA: fr 'Auf einem wilden Planeten */'entdeckte die Crew eine hochmoderne Forschungsstation'/*, die von einer künstlichen Intelligenz gesteuert und bewacht wurde. Die Tür zur Station war allerdings durch ein Passwort geschützt und die KI verweigerte die Kommunikation. Nachdem nach tagelangen Ratespielen die Vorräte knapp wurden, gelang es einem bisher eher unscheinbaren Mitglied der Crew, das Passworträtsel zu entschlüsseln. Im Inneren der Anlage stellte sich aber leider heraus, dass die KI nur ein elaboriertes Home-Management-System war und die Crew machte sich enttäuscht auf den Heimweg.'*/,
        /*'Le vaisseau d`exploration s`est dangereusement approché d`un */'trou noir à cause d`une erreur technique dans le module'/* de navigation. L`équipage a réussi à faire demi-tour de justesse à cause de ses réserves de carburant et a dû abandonner la recherche de nouvelles formes de vie. '*/,
        /*LOCA: fr 'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
        /*LOCA: fr 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*LOCA: fr 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*LOCA: fr 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /*LOCA: fr 'Das Erkundungsschiff schaffte es zwar, eine intelligente Alienspezies aufzuspüren, */'diese erwies sich jedoch als feindselig'/*. Dem letzten Funkspruch der Crew ist zu entnehmen, dass sie von den Außerirdischen als Gefangene abtransportiert wurden. Jeglicher Versuch, den weiteren Verbleib des Schiffes und seiner Besatzung aufzuklären, blieb leider erfolglos.'*/,
        /*LOCA: fr 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*LOCA: fr 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*'Il semble que le vaisseau d`exploration */'se soit perdu dans une singularité gravitationnelle'/* jusqu`alors inconnue. Aucun signe de vie de l`équipage n`a été envoyé. '*/,
        /*LOCA: fr 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*LOCA: fr 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*LOCA: fr 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /La forme de vie .+ a été trouvée aux coordonnées suivantes : .+/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /*LOCA: fr *//Dennoch konnten unsere Botschafter unser Wissen über sie um (?<xp>\d+) Erfahrung verbessern/i,
};