import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const fr: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Au début de l`exploration, quelques */'coordonnées ont été décryptées à partir d`un mystérieux message'/* . Quand le vaisseau d`exploration a atteint le secteur indiqué, l`équipage n`a trouvé que l`immense champ de ruines d`un combat armé. Les recherches de survivants sont restées vaines. '*/,
        /*'Un */'champ magnétique d`astéroïdes a malencontreusement perturbé'/* les scanners. Ce qui semblait être un signal prometteur de vie extraterrestre intelligente n`était en fait qu`un dysfonctionnement des instruments de mesure et aucune nouvelle forme de vie n`a pu être détectée.'*/,
        /*'Alors que l`équipage était */'sur le point de capter un signal extraterrestre'/* , tous les systèmes de communication sont tombés en panne. Il était non seulement impossible d`entrer en contact avec d`éventuelles formes de vie intelligentes, mais il aurait été dangereux de poursuivre la mission. L`équipage a décidé de rebrousser chemin.'*/,
        /*'Une */'nébuleuse cosmique dotée d`une conscience'/* a été découverte dans un système planétaire encore en grande partie inexploré ! Les ambassadeurs intergalactiques étaient ravis et ont envoyé une sonde dans un contexte très médiatisé. En essayant de communiquer avec la nébuleuse, il s`est rapidement avéré que son intelligence ne dépassait guère celle de simples insectes. L`excitation s`est estompée et toute l`affaire a été rapidement oubliée.'*/,
        /*'En cherchant de nouvelles formes de vie, le vaisseau d`exploration a suivi quelques */'signaux mystérieux qui semblaient provenir de l`arrière d`une planète'/* inconnue. Les ambassadeurs intergalactiques à bord avaient déjà préparé le cadeau de bienvenue et activé l`ordinateur de traduction, mais il s`est avéré que le signal provenait d`une épave de vaisseau. Le vaisseau était clairement d`origine extraterrestre, mais il n`y a malheureusement aucune trace des pilotes. Aucune forme de vie n`a été trouvée.'*/,
        /*'Le vaisseau d`exploration a voyagé pendant un certain temps */'jusqu`à qu`un bug fatal ne se glisse dans le logiciel'/* d`analyse. Aucune forme de vie n`a été trouvée.'*/,
        /*'Malheureusement, l`espèce extraterrestre insectoïde, */'que nos ambassadeurs intergalactiques ont d`abord crue intelligente'/* en raison de l`extraordinaire propreté de leur planète d`origine, s`est révélée plutôt simple d`esprit. Après avoir dévoré le contenu du compacteur de déchets de bord, ils ont été relâchés sur leur planète, après un vote de l`équipage pour en garder tout de même quelques spécimens.'*/,
        /*'Les chercheurs du vaisseau d`exploration ont trouvé un */'réseau neuronal au milieu d`un champ d`astéroïdes'/* . La déception a été grande en découvrant qu`il ne s`agissait que d`une bulle de fake news mêlées à des résultats sportifs vieux de plusieurs siècles qu`avaient développée des habitués de la désinformation. L`équipage est rentré abattu et sans résultats significatifs. '*/,
        /*'Lorsque */'des analyses de spores de moisissures ont révélé la présence'/* d`une forme de vie intelligente, l`équipage du vaisseau d`exploration s`est montré très enthousiaste quant à la suite des recherches. Malheureusement, un plaisantin avait manipulé les résultats de recherche afin de ridiculiser un chercheur rival. En réalité, les spores étudiées n`étaient pas plus intelligentes que la moisissure au fond de la cuisine de bord. Le fauteur de troubles a été mis en congé sur la planète la plus proche et le vaisseau est rentré sans résultat.'*/,
        /*'Des signaux ont guidé le vaisseau d`exploration */'vers une mystérieuse sphère dorée en orbite'/* , seule, dans les confins de l`espace. Malgré tous les efforts des ambassadeurs intergalactiques à bord, ils n`ont trouvé aucune entrée et aucun contact n`a pu être établi avec cet étrange objet avant qu`il ne s`éloigne soudainement. '*/,
        /*'Sur une planète inconnue, le vaisseau d`exploration a découvert un système végétal qui semblait nettement plus intelligent que d`habitude. Lorsque l`équipage a voulu l`examiner, ils ont été */'arrêtés par de mystérieux robots de garde en uniforme'/* , qui ont mentionné qu`il s`agissait d`une propriété privée. Malgré la menace de procès intergalactiques, les chercheurs n`ont pas renoncé et ont extrait des échantillons dans une opération de nuit et de brouillard, avant de prendre rapidement la poudre d`escampette. Sur le vaisseau, les chercheurs ont rapidement remarqué qu`il s`agissait de vulgaires plantes d`intérieur.'*/,
        /*'À la recherche d`une vie dotée d`intelligence, le vaisseau d`exploration errait depuis des mois à travers la galaxie lorsqu`ils ont */'finalement trouvé un lointain parent de la paramécie'/* . Cette forme de vie n`était certes pas intelligente, mais après ce long voyage, l`équipage a décidé de s`en contenter de rentrer sans avoir fait de découvertes notables.'*/,
        /*'Malheureusement, les signaux prometteurs suivis par le vaisseau d`exploration */'se sont perdus dans un brouillard cosmique'/*. Aucune forme de vie n`a été trouvée.'*/,
        /*'Après d`intensives recherches, l`équipage du vaisseau d`exploration a */'trouvé une espèce d`amibe géante luminescente'/* . Malheureusement, les amibes n`ont pas réussi le test standardisé d`identification de l`intelligence extraterrestre. Pour cette raison, et parce que les amibes sont malheureusement encore méconnues dans les milieux de la recherche, cette découverte a été jugée non pertinente.'*/,
        /*'Un brouillard hypnotique a captivé tout l`équipage du vaisseau d`exploration. Les couleurs et les formes de cette brume cosmique semblent interférer avec le cerveau humain, ce qui a poussé l`équipage à répondre à la question « */'Les extraterrestres mangent-ils des hotdogs verts'/* ? » plutôt que de chercher une vie extraterrestre. Inutile de dire qu`ils n`ont pas trouvé de nouvelle forme de vie.'*/,
        /*'Le vaisseau d`exploration a été */'pris dans un vortex cosmique qui a gravement endommagé'/* la coque extérieure. Une manœuvre de vol risquée a permis de sauver l`équipage et le vaisseau, mais ils ont dû abandonner l`exploration et rentrer sans résultats.'*/,
        /*'Le vaisseau d`exploration */'est tombé sur une ancienne station spatiale abandonnée'/* qui était habitée par des êtres vivants jusqu`alors inconnus. Après une enquête approfondie, les chercheurs ont constaté qu`il s`agissait d`un canular élaboré par une forme de vie déjà éteinte. L`équipage a détruit les messages haineux, mais n`a rien trouvé d`autre.'*/,
        /*'Sur une planète encore sauvage, l`équipage a */'découvert une station de recherche ultramoderne'/* , dirigée et gardée par une intelligence artificielle. La porte de la station était protégée par un mot de passe et l`IA a refusé d`ouvrir la communication. Après avoir tenté sa chance pendant plusieurs jours, alors même que les vivres commençaient à manquer, un membre de l`équipage, jusque-là plutôt discret, a réussi à déchiffrer l`énigme du mot de passe. Malheureusement, une fois à l`intérieur, il s`est avéré que l`IA n`était qu`un système de gestion domestique élaboré et l`équipage a pris le chemin du retour, déçu.'*/,
        /*'Le vaisseau d`exploration s`est dangereusement approché d`un */'trou noir à cause d`une erreur technique dans le module'/* de navigation. L`équipage a réussi à faire demi-tour de justesse à cause de ses réserves de carburant et a dû abandonner la recherche de nouvelles formes de vie. '*/,
        /*'L`équipage est tombé sur un vaisseau */'d`exploration identique provenant d`un univers miroir'/* . Étonnamment, l`équipage de l`autre dimension portait les mêmes prénoms. Mais la comparaison s`est arrêtée là : les invités de l`autre monde se sont montrés si grossiers lors de la fête de bienvenue organisée à la dernière minute qu`ils ont été expulsés de l`univers. L`équipage de notre vaisseau d`exploration est rentré, déçu, mais aussi avec un certain soulagement.'*/,
        /*'Une partie de l`équipage du vaisseau d`exploration a été abandonné sur une planète à cause d`importants */'conflits internes qui ont débouché sur une mutinerie'/* . Les membres de l`équipage abandonnés ont pu être retrouvés. Ils ont rapporté que l`autre partie du groupe avait pris le contrôle du vaisseau et s`était jointe à une bande de pirates de l`espace. Suite à cet incident, des séminaires trimestriels de team building ont été imposés à tous les équipages des vaisseaux.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*LOCA: fr 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*LOCA: fr 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /*'Le vaisseau d`exploration a réussi à trouver une espèce extraterrestre intelligente, */'mais celle-ci s`est révélée hostile'/* . D`après le dernier message radio de l`équipage, ils ont été faits prisonniers par les extraterrestres. Toute tentative pour retrouver le vaisseau et son équipage est malheureusement restée vaine.'*/,
        /*'Au cours de son voyage, le vaisseau d`exploration s`est arrêté sur une planète inconnue pour se réapprovisionner. La planète était enveloppée d`un mystérieux brouillard que l`équipage */'a pu identifier comme étant du gaz soporifique'/* . Après des recherches plus approfondies, ce brouillard s`est avéré si puissant que l`équipage et le vaisseau ont disparu.'*/,
        /*LOCA: fr 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*'Il semble que le vaisseau d`exploration */'se soit perdu dans une singularité gravitationnelle'/* jusqu`alors inconnue. Aucun signe de vie de l`équipage n`a été envoyé. '*/,
        /*'Au cours de sa mission, */'la flotte d`exploration est tombée dans une embuscade tendue'/* par une espèce extraterrestre hostile. Nous supposons qu`elle était dotée d`intelligence, mais elle était aussi très agressive et a détruit le vaisseau d`exploration avant même qu`un contact n`ait pu être établi.'*/,
        /*LOCA: fr 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*'En suivant de puissants signaux cosmiques, l`officier de */'navigation semble avoir été tellement distrait'/* qu`il a complètement perdu de vue le trou noir qui se trouvait à proximité. Le vaisseau est entré dans le champ gravitationnel et malgré les efforts de l`équipage, ils n`ont pas pu l`empêcher d`y être aspiré. Afin d`éviter une nouvelle perte de ce type, on a proposé d`intégrer des signaux d`avertissement automatiques à l`approche de trous noirs.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /La forme de vie .+ a été trouvée aux coordonnées suivantes .+/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /connaissance de cette espèce de (?<xp>\d+) points d`expérience/i,
};