import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const hr: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Na početku svog istraživanja uspjeli su */'dešifrirati neke obećavajuće koordinate koje su dobili putem tajanstvene poruke'/* . Ali kada je Istraživački brod stigao do sektora na kojem se spominju koordinate, sve što posada pronašla bilo je ogromno polje ruševina koje je ostalo nakon bitke. Potraga za preživjelima u konačnici je bila bezuspješna.'*/,
        'Magnetsko polje asteroida omelo je skenere'/* . Ono što se činilo obećavajućim signalom inteligentnog izvanzemaljskog života bio je samo poremećaj u mjernim instrumentima tako da novi oblici života nisu pronađeni.'*/,
        /*'Baš kada je Istraživački brod presreo obećavajući radio signal, */'svi njihovi komunikacijski sustavi iznenada su se pokvarili'/* . S obzirom na okolnosti, ne samo da je bilo nemoguće uspostaviti kontakt s potencijalnim inteligentnim oblicima života, već je također bilo opasno nastaviti misiju dalje. Posada se doma vratila razočarana, međutim nitko nije ozlijeđen.'*/,
        /*'Maglica s nekim oblikom svijesti otkrivena je u */'većinski neistraženom kutku našeg sustava'/* ! Naši međugalaktički izaslanici bili su izvan sebe, i nastao je ozbiljan medijski cirkus kada je sonda poslana u oblak. Međutim, pokušaji komuniciranja s maglicom ubrzo su otkrili da je njezina inteligencija negdje na razini inteligencije žohara. Uzbuđenje je naglo splasnulo i odlučeno je da cijelu epizodu treba potiho pomesti pod tepih.'*/,
        /*'Tragajući za novim oblicima života, Istraživački brod slijedio je neke tajanstvene signale za koje se */'činilo da dolaze s daleke strane nepoznatog planeta'/* . Intergalaktički izaslanici na brodu već su preuzeli paket pozdrava i aktivirali računalo za prevođenje, međutim pokazalo se da signal dolazi s brodoloma. Brod je očito izvanzemaljskog podrijetla, ali nažalost nema znakova posade. To znači da nažalost nisu uspjeli pronaći nove oblike života.'*/,
        /*'Brod za istraživanje već je neko vrijeme letio kada smo */'saznali da je sofver za skeniranje imao fatalnu pogrešku'/* . To znači da nažalost nisu uspjeli pronaći nove oblike života.'*/,
        /*'Naši međugalaktički izaslanici posjetili su planet s izuzetno čistom vrstom insekata, */'pretpostavljajući da moraju biti inteligentni, ali su na kraju bili razočarani'/* onim što su otkrili. Nakon što su ih promatrali kako žvaču sadržaj brodskog kompaktora za smeće, odlučili su ih vratiti nazad na planet, unatoč prijedlogu nekoliko članova posade da zadrže par na brodu.'*/,
        /*'Istraživači na brodu za istraživanje bili su */'oduševljeni otkrivanjem neuronske mreže usred polja asteroida'/* . Zbog toga su bili još više razočarani kada se pokazalo da se ne radi o ničemu drugom osim o klasteru presretnutih vijesti o sportskim rezultatima starim nekoliko stoljeća, koji su razvili svoj vlastiti život poput nekakvog svemirskog eksperta na kauču. Posada se vratila potištena, bez da je saznala išta značajnije od toga tko je zadnji osvojio neki pepeo ili nešto slično.'*/,
        /*'Posada istraživačkog broda bila je iznad mjeseca kada su */'rezultati testova na spore gljivica sugerirali da su pronašli'/* inteligentan život. Nažalost, pokazalo se da je neki šaljivdžija izmanipulirao rezultate testa samo kako bi posramio suparničkog istraživača. Spore u stvarnosti nisu bile ništa inteligentnije od onih koje se nalaze iza mikrovalne pećnice u kuhinji. Spletkar je suspendiran i odbačen na najbliži planet prije nego što se brod vratio kući.'*/,
        /*'Obećavajući signali vodili su Istraživački brod do */'tajanstvene zlatne kugle koja je sama plutala u dubinama svemira'/* . Unatoč svim naporima međugalaktičkih izaslanika na brodu, nisu uspjeli pronaći ulaz ili uspostaviti bilo kakav kontakt s čudnim objektom prije nego što je iznenada odletio.'*/,
        /*'Na neistraženom planetu, istraživački brod otkrio je cvjetni sustav koji je bio daleko inteligentniji nego što se na prvu činilo. Međutim, kada ga je posada pokušala istražiti, pojavili su se */'čudni uniformirani roboti čuvari koji su ih upozorili'/* da su biljke privatno vlasništvo. Zanemarujući potencijalne poteškoće vezane uz kršenje međugalaktičkih zakona, istraživači su pokazali odlučnost i izvukli nešto uzoraka tijekom tajne operacije pod okriljem tame, prije nego što su brzo krenuli nazad u orbitu. Nažalost, operacija je očito bila previše prikrivena za hrpu znanstvenika, tako da su na brodu otkrili kako su njihovi rizično nabavljeni uzorci ništa drugo nego obične kućne biljke.'*/,
        /*'U potrazi za izvanzemaljskom inteligencijom, istraživački brod proveo je mjesece besciljno pretražujući galaksiju, kada su konačno */'otkrili vanzemaljski ekvivalent paramecija'/* ! Nije baš odgovaralo kriterijima inteligentnog života, ali nakon toliko monotonih mjeseci potrage, posada je odlučila ovo otkriće čak i neinteligentnog života smatrati uspješnim i vratila se kući bez ikakvih značajnijih vijesti.'*/,
        /*'Istraživački brod pratio je vrlo obećavajuće signale, */'međutim izgubili su se u kozmičkoj magli'/* . Nastavili su svoju potragu još neko vrijeme, međutim nisu uspjeli pronaći nove oblike života.'*/,
        /*'Nakon intenzivne potrage, posada istraživačkog broda */'otkrila je luminiscentnu vrstu divovske amebe'/* ! Nažalost, ti jednostanični organizmi imali su problema s prolaskom kroz standardne testove inteligencije. S obzirom na to koliko malo pozornosti istraživači posvećuju amebama, nije iznenađenje da se ovo otkriće također smatralo beznačajnim.'*/,
        /*'Hipnotička magla začarala je cijelu posadu Istraživačkog broda. Čini se da čudne boje i dizajn nekako ometaju ljudski mozak, što je značilo da se posada umjesto traženja izvanzemaljskog života bavila odgovorom na pitanje `*/'Jedu li vanzemaljci zapravo zelene hot-dogove'/* ?` Nepotrebno je reći da nisu pronašli nikakve nove oblike života.'*/,
        /*'Dok je tragao za izvanzemaljskim životom, Istraživački brod završio je u */'kozmičkom vrtlogu koji je ozbiljno oštetio vanjski trup'/* . Posada i brod spašeni su riskantnim manevrom, ali morali su odustati od istraživanja i vratiti se praznih ruku.'*/,
        /*'Istraživački brod je naišao na staru i */'napuštenu svemirsku stanicu na kojoj su nekada bile neke do sada nepoznate vrste'/* . Međutim, nakon intenzivnijeg proučavanja, ubrzo je postalo jasno da je postaja bila samo razrađena prevara izumrlog oblika života. Posada je uništila podrugljive poruke, ali nije uspjela otkriti ništa drugo.'*/,
        /*'Posada je naišla na visokotehnološku */'istraživačku stanicu koju pokreće umjetna inteligencija na usamljenom'/* i divljem planetu. Nažalost, vrata stanice bila su zaštićena lozinkom, a umjetna inteligencija odbila je suradnju. Posada je danima pokušavala dešifrirati lozinku, a zalihe su se počele smanjivati, a tada je jedan od neupadljivih članova posade naletio na kombinaciju i provalio šifru. Nažalost, postaja se pokazala kao razočaranje, a umjetna inteligencija nije bila ništa više od razrađenog sustava za upravljanje domom. Posada se nakon toga odlučila vratiti doma.'*/,
        /*'Tehnička pogreška u navigacijskom modulu dovela je */'Istraživački brod opasno blizu horizonta crne rupe'/* . Posada se uspjela okrenuti na vrijeme, ali je na kraju ispraznila zalihe goriva i morala prekinuti potragu za novim oblicima života bez uspjeha.'*/,
        /*'Istraživački brod je s uzbuđenjem izvijestio */'da su naišli na identičan brod iz paralelnog svemira'/* . Posada iz te dimenzije čak je imala i ista imena. No, sličnosti su tu prestale: na dočeku su gosti bili toliko bezobrazni da ih je ekipa ubrzo izbacila iz našeg svemira. Razočarana, ali istodobno i s olakšanjem, posada se vratila kući.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*LOCA: hr 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
        /*'Posada istraživačkog broda */'uspješno je uspostavila kontakt s dosad nepoznatom izvanzemaljskom vrstom'/* . Na prvu su djelovali dobronamjerno. Međutim, izvještaji našeg izaslanika i posade postajali su sve euforičniji, zbog čega moramo pretpostaviti da su bili podvrgnuti nekoj vrsti hipnoze. Zadnje izvješće koje smo dobili bio je radosni navještaj u ime cijele posade da bi radije ostali s tim prijateljskim vanzemaljcima. Brod i njegova posada nakon toga su nestali bez traga.'*/,
        /*'U potrazi za inteligentnim oblicima života, brod se zaustavio na dosad neistraženom mjesecu. Odnosno, još nikada do sada nije bilo izvješća o tom mjesecu. Ubrzo je postalo i jasno zbog čega. Posada je uspjela poslati signal za pomoć, ali tada je već bilo prekasno. Probuđeni dolaskom broda, */'ogromni magma crvi proždrijeli su brod i njegovu posadu'/* u roku nekoliko minuta.'*/,
        /*'Istraživački brod uspio je ući u trag inteligentnoj vanzemaljskoj vrsti, */'ali ispalo je da su neprijateljski raspoloženi'/* . Sudeći po posljednjem signalu koji je poslala posada, čini se da su ih vanzemaljci odveli kao zarobljenike. Svaki naknadni pokušaj lociranja broda i posade je nažalost propao.'*/,
        /*'Istraživački brod se zaustavio na nepoznatom planetu tokom svog putovanju kako bi se opskrbio zalihama. Planet je bio obavijen čudnom maglom, koju je */'posada brzo uspjela identificirati kao plin za spavanje'/* . No, nakon daljnje inspekcije, ubrzo je postalo očito da je plin bio toliko jak da se ni brod ni njegova posada nisu uspjeli spasiti.'*/,
        /*'Posada ovog istraživačkog broda već je stekla reputaciju pomalo maveričke ekipe, hrabre do pomalo nerazumne razine, zbog čega je izgledala kao savršeni izbor za ovu misiju. Možda su mislili da jednostavno mogu */'proletjeti direktno kroz polje asteroida'/* ? Nažalost, bit će teško doći do odgovora s olupine njihovog broda.'*/,
        /*'Čini se da je istraživački brod */'izgubljen u dosad nepoznatoj singularnosti'/*. Od tada nismo primili znakove života od posade.'*/,
        /*'Istraživačka flota uletjela je u */'zasjedu koju je postavila zlonamjerna vanzemaljska vrsta'/* . Potpuno su uništili istraživački brod prije nego što je prvi kontakt uopće mogao biti uspostavljen.'*/,
        /*LOCA: hr 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*'Brodski navigator mora da je bio toliko koncentriran na praćenje čudnog signala da */'nije zamjetio kako se nalaze u blizini crne rupe'/* . Brod je bio preblizu njenom gravitacijskom polju, i unatoč svim naporima posade, nisu mogli učiniti ništa kako bi izbjegli uvlačenje u rupu. Kako bi se izbjeglo više ovakvih nepotrebnih gubitaka, izvješće predlaže da se ubuduće kao standard u brodove integriraju automatski alarmi za crne rupe.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /na koordinatama .+ te je dodan u izbornik Oblika života/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /unaprijediti naše znanje o njima za (?<xp>\d+) XP/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*LOCA: hr 'The Exploration Ship has found some artefacts */'but cannot recover them as your storage is full',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'Istraživački Brod je */'pronašao manju količinu artefakata',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Istraživački Brod je */'pronašao veću količinu artefakata',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*Istraživački Brod je */'pronašao ogromnu riznicu artefakata',
        },
        numberOfArtifacts: /Artefakata pronađeno: (?<artifacts>\d+)/i,
    },
};