import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const hu: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*TODO: hu 'Zu Beginn der Erkundung konnten einige */'vielversprechende Koordinaten aus einer geheimnisvollen Nachricht'/* entschlüsselt werden. Als das Erkundungsschiff jedoch den angegebenen Sektor erreichte, fand die Crew nur noch das riesige Trümmerfeld eines bewaffneten Konflikts vor. Die Suche nach Überlebenden blieb erfolglos.'*/,
        /*TODO: hu 'Ein */'magnetisches Asteroidenfeld störte ungünstigerweise die Scanner'/*. Was wie ein vielversprechendes Signal intelligenten außerirdischen Lebens aussah, war nur eine Störung der Messinstrumente und es konnte keine neue Lebensform gefunden werden.'*/,
        /*TODO: hu 'Gerade als das Erkundungsschiff einen vielversprechenden Funkspruch auffangen konnte, */'kam es zu einem Totalausfall sämtlicher Kommunikationssysteme'/*. Unter diesen Umständen war nicht nur jede Kontaktaufnahme mit eventuellen intelligenten Lebensformen ausgeschlossen, ein Fortführen der Mission wäre auch gefährlich gewesen. Deshalb kehrte die Crew enttäuscht, aber unversehrt zurück.'*/,
        /*TODO: hu 'In einem noch größtenteils unerforschten Planetensystem */'wurde ein kosmischer Nebel mit Bewusstsein entdeckt'/* ! Die intergalaktischen Botschafter gerieten in helle Aufregung, weshalb unter großer medialer Aufmerksamkeit eine Sonde entsandt wurde. Beim Kommunikationsversuch mit dem Nebel stellte sich aber schnell heraus, dass seine Intelligenz kaum über der von einfachen Insekten lag. Die Aufregung schwand und es wurde beschlossen, einen Mantel des Schweigens über die ganze Aktion zu breiten.'*/,
        /*'Új életformák után kutatva a Kutatóhajó titokzatos jeleket követett, */'amelyek egy ismeretlen bolygó túloldaláról érkeztek'/* . A fedélzeten lévő intergalaktikus küldöttek már előkészítették az üdvözlőcsomagot és aktiválták a fordítókomputert, de kiderült, hogy a jel egy hajóroncsról érkezett. A hajó egyértelműen földönkívüli eredetű, de sajnos nyoma sem volt a legénységnek. Ez azt jelenti, hogy nem találtunk új életformát.'*/,
        /*'A Kutatóhajó már egy ideje úton volt, amikor kiderült, */'végzetes hiba csúszott a letapogató szoftverbe'/* . Ez sajnos azt jelenti, hogy nem lehetett új életformát találni.'*/,
        /*'Intergalaktikus küldötteink meglátogattak egy bolygót, */'ahol egy rendkívül tiszta, rovarszerű faj élt, feltételezve'/* , hogy intelligensek lehetnek, de csalódniuk kellett abban, amit találtak. Miután végignézték, ahogy a hajó hulladékpréselőjének tartalmát majszolják, úgy döntöttek, visszaviszik őket a bolygójukra, annak ellenére, hogy a legénység néhány tagja azt javasolta, tartsanak egy párat a fedélzeten.'*/,
        /*TODO: hu 'Vollkommen begeistert fanden die Forscher des Erkundungsschiffes */'ein neuronales Netzwerk mitten in einem Asteroidenfeld'/*. Die Enttäuschung war groß, als sich herausstellte, dass es sich lediglich um ein Cluster verfangener Nachrichten mit jahrhundertealten Sportergebnissen handelte, die das Eigenleben eines schlecht informierten Stammtisches entwickelt hatten. Die Crew kehrte niedergeschlagen und ohne signifikante Ergebnisse zurück.'*/,
        /*'A kutatóhajó legénysége el volt ragadtatva, amikor a */'gombaspórákon végzett vizsgálatok eredményei arra utaltak'/* , intelligens életet találtak. Sajnos kiderült, valami tréfamester manipulálta a teszteredményeket, csak hogy kínos helyzetbe hozzon egy rivális kutatót. A spórák valójában nem voltak intelligensebbek, mint azok, amelyeket a konyhában a mikrohullámú sütő háta mögött találtak. A bajkeverőt felfüggesztették és kitették a legközelebbi bolygón, mielőtt a hajó hazatért volna.'*/,
        /*TODO: hu 'Vielversprechende Signale führten das */'Erkundungsschiff zu einer mysteriösen goldenen Sphäre'/*, die einsam in den Tiefen des Weltalls schwebte. Trotz aller Bemühungen der intergalaktischen Botschafter an Bord konnte weder ein Eingang gefunden noch irgendwie Kontakt zu dem merkwürdigen Objekt hergestellt werden, bevor es sich mit einem Sprung davonmachte.'*/,
        /*'Egy */'feltáratlan bolygón a kutatóhajó felfedezett egy növényrendszert'/* , amely sokkal intelligensebb volt, mint amilyennek elsőre tűnt. Amikor azonban a legénység megpróbált vizsgálódni, furcsa egyenruhás őrrobotok jelentek meg, és figyelmeztették őket, hogy a növények magántulajdonban vannak. Figyelmen kívül hagyva az intergalaktikus birtokháborítási törvények megszegésének lehetséges következményeit, a kutatók kitartottak, és a sötétség leple alatt egy titkos művelet során mintát vettek, majd gyorsan pályára álltak. Sajnos a művelet egy kicsit TÚLSÁGOSAN IS titkos volt egy csapat nagyokos számára, és a hajón derült ki, hogy a kockázatosan megszerzett minták nem mások, mint közönséges szobanövények.'*/,
        /*'A földönkívüli intelligencia után kutatva a kutatóhajó már hónapok óta eredménytelenül, céltalanul járta a galaxist, */'amikor végre felfedezték a papucsállatkák idegen megfelelőjét'/* ! Ugyan nem igazán felelt meg az intelligens élet kritériumainak, de a legénység annyi monoton hónapnyi keresés után úgy döntött, hogy ezt a mégoly értelmetlen élet felfedezését is sikernek tekinti, és minden említésre méltó hír nélkül tért haza.'*/,
        /*TODO: hu 'Die vielversprechenden Signale, denen das Erkundungsschiff folgte, */'verloren sich leider in einem kosmischen Nebel'/*. Die Suche wurde noch eine Weile fortgesetzt, aber es konnten keine neuen Lebensformen entdeckt werden.'*/,
        /*'A kutatóhajó legénysége intenzív kutatás után */'felfedezte az óriás amőbák egy fluoreszkáló faját'/* ! Sajnos az egysejtű organizmusoknak akadt némi problémájuk az általános intelligenciateszten való megfeleléssel. Tekintettel arra, hogy a kutatók milyen kevés figyelmet szentelnek az amőbáknak, nem meglepő módon ezt a felfedezést is hasonlóan jelentéktelennek minősítették.'*/,
        /*'Hipnotikus köd vette körül a Kutatóhajó teljes legénységét. Úgy tűnik, a furcsa színek és minták valahogy megzavarják az emberi agyat, ami azt jelentette, ahelyett, hogy földönkívüli élet után kutattak volna, a legénység inkább azzal foglalkozott, hogy megválaszolja a kérdést: "*/'Vajon az idegenek tényleg esznek zöld hot dogot'/* ?”. Mondanunk sem kell, nem találtak új életformát.'*/,
        /*'A földön kívüli élet után kutatva a */'Kutatóhajó egy kozmikus örvénybe került'/* , amely súlyosan megrongálta a külső burkolatot. A legénység és a hajó megmenekült egy kockázatos repülési manőver által, de fel kellett adniuk a kutatást, és üres kézzel kellett visszatérniük.'*/,
        /*TODO: hu 'Das Erkundungsschiff stieß auf eine */'alte verlassene Raumstation, die von bisher unbekannten Lebewesen'/* bewohnt wurde. Nach eingehender Untersuchung musste man allerdings feststellen, dass es sich um den ausgeklügelten Scherz einer bereits ausgestorbenen Lebensform handelte. Die Crew zerstörte die hämischen Botschaften, konnte ansonsten aber nichts entdecken.'*/,
        /*TODO: hu 'Auf einem wilden Planeten */'entdeckte die Crew eine hochmoderne Forschungsstation'/*, die von einer künstlichen Intelligenz gesteuert und bewacht wurde. Die Tür zur Station war allerdings durch ein Passwort geschützt und die KI verweigerte die Kommunikation. Nachdem nach tagelangen Ratespielen die Vorräte knapp wurden, gelang es einem bisher eher unscheinbaren Mitglied der Crew, das Passworträtsel zu entschlüsseln. Im Inneren der Anlage stellte sich aber leider heraus, dass die KI nur ein elaboriertes Home-Management-System war und die Crew machte sich enttäuscht auf den Heimweg.'*/,
        /*'A navigációs modul műszaki hibája miatt a */'kutatóhajó veszélyesen közel került egy fekete lyuk eseményhorizontjához'/* . A legénység még időben vissza tudott fordulni, de az üzemanyagkészletük végül kimerült, így sikertelenül meg kellett szakítaniuk az új életformák keresését.'*/,
        /*TODO: hu 'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*TODO: hu 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
        /*TODO: hu 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*TODO: hu 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /*'A kutatóhajónak sikerült egy */'intelligens idegen faj nyomára bukkannia, de kiderült'/* , hogy ellenségesek. A legénység által küldött utolsó jelek alapján úgy tűnik, hogy az idegenek foglyul ejtették őket. Minden további kísérlet a hajó és legénysége felkutatására kudarcot vallott.'*/,
        /*TODO: hu 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*TODO: hu 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*TODO: hu 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*TODO: hu 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*TODO: hu 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*TODO: hu 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /.+ lett felfedezve a .+ koordinátán és hozzá lett adva az Életformák menühöz/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Követeink azonban (?<xp>\d+) XP-vel bővíthették a róluk gyűjtött ismereteinket/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*'Das Erkundungsschiff hat zwar ein paar Artefakte gefunden, */'konnte sie aber nicht mitnehmen, da deine Lager voll sind',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'A Kutatóhajó */'kis mennyiségű leletet talált',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Das Erkundungsschiff hat */'eine große Menge an Artefakten gefunden',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*'Das Erkundungsschiff hat */'eine riesige Sammlung von Artefakten gefunden',
        },
        numberOfArtifacts: /Talált leletek: (?<artifacts>\d+)/i,
    },
};