import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const it: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'All`inizio dell`esplorazione, è stato possibile decifrare alcune */'coordinate promettenti di un misterioso messaggio'/*. Tuttavia, quando la Nave da ricognizione ha raggiunto il settore indicato, l`equipaggio ha trovato solo un vasto campo di detriti, ciò che rimaneva di un conflitto armato. La ricerca dei sopravvissuti non ha avuto successo.'*/,
        /*'Il */'campo magnetico di un asteroide ha interferito'/* sfavorevolmente con gli strumenti di scansione. Quello che era sembrato un segnale di vita extraterrestre intelligente era solo un difetto negli strumenti di misurazione. Non è stata trovata alcuna forma di vita sconosciuta.'*/,
        /*'Proprio quando la Nave da ricognizione ha captato un promettente messaggio radio, */'tutti i sistemi di comunicazione sono andati in tilt'/*. Date le circostanze, non solo si è dovuto rinunciare al contatto con una forma di vita intelligente, ma sarebbe stato anche pericoloso continuare la missione. Quindi l`equipaggio è tornato deluso ma illeso.'*/,
        /*In un sistema planetario per lo più inesplorato è stata scoperta una */'nebulosa cosmica dotata di coscienza'/* ! Gli ambasciatori intergalattici hanno reagito con grande entusiasmo. Una sonda è stata inviata immediatamente in ricognizione, suscitando grande attenzione da parte dei media. Quando si è cercato di comunicare con la nebbia, tuttavia, è stato subito evidente che la sua intelligenza era appena superiore a quella dei semplici insetti. L`eccitazione si è placata subito e si è deciso di stendere un velo pietoso sull`intera operazione.'*/,
        /*'Alla ricerca di nuove forme di vita, la Nave da ricognizione ha seguito alcuni misteriosi segnali che sembravano provenire */'dalla porzione posteriore di un pianeta sconosciuto'/*. Gli ambasciatori intergalattici a bordo avevano già preparato dei doni e attivato il computer di traduzione, ma il segnale si è rivelato provenire da un relitto. La nave era chiaramente di origine extraterrestre, ma purtroppo non c`er traccia dei piloti. Non è stato possibile individuare alcuna nuova forma di vita.'*/,
        /*'La Nave da ricognizione era in viaggio già da un po` di tempo quando si è scoperto che */'un bug critico si era insinuato nel software'/* di scansione. Non è stato possibile individuare alcuna nuova forma di vita.'*/,
        /*'Sfortunatamente, le specie aliene insettoidi, che inizialmente i nostri */'ambasciatori intergalattici avevano ritenuto intelligenti'/*, si sono rivelate piuttosto semplici. L`eccezionale pulizia del loro pianeta non ne indicava l`evoluzione. Di conseguenza, dopo aver mangiato il contenuto del compattatore di rifiuti della nave, gli insettoidi sono stati rilasciati sul loro pianeta. Questo nonostante il voto dell`equipaggio di conservarne alcuni esemplari.'*/,
        /*'I ricercatori della Nave da ricognizione erano stati entusiasti di trovare una rete */'neurale nel mezzo di un campo di asteroidi'/*. La delusione è stata grande quando si è scoperto che si trattava di inutili notizie sportive secolari, frutto di discussioni male informate di qualche cliente di un bar. L`equipaggio è tornato sconsolato e senza risultati degni di nota.'*/,
        /*TODO: it 'Die Crew des Erkundungsschiffes war hellauf begeistert, als */'Untersuchungen von Schimmelsporen intelligentes Leben versprachen'/*. Leider stellte sich heraus, dass ein Witzbold die Forschungsergebnisse manipuliert hatte, um einen rivalisierenden Forscher bloßzustellen. Die untersuchten Sporen waren in Wahrheit kein bisschen intelligenter als der durchschnittliche Schimmelpilz in der Bordküche. Der Unruhestifter wurde auf den nächstbesten Planeten beurlaubt und das Schiff kehrte ergebnislos zurück.'*/,
        /*'Alcuni segnali promettenti hanno condotto la Nave da ricognizione in una */'misteriosa sfera dorata che fluttuava solitaria'/* nelle profondità dello spazio. Nonostante gli sforzi degli ambasciatori intergalattici a bordo, non è stato possibile trovare un ingresso o stabilire un contatto con lo strano oggetto, che è schizzato via rapidamente.'*/,
        /*'La Nave da ricognizione ha scoperto un sistema vegetale dall`aria intelligente su un pianeta inesplorato. Quando l`equipaggio è andato a indagare, sono */'apparsi dei misteriosi robot di guardia'/* in uniforme, che hanno sottolineato che si trattava di proprietà privata. Nonostante la minaccia di azioni legali intergalattiche, i ricercatori non si sono arresi e sono riusciti a prelevare dei campioni di nascosto, prima di fuggire. Apparentemente l`atmosfera doveva essere molto buia e nebbiosa, perché i reperti che erano stati prelevati si sono poi rivelati normali piante da interni.'*/,
        /*'La Nave da ricognizione ha vagato per la galassia per mesi, alla ricerca di vita intelligente extraterrestre. A un certo punto, l`equipaggio ha */'trovato un parente extraterrestre del paramecio'/* ! Questa forma di vita non era intelligente, ma a causa del lungo viaggio e dei nervi a pezzi, l`equipaggio ha deciso di accontentarsi di una vita poco intelligente e di tornare senza alcuna scoperta significativa.'*/,
        /*'Sfortunatamente, i promettenti segnali che la Nave da ricognizione stava seguendo */'si erano persi in una nebbia cosmica'/* . La ricerca è proseguita per qualche tempo, ma non è stato possibile individuare alcuna nuova forma di vita.'*/,
        /*TODO: it 'Nach intensiver Suche fand die Crew des */'Erkundungsschiffes eine lumineszente Riesenamöbenart'/* ! Leider hatten die Amöben Schwierigkeiten bei der Bearbeitung des standardisierten Tests zur Identifikation außerirdischer Intelligenz. Deshalb und weil in Forscherkreisen Amöben leider immer noch verkannt werden, wurde diese Entdeckung als nicht relevant eingestuft.'*/,
        /*'Una strana nebbia ha ipnotizzato l`intero equipaggio della Nave da ricognizione. I colori e i motivi alieni sembravano interferire con il corretto funzionamento del cervello umano. Invece di cercare segni di vita extraterrestre, l`equipaggio si è concentrato sul cercare la risposta a domande come: "*/'Gli alieni mangiano pizze volanti'/*?". È inutile dire che non sono state trovate forme di vita sconosciute.'*/,
        /*'Durante la ricerca di vita extraterrestre, la Nave da ricognizione è rimasta */'intrappolata in un vortice cosmico che ha danneggiato'/* gravemente lo scafo esterno. L`equipaggio e la nave si sono salvati grazie a una rischiosa manovra di volo, ma hanno dovuto rinunciare alla ricognizione e tornare senza alcun risultato.'*/,
        /*'La Nave da ricognizione ha */'incontrato una vecchia stazione spaziale abbandonata'/*, abitata da creature precedentemente sconosciute. A un esame più attento, tuttavia, si è scoperto che si trattava di un`elaborata bufala di una forma di vita già estinta. L`equipaggio ha distrutto i messaggi dannosi, ma non è riuscito a trovare nient`altro.'*/,
        /*'Su un pianeta selvaggio, l`equipaggio ha scoperto una stazione di ricerca all`avanguardia, */'controllata e sorvegliata da un`IA'/*. Tuttavia, la porta della stazione era protetta da una password e l`IA si rifiutava di comunicare. Dopo giorni di indovinelli e scorte in esaurimento, uno schivo membro dell`equipaggio è riuscito a decifrare il rompicapo. Purtroppo, all`interno della struttura, si è scoperto che l`IA era solo un elaborato sistema di gestione domestica e l`equipaggio è tornato a casa deluso.'*/,
        /*'A causa di un errore tecnico nel modulo di navigazione, la Nave da ricognizione si è */'avvicinata pericolosamente a un buco nero'/*. L`equipaggio è fortunatamente riuscito a invertire la rotta, ma ha esaurito la scorta di carburante e ha dovuto abbandonare la ricerca di nuove forme di vita.'*/,
        /*'La Nave da ricognizione ha riferito con entusiasmo che l`equipaggio aveva incontrato una Nave da */'ricognizione identica proveniente da un universo speculare'/*. Sorprendentemente, l`equipaggio dell`altra dimensione condivideva persino gli stessi nomi. Ma le somiglianze si limitavano a questo. Gli ospiti dell`altro mondo si sono comportati in modo così sgarbato alla festa di benvenuto che è stato necessario espellerli dall`universo. Deluso, ma anche in qualche modo sollevato, l`equipaggio della nostra Nave da ricognizione è tornato a casa.'*/,
        /*TODO: it 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*TODO: it 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*'Durante la ricerca di forme di vita intelligenti, la nave ha fatto scalo su una luna precedentemente inesplorata. È stato subito chiaro il motivo per cui nessuno avesse parlato di essa in precedenza. L`equipaggio è riuscito a inviare una richiesta di aiuto, ma sfortunatamente era troppo tardi. */'Dei giganteschi vermi magma'/*, messi in subbuglio dalla manovra di atterraggio, hanno divorato la nave e l`intero equipaggio in pochi minuti.'*/,
        /*'Sebbene la Nave da ricognizione sia riuscita a rintracciare una specie aliena intelligente, */'questa si è rivelata ostile'/*. L`ultimo messaggio radio dell`equipaggio indica che i suoi membri siano stati fatti prigionieri dagli alieni. Qualsiasi tentativo di individuare la posizione della nave e del suo equipaggio purtroppo non ha avuto successo.'*/,
        /*'La Nave da ricognizione si è fermata su un pianeta inesplorato per fare scorta di rifornimenti. Il pianeta era avvolto da una misteriosa nebulosa che l`equipaggio */'ha identificato come un gas soporifero'/* . A un`indagine più approfondita, questo si è rivelato così forte che non c`è stato modo di mettersi in salvo.'*/,
        /*TODO: it 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*TODO: it 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*TODO: it 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*TODO: it 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*TODO: it 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /Questa è stata aggiunta alla Gestione Forme di vita/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /loro guadagnando la seguente esperienza: (?<xp>\d+)/i,
};