import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const it: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'All`inizio dell`esplorazione, è stato possibile decifrare alcune */'coordinate promettenti di un misterioso messaggio'/*. Tuttavia, quando la Nave da ricognizione ha raggiunto il settore indicato, l`equipaggio ha trovato solo un vasto campo di detriti, ciò che rimaneva di un conflitto armato. La ricerca dei sopravvissuti non ha avuto successo.'*/,
        /*TODO: it 'Ein */'magnetisches Asteroidenfeld störte ungünstigerweise die Scanner'/*. Was wie ein vielversprechendes Signal intelligenten außerirdischen Lebens aussah, war nur eine Störung der Messinstrumente und es konnte keine neue Lebensform gefunden werden.'*/,
        /*'Proprio quando la Nave da ricognizione ha captato un promettente messaggio radio, */'tutti i sistemi di comunicazione sono andati in tilt'/*. Date le circostanze, non solo si è dovuto rinunciare al contatto con una forma di vita intelligente, ma sarebbe stato anche pericoloso continuare la missione. Quindi l`equipaggio è tornato deluso ma illeso.'*/,
        /*TODO: it 'In einem noch größtenteils unerforschten Planetensystem */'wurde ein kosmischer Nebel mit Bewusstsein entdeckt'/*! Die intergalaktischen Botschafter gerieten in helle Aufregung, weshalb unter großer medialer Aufmerksamkeit eine Sonde entsandt wurde. Beim Kommunikationsversuch mit dem Nebel stellte sich aber schnell heraus, dass seine Intelligenz kaum über der von einfachen Insekten lag. Die Aufregung schwand und es wurde beschlossen, einen Mantel des Schweigens über die ganze Aktion zu breiten.'*/,
        /*TODO: it 'Bei der Suche nach neuen Lebensformen folgte das Erkundungsschiff einigen mysteriösen Signalen, die */'von der Rückseite eines unbekannten Planeten zu stammen'/* schienen. Die intergalaktischen Botschafter an Bord hatten schon das Begrüßungspaket geholt und den Übersetzungscomputer aktiviert, doch es stellte sich heraus, dass das Signal von einem Schiffswrack stammt. Das Schiff ist eindeutig außerirdischer Herkunft, aber von den Piloten fehlt leider jede Spur. So konnte keine neue Lebensform entdeckt werden.'*/,
        /*'La Nave da ricognizione era in viaggio già da un po` di tempo quando si è scoperto che */'un bug critico si era insinuato nel software'/* di scansione. Non è stato possibile individuare alcuna nuova forma di vita.'*/,
        /*TODO: it 'Leider erwies sich die insektoide Alienspezies, die unsere */'intergalaktischen Botschafter wegen der außerordentlichen Sauberkeit'/* ihres Heimatplaneten zunächst für intelligent hielten, doch als eher einfach gestrickt. Nachdem sie den Inhalt der Bord-Müllpresse gefressen hatten, wurden sie deshalb wieder auf ihrem Planeten ausgesetzt, trotz eines Votums der Crew, doch ein paar Exemplare zu behalten.'*/,
        /*TODO: it 'Vollkommen begeistert fanden die Forscher des Erkundungsschiffes */'ein neuronales Netzwerk mitten in einem Asteroidenfeld'/*. Die Enttäuschung war groß, als sich herausstellte, dass es sich lediglich um ein Cluster verfangener Nachrichten mit jahrhundertealten Sportergebnissen handelte, die das Eigenleben eines schlecht informierten Stammtisches entwickelt hatten. Die Crew kehrte niedergeschlagen und ohne signifikante Ergebnisse zurück.'*/,
        /*TODO: it 'Die Crew des Erkundungsschiffes war hellauf begeistert, als */'Untersuchungen von Schimmelsporen intelligentes Leben versprachen'/*. Leider stellte sich heraus, dass ein Witzbold die Forschungsergebnisse manipuliert hatte, um einen rivalisierenden Forscher bloßzustellen. Die untersuchten Sporen waren in Wahrheit kein bisschen intelligenter als der durchschnittliche Schimmelpilz in der Bordküche. Der Unruhestifter wurde auf den nächstbesten Planeten beurlaubt und das Schiff kehrte ergebnislos zurück.'*/,
        /*'Alcuni segnali promettenti hanno condotto la Nave da ricognizione in una */'misteriosa sfera dorata che fluttuava solitaria'/* nelle profondità dello spazio. Nonostante gli sforzi degli ambasciatori intergalattici a bordo, non è stato possibile trovare un ingresso o stabilire un contatto con lo strano oggetto, che è schizzato via rapidamente.'*/,
        /*'La Nave da ricognizione ha scoperto un sistema vegetale dall`aria intelligente su un pianeta inesplorato. Quando l`equipaggio è andato a indagare, sono */'apparsi dei misteriosi robot di guardia'/* in uniforme, che hanno sottolineato che si trattava di proprietà privata. Nonostante la minaccia di azioni legali intergalattiche, i ricercatori non si sono arresi e sono riusciti a prelevare dei campioni di nascosto, prima di fuggire. Apparentemente l`atmosfera doveva essere molto buia e nebbiosa, perché i reperti che erano stati prelevati si sono poi rivelati normali piante da interni.'*/,
        /*TODO: it 'Bei der Suche nach außerirdischem intelligentem Leben irrte das Erkundungsschiff bereits seit Monaten durch die Galaxis, als sie */'endlich einen außerirdischen Verwandten des Pantoffeltierchens'/* fanden! Diese Lebensform war zwar nicht intelligent, aber aufgrund der langen Reise und blankliegender Nerven entschied die Crew, auch mit unintelligentem Leben vorlieb zu nehmen und ohne nennenswerte Funde zurückzukehren.'*/,
        /*TODO: it 'Die vielversprechenden Signale, denen das Erkundungsschiff folgte, */'verloren sich leider in einem kosmischen Nebel'/*. Die Suche wurde noch eine Weile fortgesetzt, aber es konnten keine neuen Lebensformen entdeckt werden.'*/,
        /*TODO: it 'Nach intensiver Suche fand die Crew des */'Erkundungsschiffes eine lumineszente Riesenamöbenart'/*! Leider hatten die Amöben Schwierigkeiten bei der Bearbeitung des standardisierten Tests zur Identifikation außerirdischer Intelligenz. Deshalb und weil in Forscherkreisen Amöben leider immer noch verkannt werden, wurde diese Entdeckung als nicht relevant eingestuft.'*/,
        /*'Una strana nebbia ha ipnotizzato l`intero equipaggio della Nave da ricognizione. I colori e i motivi alieni sembravano interferire con il corretto funzionamento del cervello umano. Invece di cercare segni di vita extraterrestre, l`equipaggio si è concentrato sul cercare la risposta a domande come: "*/'Gli alieni mangiano pizze volanti'/*?". È inutile dire che non sono state trovate forme di vita sconosciute.'*/,
        /*'Durante la ricerca di vita extraterrestre, la Nave da ricognizione è rimasta */'intrappolata in un vortice cosmico che ha danneggiato'/* gravemente lo scafo esterno. L`equipaggio e la nave si sono salvati grazie a una rischiosa manovra di volo, ma hanno dovuto rinunciare alla ricognizione e tornare senza alcun risultato.'*/,
        /*TODO: it 'Das Erkundungsschiff stieß auf eine */'alte verlassene Raumstation, die von bisher unbekannten Lebewesen'/* bewohnt wurde. Nach eingehender Untersuchung musste man allerdings feststellen, dass es sich um den ausgeklügelten Scherz einer bereits ausgestorbenen Lebensform handelte. Die Crew zerstörte die hämischen Botschaften, konnte ansonsten aber nichts entdecken.'*/,
        /*TODO: it 'Auf einem wilden Planeten */'entdeckte die Crew eine hochmoderne Forschungsstation'/*, die von einer künstlichen Intelligenz gesteuert und bewacht wurde. Die Tür zur Station war allerdings durch ein Passwort geschützt und die KI verweigerte die Kommunikation. Nachdem nach tagelangen Ratespielen die Vorräte knapp wurden, gelang es einem bisher eher unscheinbaren Mitglied der Crew, das Passworträtsel zu entschlüsseln. Im Inneren der Anlage stellte sich aber leider heraus, dass die KI nur ein elaboriertes Home-Management-System war und die Crew machte sich enttäuscht auf den Heimweg.'*/,
        /*TODO: it 'Das Erkundungsschiff kam durch einen technischen Fehler im */'Navigationsmodul dem Ereignishorizont eines schwarzen Lochs bedrohlich nahe'/*. Die Crew konnte gerade noch abdrehen, verbrauchte dabei jedoch ihren Treibstoffvorrat und musste daher die Suche nach neuen Lebensformen erfolglos abbrechen.'*/,
        /*TODO: it 'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
        /*TODO: it 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*TODO: it 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*TODO: it 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /*'Sebbene la Nave da ricognizione sia riuscita a rintracciare una specie aliena intelligente, */'questa si è rivelata ostile'/*. L`ultimo messaggio radio dell`equipaggio indica che i suoi membri siano stati fatti prigionieri dagli alieni. Qualsiasi tentativo di individuare la posizione della nave e del suo equipaggio purtroppo non ha avuto successo.'*/,
        /*TODO: it 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*TODO: it 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*TODO: it 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*TODO: it 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*TODO: it 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*TODO: it 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /*TODO: it *//Bei den Koordinaten .+ wurde die Lebensform .+ gefunden und der Lebensformverwaltung hinzugefügt/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /*TODO: it *//Dennoch konnten unsere Botschafter unser Wissen über sie um (?<xp>\d+) Erfahrung verbessern/i,
};