import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const nl: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Bij de start van hun verkenningsmissie konden ze enkele beloftevolle coördinaten ontcijferen afkomstig uit een mysterieus bericht. Maar wanneer het Verkenningsschip aankwam in de sector op deze coördinaten, vonden ze */'enkel een gigantisch puinveld dat achtergelaten was na een gevecht'/* . De zoektocht naar overlevenden was uiteindelijk vruchteloos.'*/,
        /*'Een */'magnetisch asteroïde veld verstoorde de scanners'/* . Wat leek op een beloftevol signaal van intelligent buitenaards leven was gewoon een verstoring van de meetinstrumenten en er konden geen nieuwe levensvormen gevonden worden.'*/,
        /*'Net op het ogenblik dat het Verkenningsschip een beloftevol signaal ontving gingen al hun communicatiesystemen plots uit. Door omstandigheden was het niet enkel */'onmogelijk om contact te maken met potentieel intelligente levensvormen'/* , maar zou het ook gevaarlijk zijn om de missie verder te zetten. De bemanning keerde teleurgesteld, maar ongedeerd terug naar huis.'*/,
        /*'Een */'nevel met enige vorm van bewustzijn werd ontdekt'/* in een grotere onontdekt deel van ons melkwegstelsel. Onze intergalactische afgezanten waren extatisch en er werd een groots mediacircus opgezet als de expeditie opgezet werd. Na communicatie met de nevel werd echter duidelijk dat zijn intelligentie vergelijkbaar was met die van een kakkerlak. De opwinding zwakte enorm af en er werd beslist om de hele operatie stilletjes te laten uitdoven.'*/,
        /*'Tijdens de zoektocht naar nieuwe levensvormen volgde het Verkenningsschip enkele */'mysterieuze signalen die vanaf de verste kant van een onbekende planeet'/* leken te komen. De intergalactische gezanten aan boord hadden reeds hun welkomspakket bovengehaald en vertaalcomputer geactiveerd, maar het signaal bleek te komen van een scheepswrak. Het schip is duidelijk van buitenaardse oorsprong, maar helaas was er geen teken van de bemanning. Dit betekent dat er geen nieuwe levensvorm ontdekt werd.'*/,
        /*'Het Verkenningsschip was al even onderweg toen we */'ontdekten dat een fatale bug in de scansoftware geslopen was'/* . Dit betekent helaas dat er geen nieuwe levensvormen ontdekt konden worden.'*/,
        /*'Onze intergalactische afgezanten */'bezochten een planeet met een extreem schone insectoïde soort'/* . Ze gingen ervanuit dat deze intelligent was, maar waren teleurgesteld door wat ze ontdekten. Nadat ze hen de inhoud van de afvalpers van het schip zagen oppeuzelen besloten ze hen terug te brengen naar hun thuisplaneet, ondanks het voorstel van enkele van de bemanningsleden om er enkele te houden.'*/,
        /*'De onderzoekers aan boord van het verkenningsschip waren */'extatisch om een neuraal netwerk te ontdekken'/* in het midden van een asteroïde veld. Daarom waren ze nog teleurgestelder toen ze ontdekten dat het niet meer was dan een heleboel onderschepte nieuwsrapportages van eeuwenoude sportresultaten, die een eigen leven was gaan leiden als een soort ruimtebankexpert. De bemanning keerde depressief terug zonder iets bijgeleerd te hebben buiten wie wat als laatste gewonnen had.'*/,
        /*'De bemanning can het verkenningsschip waren in de wolken toen resultaten van testen op */'schimmelsporen aangaven dat ze intelligent leven'/* ontdekt hadden. Helaas kwam aan het licht dat een grapjas de testresultaten had gemanipuleerd om zijn mede-onderzoeker in verlegenheid te brengen. De sporen waren niet intelligenter dan degene die je kan vinden aan de achterkant van de magnetron uit de kombuis. De grappenmaker werd geschorst en afgezet op de eerstvolgende planeet alvorens het schip huiswaarts keerde.'*/,
        /*'Hoopvolle signalen stuurden het Verkenningsschip naar een */'mysterieuze gouden bol die ronddreef in de dieptes'/* van de ruimte. Maar ondanks alle inspanningen van de intergalactische gezanten aan boord, waren ze niet in staat om een ingang te vinden of enige vorm van contact te maken met het vreemde object alvorens het plots wegsprong.'*/,
        /*'Op een onontdekte planeet kwam het verkenningsschip */'een bloemensysteem tegen dat veel intelligenter leek'/* dan het er op het eerste zicht uitzag. Wanneer de bemanning dit probeerde te onderzoeken verschenen er vreemde bewakingsrobots in uniform die hen waarschuwden dat de planten privé eigendom waren. De onderzoekers waren vastberaden en maakten enkele monsters buit gedurende een geheime nachtelijke operatie waarbij ze mogelijks intergalactisch wetten overtraden. Ze stegen daarna snel terug op. Helaas was de operatie een beetje te geheim voor een stelletje wetenschapsnerds en wanneer ze terug op het schip kwamen ontdekten ze dat de monsters die ze hadden verzameld niks meer waren dan gewone huisplanten.'*/,
        /*'Op hun zoektocht naar buitenaardse intelligentie had het verkenningsschip reeds maanden vruchteloos door de melkweg gevlogen toen ze */'eindelijk een buitenaards pantoffeldiertje tegenkwamen'/* ! Het komt niet echt in aanmerking als intelligent leven maar na enkele monotone maanden zoeken bestempelde de bemanning deze ontdekking van niet-intelligent leven zelfs als een succes en besloten ze huiswaarts te keren met het nieuws.'*/,
        /*'De zeer beloftevolle signalen die het Verkenningsschip */'opspoorde gingen helaas verloren in ruimteruis'/* . Ze bleven nog wat langer zoeken, maar konden helaas geen nieuwe levensvormen vinden.'*/,
        /*'Na een intense zoektocht ontdekte de bemanning van het verkenningsschip een */'lichtgevende soort gigantische amoeben'/* ! Helaas hadden deze eencellige organismen wat problemen om de standaard intelligentie test af te ronden. Rekening houdend met hoe weinig aandacht onderzoekers geven aan amouben is het verrassend dat deze ontdekking zelfs gerapporteerd werd.'*/,
        /*'Een hypnotiserend mist deed de volledige bemanning van het Verkenningsschip hallucineren. De vreemde kleuren en ontwerpen leken het menselijk brein aan te tasten, waardoor de bemanning in plaats van te zoeken naar buitenaards leven zich begonnen af te */'vragen of aliens groene hotdogs eten'/* ? Vanzelfsprekend vonden ze dan ook geen nieuwe levensvormen.'*/,
        /*'Tijdens hun zoektocht naar buitenaards leven raakte het Verkenningsschip */'verstrengeld in een kosmische draaikolk die de buitenste romp zwaar beschadigde'/* . De bemanning en het schip werden gered door een gevaarlijk vliegmanoeuvre, maar ze moesten hun verkenningsmissie opgeven en met lege handen terugkeren.'*/,
        /*'Het verkenningsschip kwam langs een oud, */'verlaten ruimtestation dat voordien bemand werd door een onbekende levensvorm'/* . Na een grondig onderzoek werd duidelijk dat het station enkel een uitgebreide hoax was van een uitgestorven levensvorm. De bemanning vernietigde de bespottelijke berichten maar konden niks anders ontdekken.'*/,
        /*'De bemanning ontdekte een */'high-tech AI-gestuurde onderzoeksbasis'/* op een eenzame en verlaten planeet. Helaas was de deur naar het station beschermt met een wachtwoord en wou de AI niet meewerken. De bemanning probeerde dagenlang het wachtwoord te kraken en hun voorraden begon te slinken wanneer plots één van de onopvallend bemanningsleden bij toeval de combinatie ontdekte en code kon kraken. Helaas bleek het station een teleurstelling en was de AI niet meer dan een geavanceerd huisbeheersysteem. De bemanning keerde terug naar huis.'*/,
        /*'Een technische fout in het navigatiesysteem van het Verkenningsschip */'bracht het gevaarlijk dichtbij een zwart gat'/* . De bemanning kon net op tijd rechtsomkeer maken waardoor het alle brandstofvoorziening opgebruikte en dus moesten ze hun zoektocht naar nieuwe levensvormen zonder succes staken.'*/,
        /*'Het verkenningsschip rapporteerde vol vreugde dat ze een */'identiek schip tegenkwamen van een parallel universum'/* . De bemanning van deze dimensie had zelfs dezelfde namen. Maar daar stopten de overeenkomsten: op het welkomstfeest waren de gasten zo saai dat de bemanning hen snel uit ons universum verbanden. Teleurgesteld, maar ook opgelucht, keerde de bemanning terug naar huis.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'De bemanning van het verkenningsschip werd verscheurd in een onderlinge */'strijd waarna er uiteindelijk muiterij uitbrak'/* . De gestrande bemanning werd gelocaliseerd en gered, maar de muiters hebben de controle overgenomen over het schip en zijn toegetreden tot een groep ruimtepiraten. Als resultaat van dit incident worden alle scheepsbemanningen nu verplicht om elk kwartaal een teambuildingsoefening te doen.'*/,
        /*'De bemanning can het verkenningsschip maakte */'succesvol contact met een onbekende alienras'/* . Op het eerste zicht leken ze goedaardig. Maar de rapporten van onze afgezant en de bemanning waren te euphorisch, hierdoor moeten we er vanuit gaan dat ze onderworpen werden aan een vorm van hypnose. Het laatste rapport dat we ontvingen was een vreugdevolle mededeling van de bemanning dat ze liever bij hun nieuwe alien-vrienden wouden blijven. Het schip en de bemanning gingen verloren zonder enig spoor na te laten.'*/,
        /*'In zijn zoektocht naar intelligente levensvormen stopte het schip op een nog onbekende maan. De maan werd nog nooit eerder gerapporteerd. Al snel werd duidelijk waarom. De bemanning kon nog een noodsignaal uitsturen, maar dit was al te laat. */'Gigantische magma wormen verslonden het schip'/* en zijn bemanning binnen enkele minuten nadat ze de komst van het schip ontdekten.'*/,
        /*'Het verkenningsschip kon een intelligente buitenaardse levensvorm opsporen maar ze bleken gewelddadig. Als we afgaan op het laatste signaal die we ontvingen van de bemanning */'lijkt het erop dat de aliens hen gevangen genomen hebben'/* . Elke poging om het schip en zijn bemanning op te sporen mislukte.'*/,
        /*'Het verkenningsschip stopte op een onbekende planeet om hun voorraden bij te vullen. De planeet werd omgeven door een vreemde mist en de */'bemanning kon dit snel identificeren als slaapgas'/* . Maar na verder onderzoek werd duidelijk dat het gas te sterk was en dat het schip en hun bemanning waren niet meer te redden.'*/,
        /*'De bemanning van dit verkenningsschip hadden reeds de reputatie als buitenbeentjes, zeer moedig, maar ook enorm roekeloos, daarom leken ze de perfecte match voor deze missie. Misschien dachten ze dat ze gewoon */'recht door het asteroïde veld konden vliegen'/* ? Helaas zal het moeilijk zijn om antwoorden te vinden uit hun scheepswrak.'*/,
        /*'Het lijkt erop dat het verkenningsschip */'verloren ging in een tot nu toe onbekende bijzonderheid'/* . Er is sindsdien geen teken meer van leven van de bemanning.'*/,
        /*'Het verkenningsschip vloog in een */'hinderlaag opgezet door een gevaarlijke aliensoort'/* . Het verkenningsschip werd verpulverd voordat er ook maar enige contact gelegd kon worden.'*/,
        /*'Het verkenningsschip kreeg enkele beloftevolle signalen. Maar nadat de bron van het */'signaal ontdekt werd, stopte het plots'/* . Zoekteams werden erop uitgestuurd maar konden de locatie van het schip niet traceren. Het moet verloren gegaan zijn in de leegte.'*/,
        /*'Het schip zijn navigator moet zeer geconcentreerd geweest zijn op het volgen van een vreemd signaal dat hij niet gezien heeft dat ze dichtbij een zwart gat vlogen. Het schip kwam te dicht bij de zwaartekrachtbron en ondanks de bemanning hun inspanningen, */'niks kon verkomen dat ze opgezogen werden'/* . Om verdere nodeloze verliezen te verkomen raadt het rapport aan om automatische alarmen voor zwarte gaten vanaf nu te integreren in de standaarduitrusting.'*/,
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /werd ontdekt op de coördinaten .+ en toegevoegd aan het Levensvormen menu./i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /onze kennis over hen vebeteren met (?<xp>\d+) XP/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*'Het Verkenningsschip heeft enkele artefacten */'gevonden maar kan deze niet verkrijgen omdat de opslag vol is',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*Het Verkenningsschip heeft een */'klein aantal artefacten gevonden', 
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Het Verkenningsschip heeft een */'grote hoeveelheid artefacten gevonden', 
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*'Het Verkenningsschip heeft een */'grote schat aan artefacten gevonden',
        },
        numberOfArtifacts: /Gevonden Artefacten: (?<artifacts>\d+)/i,
    }
};