import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const pl: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Na początku wyprawy udało im się */'odszyfrować z tajnej wiadomości kilka obiecujących współrzędnych'/* . Jednak gdy statek ekspedycyjny dotarł do wyznaczonego sektora, załoga znalazła tylko gigantyczne pole zniszczeń pozostałe po zakończonej bitwie. Nie odnaleziono tam żadnych ocalałych.'*/,
        'Magnetyczne pole asteroid zakłóciło pracę skanerów'/*. To, co wydawało się obiecującym sygnałem inteligentnej pozaziemskiej formy życia, było po prostu tylko małą usterką urządzeń pomiarowych, a nie nową formą życia.'*/,
        /*'W momencie przejęcia sygnału radiowego przez statek ekspedycyjny, */'doszło do awarii wszystkich systemów komunikacjach'/* . W tych okolicznościach nie tylko nie było możliwe nawiązanie kontaktu z inteligentną formą życia, ale także kontynuowanie misji mogłoby się okazać niebezpieczne. Wprawdzie załoga powróciła do domu rozczarowana, ale cała i zdrowa.'*/,
        /*'W dużej mierze niezbadanym jeszcze systemie */'planetarnym odkryto samoświadomą kosmiczną mgłę'/* ! Nasi międzygalaktyczni ambasadorzy byli tak podekscytowani, że przy dużym medialnym rozgłosie wysłali sondę badawczą. Gdy jednak próbowali za jej pomocą nawiązać kontakt ze świeżo odkrytym mgielnym bytem, okazało się, że jego inteligencja nie przewyższa intelektu plujki pospolitej. Ekscytacja znaleziskiem szybko wygasła, a pobłażliwe media zgodziły się przemilczeć to niefortunne wydarzenie.'*/,
        /*'W poszukiwaniu nowych form życia statek ekspedycyjny podążał za tajemniczymi sygnałami, */'które prawdopodobnie dochodziły z tyłu nieznanej planety'/* . Na pokładzie międzygalaktyczni posłańcy odebrali już pakiet powitalny oraz aktywowali komputer tłumaczący, okazało się jednak, że sygnał pochodził z wraku statku. Z całą pewnością statek jest obcego pochodzenia, ale po pilotach nie ma śladu. Nie odkryto więc żadnej nowej formy życia.'*/,
        /*'Statek ekspedycyjny był już od dłuższego czasu w drodze, gdy się okazało, że do */'oprogramowania skanującego wkradł się jakiś fatalny błąd'/* . I dlatego też nie można było odkryć żadnej nowej formy życia.'*/,
        /*'Insektoidalne istoty obce, które nasi */'międzygalaktyczni ambasadorzy z powodu niebywałego porządku na ich planecie uznali'/* za inteligentne formy życia, okazały się niestety dość prymitywne. Gdy w końcu pożarły całą zawartość pokładowych śmietników, wysadzono je ponownie na ich planecie, nie zważając na protesty załogi, która chciała zatrzymać tak pożytecznych współlokatorów.'*/,
        /*'Na samym środku pola asteroid zachwyceni naukowcy */'statku ekspedycyjnego znaleźli sieć neuronalną'/* . Tym większe było ich rozczarowanie, gdy się okazało, że jest to jedynie zbitek wiadomości sportowych sprzed stuleci, w dodatku o bardzo wątpliwej wiarygodności. Załoga powróciła do doku bez żadnych wyników i z miernymi nastrojami.'*/,
        /*'Wśród załogi statku ekspedycyjnego zapanowała radosna nadzieja, gdy */'badania zarodników pleśni wykazały poszlaki inteligentnego życia'/* . Nieco później okazało się jednak, że była to niecna manipulacja jakiegoś zgrywusa, który chciał skompromitować swojego kolegę po fachu. Analizowane zarodniki mogły poszczycić się w rzeczywistości inteligencją nie większą od przeciętnej pleśni rozprzestrzeniającej się po kuchni pokładowej. Sabotażystę eksperymentu wysadzono po prostu na pierwszej lepszej planecie, a statek powrócił bezowocnie do doku.'*/,
        /*'Obiecujące sygnały pokierowały statek */'ekspedycyjny do tajemniczej złotej sfery'/* , która samotnie unosiła się w głębiach kosmosu. Mimo wszelkich starań międzygalaktycznym posłańcom nie udało się odnaleźć wejście ani nawiązać kontaktu z dziwnym obiektem, zanim ten nagle odleciał.'*/,
        /*'Statek ekspedycyjny odkrył na nieznanej planecie system roślin, który wydawał się być nad wyraz inteligentny. Gdy załoga chciała go zbadać, */'została zatrzymana przez tajemnicze roboty w mundurach'/* , które zwróciły naukowcom uwagę, że jest to własność prywatna. Mimo gróźb międzygalaktycznych procesów sądowych członkowie naszej załogi ekstrahowali pod osłoną nocy próbki z tej rzekomo inteligentnej rośliny i niepostrzeżenie wrócili na pokład. W laboratorium okazało się jednak, że zebrane po ciemaku próbki pochodzą z najzwyklejszych roślin pokojowych.'*/,
        /*'W poszukiwaniu obcego inteligentnego życia statek ekspedycyjny kluczył już od wielu miesięcy bezowocnie po przepastnej galaktyce, gdy nagle jego załoga natrafiła na */'kosmicznego kuzyna naszego ziemskiego pantofelka'/* ! Ta forma życia do inteligentnych co prawda nie należała, ale członkowie załogi byli już tak zmęczeni tą długą podróżą, że zadowolili się i takim znaleziskiem i obrali kurs powrotny.'*/,
        /*'Mimo obiecujących sygnałów, za którymi podążał statek ekspedycyjny, */'rozwiały się one w kosmicznej mgle'/* . Poszukiwania trwały jeszcze przez jakiś czas, ale nie udało się odkryć nowych form życia.'*/,
        /*'Po intensywnych poszukiwaniach załoga statku ekspedycyjnego natrafiła na ogromną, */'luminescencyjną amebę'/* ! Ameba ta niestety nie najlepiej radziła sobie w standardowych testach na ustalenie ilorazu kosmicznej inteligencji. Ponadto ameby nie cieszyły się zbyt wielkim uznaniem wśród naukowców, więc postanowiono nie drążyć tego tematu i wrócić do domu.'*/,
        /*'Dziwna mgła zahipnotyzowała całą załogę statku ekspedycyjnego. Nieznane kolory i wzory przenikają do mózgu ludzkiego i wytwarzają tam dziwny zamęt, sprawiając, że załoga zamiast szukać pozaziemskich form życia, próbuje odpowiedzieć na pytanie "*/'Czy kosmici jedzą zielone hot dogi'/* ?". Nie trzeba chyba dodawać, że załoga nie znalazła nowych form życia.'*/,
        /*'Podczas poszukiwania pozaziemskiego życia */'statek ekspedycyjny wpadł w kosmiczny wir'/* , który niestety poważnie uszkodził zewnętrzną osłonę statku. Wprawdzie załogę i statek uratował ryzykowny manewr podczas lotu, ale musieli przerwać wyprawę i powrócili z pustymi rękami.'*/,
        /*'Statek ekspedycyjny */'natrafił na od dawna opuszczoną stację badawczą'/* , którą zamieszkiwały dotychczas nieznane istoty żyjące. Przeprowadzenie dokładnych analiz wykazało niestety, że jest to jedynie wyrafinowany żart pewnej wymarłej już formy życia. Załoga zniszczyła wszystkie szydercze atrapy i wróciła zła na pokład.'*/,
        /*'Na dzikiej */'planecie załogi odkryła bardzo nowoczesną stację badawczą'/* , która była nadzorowana i sterowana przez sztuczną inteligencję. Drzwi do stacji były jednak chronione hasłem, a AI nie była skora do komunikacji. Po wielu dniach nieudanych prób odgadnięcia hasła zaczęły kończyć się zapasy, a załoga już chciała się poddać, gdy nagle jednemu z jej członków jakimś cudem udało się zgadnąć hasło. Wewnątrz budynku okazało się jednak, że ta dość imponująca AI była jedynie wyrafinowanym systemem automatyki domowej, a zawiedziona załoga wróciła na statek z pustym rękoma.'*/,
        /*'Z powodu technicznego błędu w systemie nawigacyjnym statek ekspedycyjny */'niebezpiecznie zbliżył się do horyzontu zdarzeń czarnej dziury'/* . Załodze udało się w ostatniej chwili zawrócić, ale zużyli cały zapas paliwa i musieli zrezygnować z poszukiwań nowych form życia.'*/,
        /*'Statek ekspedycyjny z nieukrywanym entuzjazmem zgłosił natrafienie na */'identycznej konstrukcji statek ekspedycyjny z lustrzanego uniwersum'/* . Jego załoga, pochodząca przecież z innego wymiaru, miała nawet te same imiona. Na tym zakończyły się jednak jakiekolwiek podobieństwa, gdyś nasi goście z innego świata zachowali się podczas międzywymiarowej imprezy powitalnej tak chamsko i gburowato, że w trybie natychmiastowym zostali wydaleni z naszego uniwersum. Załoga naszego statku ekspedycyjnego nie kryła rozczarowania, ale wszyscy odczuli jednak także przynajmniej lekką ulgę.'*/,
        /*'Załoga statku ekspedycyjnego zmagała się od dłuższego czasu ze znacznymi wewnętrznymi konfliktami, */'które w końcu doprowadziły do buntu'/* . Gdy ekipy ratunkowe odnalazły porzuconych członków załogi, okazało się że druga strona konfliktu porwała statek i dołączyła do bandy kosmicznych piratów. W konsekwencji tego zajścia wprowadzono przepis, który nakazuje wszystkim załogom statków odbywanie cokwartalnych seminariów promujących team building.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'Załodze statku */'ekspedycyjnego udało się nawiązać kontakt z nieznaną rasą obcych'/* , która na pierwszy rzut oka wydawała się być przyjazna. Wiadomości naszych ambasadorów i załogi dosyć szybko wydały nam się jednak aż nazbyt euforyczne i musieliśmy wyjść z założenia, że ulegli hipnozie. Ich ostatnich znakiem życia było bardzo radosne orzeczenie całej załogi, że zostaną już na stale u ich nowych najlepszych przyjaciół. Od tamtej pory zaginął po nich wszelki ślad.'*/,
        /*'W trakcie poszukiwania inteligentnych form życia statek wylądował na nieznanym do tej pory księżycu. Załoga statku dosyć szybko dowiedziała się, dlaczego jeszcze nikt nie udokumentował istnienia tego ciała niebieskiego. Udało im się wysłać jeszcze szybki sygnał SOS, ale niestety było już za późno. */'Ogromne czerwie magmowe pochłonęły cały statek'/* wraz za załogą w przeciągu kilku minut.'*/,
        /*'Statek ekspedycyjny natrafił na nieznany do tej pory gatunek istot żyjących, */'które okazały się jednak wrogo nastawione'/* . Z ostatniej wiadomości załogi wynika, że jej członkowie zostali pojmani i uprowadzeni przez obcych. Niestety nie udało się ustalić ani lokalizacji statku, ani dalszych losów jego załogi.'*/,
        /*'Statek ekspedycyjny wylądował na nieznanej planecie, by uzupełnić zapasy. Planeta ta była spowita tajemniczą mgłą, */'która okazała się być niezwykle silnym gazem usypiającym'/* . Jego moc była na tyle niezwykła, że nikt nie odważył się podjąć misji ratunkowej.'*/,
        /*'Załoga tego statku ekspedycyjnego już zawsze słynęła z brawurowych manewrów i miała w całej flocie reputację nieustraszonej, co czyniło ją idealnym wyborem do tej misji. Pewnie dlatego jej członkowie pomyśleli, że mogą */'spokojnie przelecieć przez sam środek pola asteroid'/* . Niestety tym razem ich odwaga nie była najlepszym doradcą, a ze statku pozostał tylko kosmiczny złom.'*/,
        /*'Wygląda na to, że */'statek ekspedycyjny przepadł w do tej pory nieznanej osobliwości'/* . Nie udało się namierzyć oznak życia załogi.'*/,
        /*LOCA: pl 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*'Statek ekspedycyjny przechwycił bardzo obiecujące sygnały. Gdy pełna nadziei załoga podążała za energetycznymi śladami, */'doszło nagle do zerwania połączenia'/* , którego nie udało się już niestety przywrócić. Wysłane oddziały poszukiwawcze nie znalazły żadnych wskazówek co do lokalizacji statku. Najwidoczniej przepadł w bezkresach kosmosu.'*/,
        /*'Podczas śledzenia silnych kosmicznych sygnałów nawigator był najwidoczniej zafiksowany na celu, */'że nie zauważył znajdującej się pobliżu czarnej dziury'/* . Wkrótce statek wpadł w jej pole grawitacyjne i nawet największe wysiłki załogi nie powstrzymały go przed trafieniem do jej bezdennej głębi. Aby zapobiec takim wypadkom, ustalono nowy standard, według którego skanery automatycznie alarmują w przypadku niedalekiej obecności czarnych dziur.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /Odkryto formę życia .+ na współrzędnych .+ i dodano ją do Zarządzania formami życia/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Jednak nasi posłańcy pogłębili naszą wiedzę na jej temat o (?<xp>\d+) doświadczenia/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*'Statek ekspedycyjny znalazł */'kilka artefaktów, ale nie mógł ich zabrać, ponieważ twoje'/* magazyny są pełne.'*/,
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'Statek */'ekspedycyjny znalazł kilka artefaktów',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Statek */'ekspedycyjny znalazł dużą ilość artefaktów',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*'Statek */'ekspedycyjny znalazł olbrzymią kolekcję artefaktów',
        },
        numberOfArtifacts: /Znalezione artefakty: (?<artifacts>\d+)/i,
    },
};