import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const pl: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Na początku wyprawy udało im się */'odszyfrować z tajnej wiadomości kilka obiecujących współrzędnych'/* . Jednak gdy statek ekspedycyjny dotarł do wyznaczonego sektora, załoga znalazła tylko gigantyczne pole zniszczeń pozostałe po zakończonej bitwie. Nie odnaleziono tam żadnych ocalałych.'*/,
        'Magnetyczne pole asteroid zakłóciło pracę skanerów'/*. To, co wydawało się obiecującym sygnałem inteligentnej pozaziemskiej formy życia, było po prostu tylko małą usterką urządzeń pomiarowych, a nie nową formą życia.'*/,
        /*'W momencie przejęcia sygnału radiowego przez statek ekspedycyjny, */'doszło do awarii wszystkich systemów komunikacjach'/* . W tych okolicznościach nie tylko nie było możliwe nawiązanie kontaktu z inteligentną formą życia, ale także kontynuowanie misji mogłoby się okazać niebezpieczne. Wprawdzie załoga powróciła do domu rozczarowana, ale cała i zdrowa.'*/,
        /*'W dużej mierze niezbadanym jeszcze systemie */'planetarnym odkryto samoświadomą kosmiczną mgłę'/* ! Nasi międzygalaktyczni ambasadorzy byli tak podekscytowani, że przy dużym medialnym rozgłosie wysłali sondę badawczą. Gdy jednak próbowali za jej pomocą nawiązać kontakt ze świeżo odkrytym mgielnym bytem, okazało się, że jego inteligencja nie przewyższa intelektu plujki pospolitej. Ekscytacja znaleziskiem szybko wygasła, a pobłażliwe media zgodziły się przemilczeć to niefortunne wydarzenie.'*/,
        /*LOCA: pl 'Bei der Suche nach neuen Lebensformen folgte das Erkundungsschiff einigen mysteriösen Signalen, die */'von der Rückseite eines unbekannten Planeten zu stammen'/* schienen. Die intergalaktischen Botschafter an Bord hatten schon das Begrüßungspaket geholt und den Übersetzungscomputer aktiviert, doch es stellte sich heraus, dass das Signal von einem Schiffswrack stammt. Das Schiff ist eindeutig außerirdischer Herkunft, aber von den Piloten fehlt leider jede Spur. So konnte keine neue Lebensform entdeckt werden.'*/,
        /*'Statek ekspedycyjny był już od dłuższego czasu w drodze, gdy się okazało, że do */'oprogramowania skanującego wkradł się jakiś fatalny błąd'/* . I dlatego też nie można było odkryć żadnej nowej formy życia.'*/,
        /*LOCA: pl 'Leider erwies sich die insektoide Alienspezies, die unsere */'intergalaktischen Botschafter wegen der außerordentlichen Sauberkeit'/* ihres Heimatplaneten zunächst für intelligent hielten, doch als eher einfach gestrickt. Nachdem sie den Inhalt der Bord-Müllpresse gefressen hatten, wurden sie deshalb wieder auf ihrem Planeten ausgesetzt, trotz eines Votums der Crew, doch ein paar Exemplare zu behalten.'*/,
        /*'Na samym środku pola asteroid zachwyceni naukowcy */'statku ekspedycyjnego znaleźli sieć neuronalną'/* . Tym większe było ich rozczarowanie, gdy się okazało, że jest to jedynie zbitek wiadomości sportowych sprzed stuleci, w dodatku o bardzo wątpliwej wiarygodności. Załoga powróciła do doku bez żadnych wyników i z miernymi nastrojami.'*/,
        /*'Wśród załogi statku ekspedycyjnego zapanowała radosna nadzieja, gdy */'badania zarodników pleśni wykazały poszlaki inteligentnego życia'/* . Nieco później okazało się jednak, że była to niecna manipulacja jakiegoś zgrywusa, który chciał skompromitować swojego kolegę po fachu. Analizowane zarodniki mogły poszczycić się w rzeczywistości inteligencją nie większą od przeciętnej pleśni rozprzestrzeniającej się po kuchni pokładowej. Sabotażystę eksperymentu wysadzono po prostu na pierwszej lepszej planecie, a statek powrócił bezowocnie do doku.'*/,
        /*'Obiecujące sygnały pokierowały statek */'ekspedycyjny do tajemniczej złotej sfery'/* , która samotnie unosiła się w głębiach kosmosu. Mimo wszelkich starań międzygalaktycznym posłańcom nie udało się odnaleźć wejście ani nawiązać kontaktu z dziwnym obiektem, zanim ten nagle odleciał.'*/,
        /*'Statek ekspedycyjny odkrył na nieznanej planecie system roślin, który wydawał się być nad wyraz inteligentny. Gdy załoga chciała go zbadać, */'została zatrzymana przez tajemnicze roboty w mundurach'/* , które zwróciły naukowcom uwagę, że jest to własność prywatna. Mimo gróźb międzygalaktycznych procesów sądowych członkowie naszej załogi ekstrahowali pod osłoną nocy próbki z tej rzekomo inteligentnej rośliny i niepostrzeżenie wrócili na pokład. W laboratorium okazało się jednak, że zebrane po ciemaku próbki pochodzą z najzwyklejszych roślin pokojowych.'*/,
        /*'W poszukiwaniu obcego inteligentnego życia statek ekspedycyjny kluczył już od wielu miesięcy bezowocnie po przepastnej galaktyce, gdy nagle jego załoga natrafiła na */'kosmicznego kuzyna naszego ziemskiego pantofelka'/* ! Ta forma życia do inteligentnych co prawda nie należała, ale członkowie załogi byli już tak zmęczeni tą długą podróżą, że zadowolili się i takim znaleziskiem i obrali kurs powrotny.'*/,
        /*LOCA: pl 'Die vielversprechenden Signale, denen das Erkundungsschiff folgte, */'verloren sich leider in einem kosmischen Nebel'/*. Die Suche wurde noch eine Weile fortgesetzt, aber es konnten keine neuen Lebensformen entdeckt werden.'*/,
        /*'Po intensywnych poszukiwaniach załoga statku ekspedycyjnego natrafiła na ogromną, */'luminescencyjną amebę'/* ! Ameba ta niestety nie najlepiej radziła sobie w standardowych testach na ustalenie ilorazu kosmicznej inteligencji. Ponadto ameby nie cieszyły się zbyt wielkim uznaniem wśród naukowców, więc postanowiono nie drążyć tego tematu i wrócić do domu.'*/,
        /*'Dziwna mgła zahipnotyzowała całą załogę statku ekspedycyjnego. Nieznane kolory i wzory przenikają do mózgu ludzkiego i wytwarzają tam dziwny zamęt, sprawiając, że załoga zamiast szukać pozaziemskich form życia, próbuje odpowiedzieć na pytanie "*/'Czy kosmici jedzą zielone hot dogi'/* ?". Nie trzeba chyba dodawać, że załoga nie znalazła nowych form życia.'*/,
        /*'Podczas poszukiwania pozaziemskiego życia */'statek ekspedycyjny wpadł w kosmiczny wir'/* , który niestety poważnie uszkodził zewnętrzną osłonę statku. Wprawdzie załogę i statek uratował ryzykowny manewr podczas lotu, ale musieli przerwać wyprawę i powrócili z pustymi rękami.'*/,
        /*'Statek ekspedycyjny */'natrafił na od dawna opuszczoną stację badawczą'/* , którą zamieszkiwały dotychczas nieznane istoty żyjące. Przeprowadzenie dokładnych analiz wykazało niestety, że jest to jedynie wyrafinowany żart pewnej wymarłej już formy życia. Załoga zniszczyła wszystkie szydercze atrapy i wróciła zła na pokład.'*/,
        /*LOCA: pl 'Auf einem wilden Planeten */'entdeckte die Crew eine hochmoderne Forschungsstation'/*, die von einer künstlichen Intelligenz gesteuert und bewacht wurde. Die Tür zur Station war allerdings durch ein Passwort geschützt und die KI verweigerte die Kommunikation. Nachdem nach tagelangen Ratespielen die Vorräte knapp wurden, gelang es einem bisher eher unscheinbaren Mitglied der Crew, das Passworträtsel zu entschlüsseln. Im Inneren der Anlage stellte sich aber leider heraus, dass die KI nur ein elaboriertes Home-Management-System war und die Crew machte sich enttäuscht auf den Heimweg.'*/,
        /*'Z powodu technicznego błędu w systemie nawigacyjnym statek ekspedycyjny */'niebezpiecznie zbliżył się do horyzontu zdarzeń czarnej dziury'/* . Załodze udało się w ostatniej chwili zawrócić, ale zużyli cały zapas paliwa i musieli zrezygnować z poszukiwań nowych form życia.'*/,
        /*'Statek ekspedycyjny z nieukrywanym entuzjazmem zgłosił natrafienie na */'identycznej konstrukcji statek ekspedycyjny z lustrzanego uniwersum'/* . Jego załoga, pochodząca przecież z innego wymiaru, miała nawet te same imiona. Na tym zakończyły się jednak jakiekolwiek podobieństwa, gdyś nasi goście z innego świata zachowali się podczas międzywymiarowej imprezy powitalnej tak chamsko i gburowato, że w trybie natychmiastowym zostali wydaleni z naszego uniwersum. Załoga naszego statku ekspedycyjnego nie kryła rozczarowania, ale wszyscy odczuli jednak także przynajmniej lekką ulgę.'*/,
        /*'Załoga statku ekspedycyjnego zmagała się od dłuższego czasu ze znacznymi wewnętrznymi konfliktami, */'które w końcu doprowadziły do buntu'/* . Gdy ekipy ratunkowe odnalazły porzuconych członków załogi, okazało się że druga strona konfliktu porwała statek i dołączyła do bandy kosmicznych piratów. W konsekwencji tego zajścia wprowadzono przepis, który nakazuje wszystkim załogom statków odbywanie cokwartalnych seminariów promujących team building.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*LOCA: pl 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*LOCA: pl 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /*LOCA: pl 'Das Erkundungsschiff schaffte es zwar, eine intelligente Alienspezies aufzuspüren, */'diese erwies sich jedoch als feindselig'/*. Dem letzten Funkspruch der Crew ist zu entnehmen, dass sie von den Außerirdischen als Gefangene abtransportiert wurden. Jeglicher Versuch, den weiteren Verbleib des Schiffes und seiner Besatzung aufzuklären, blieb leider erfolglos.'*/,
        /*LOCA: pl 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*'Załoga tego statku ekspedycyjnego już zawsze słynęła z brawurowych manewrów i miała w całej flocie reputację nieustraszonej, co czyniło ją idealnym wyborem do tej misji. Pewnie dlatego jej członkowie pomyśleli, że mogą */'spokojnie przelecieć przez sam środek pola asteroid'/* . Niestety tym razem ich odwaga nie była najlepszym doradcą, a ze statku pozostał tylko kosmiczny złom.'*/,
        /*LOCA: pl 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*LOCA: pl 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*LOCA: pl 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*LOCA: pl 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /Odkryto formę życia .+ na współrzędnych .+ i dodano ją do Zarządzania formami życia/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Jednak nasi posłańcy pogłębili naszą wiedzę na jej temat o (?<xp>\d+) doświadczenia/i,
};