import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const pt: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*TODO: pt 'Zu Beginn der Erkundung konnten einige */'vielversprechende Koordinaten aus einer geheimnisvollen Nachricht'/* entschlüsselt werden. Als das Erkundungsschiff jedoch den angegebenen Sektor erreichte, fand die Crew nur noch das riesige Trümmerfeld eines bewaffneten Konflikts vor. Die Suche nach Überlebenden blieb erfolglos.'*/,
        /*TODO: pt 'Ein */'magnetisches Asteroidenfeld störte ungünstigerweise die Scanner'/*. Was wie ein vielversprechendes Signal intelligenten außerirdischen Lebens aussah, war nur eine Störung der Messinstrumente und es konnte keine neue Lebensform gefunden werden.'*/,
        /*TODO: pt 'Gerade als das Erkundungsschiff einen vielversprechenden Funkspruch auffangen konnte, */'kam es zu einem Totalausfall sämtlicher Kommunikationssysteme'/*. Unter diesen Umständen war nicht nur jede Kontaktaufnahme mit eventuellen intelligenten Lebensformen ausgeschlossen, ein Fortführen der Mission wäre auch gefährlich gewesen. Deshalb kehrte die Crew enttäuscht, aber unversehrt zurück.'*/,
        /*'Foi descoberta uma nébula com uma qualquer forma de */'consciência numa área muito inexplorada do nosso sistema'/* ! Os nossos emissários intergalácticos mal conseguiam conter o seu entusiasmo. Chegou mesmo a montar-se um circo mediático quando foi enviada uma sonda para o interior da nuvem. Mas as tentativas de comunicação com a nébula revelaram que a sua inteligência era semelhante à de uma barata. O entusiasmo rapidamente desapareceu e foi decidido esquecer este episódio o mais rápido possível.'*/,
        /*'À procura de novas formas de vida, a Nave de Exploração seguiu alguns sinais misteriosos que pareciam ter origem no lado */'longínquo de um planeta desconhecido'/*. Os emissários intergalácticos a bordo já tinham o pacote de saudações pronto e o computador de tradução ativado, mas descobriu-se que o sinal tinha origem num destroço. A nave tem origem definitivamente extraterrestre, mas, infelizmente, não há sinais da tripulação. Não foi encontrada nenhuma forma de vida nova.'*/,
        /*TODO: pt 'Das Erkundungsschiff war einige Zeit unterwegs, bis sich herausstellte, dass sich ein */'fataler Bug in die Scan-Software eingeschlichen'/* hatte. So konnte leider keine neue Lebensform aufgespürt werden.'*/,
        /*TODO: pt 'Leider erwies sich die insektoide Alienspezies, die unsere */'intergalaktischen Botschafter wegen der außerordentlichen Sauberkeit'/* ihres Heimatplaneten zunächst für intelligent hielten, doch als eher einfach gestrickt. Nachdem sie den Inhalt der Bord-Müllpresse gefressen hatten, wurden sie deshalb wieder auf ihrem Planeten ausgesetzt, trotz eines Votums der Crew, doch ein paar Exemplare zu behalten.'*/,
        /*'Os investigadores a bordo da Nave de Exploração ficaram muito entusiasmados quando */'descobriram uma rede neural no centro de um campo'/* de asteroides. Foi uma enorme deceção quando descobriram apenas um punhado de notícias intercetadas sobre resultados desportivos de há muitos séculos atrás. Estas notícias tinham desenvolvido uma vida própria, como se fossem um tipo qualquer de comentador desportivo espacial. A tripulação regressou com os espíritos em baixo, sem ter descoberto algo mais significante do que quem se sagrou vencedor em determinadas competições.'*/,
        /*TODO: pt 'Die Crew des Erkundungsschiffes war hellauf begeistert, als */'Untersuchungen von Schimmelsporen intelligentes Leben versprachen'/*. Leider stellte sich heraus, dass ein Witzbold die Forschungsergebnisse manipuliert hatte, um einen rivalisierenden Forscher bloßzustellen. Die untersuchten Sporen waren in Wahrheit kein bisschen intelligenter als der durchschnittliche Schimmelpilz in der Bordküche. Der Unruhestifter wurde auf den nächstbesten Planeten beurlaubt und das Schiff kehrte ergebnislos zurück.'*/,
        /*'Alguns sinais promissores guiaram a Nave de Exploração até uma esfera */'dourada misteriosa que flutuava abandonada nos confins'/* do espaço. Apesar de todos os esforços dos emissários intergalácticos a bordo, não foi possível descobrir uma entrada ou estabelecer qualquer tipo de contacto com este estranho objeto antes de ele desaparecer subitamente.'*/,
        /*'Num planeta inexplorado, a Nave de Exploração descobriu um sistema de flores mais inteligente do que aparentava. No entanto, quando a tripulação tentou investigar, surgiram alguns */'guardas robóticos em uniformes a avisá-los de que as plantas'/* eram propriedade privada. Ignorando as possíveis dificuldades causadas por violações das leis intergalácticas sobre a invasão de propriedade, os investigadores decidiram extrair algumas amostras com uma operação clandestina durante o escuro da noite, escapando na sua nave. Infelizmente, parece que a noite era demasiado escura. A bordo da sua nave, descobriram que as amostras pelas quais arriscaram tanto eram meras plantas de ter por casa.'*/,
        /*TODO: pt 'Bei der Suche nach außerirdischem intelligentem Leben irrte das Erkundungsschiff bereits seit Monaten durch die Galaxis, als sie */'endlich einen außerirdischen Verwandten des Pantoffeltierchens'/* fanden! Diese Lebensform war zwar nicht intelligent, aber aufgrund der langen Reise und blankliegender Nerven entschied die Crew, auch mit unintelligentem Leben vorlieb zu nehmen und ohne nennenswerte Funde zurückzukehren.'*/,
        /*'Os extremamente promissores sinais perseguidos pela Nave de Exploração */'foram perdidos numa neblina cósmica'/*. A busca ainda se prolongou por mais algum tempo, mas não foi encontrada nenhuma forma de vida nova.'*/,
        /*TODO: pt 'Nach intensiver Suche fand die Crew des */'Erkundungsschiffes eine lumineszente Riesenamöbenart'/*! Leider hatten die Amöben Schwierigkeiten bei der Bearbeitung des standardisierten Tests zur Identifikation außerirdischer Intelligenz. Deshalb und weil in Forscherkreisen Amöben leider immer noch verkannt werden, wurde diese Entdeckung als nicht relevant eingestuft.'*/,
        /*TODO: pt 'Ein hypnotischer Nebel zog die gesamte Crew des Erkundungsschiffes in seinen Bann. Die fremdartigen Farben und Muster scheinen auf ungünstige Weise mit dem menschlichen Gehirn zu interferieren, wodurch die Besatzung statt der Suche nach außerirdischem Leben der Beantwortung der Frage „*/'Essen Aliens eigentlich grüne Hotdogs'/*?“ nachging. Überflüssig zu erwähnen, dass sie keine neue Lebensform fanden.'*/,
        /*'Durante a sua busca por vida extraterrestre, a Nave de Exploração */'entrou num vórtice cósmico que provocou danos graves'/* ao casco externo. A tripulação e a nave foram salvas graças a uma manobra de voo arriscada, mas tiveram de abandonar a exploração e regressar a casa de mãos vazias.'*/,
        /*TODO: pt 'Das Erkundungsschiff stieß auf eine */'alte verlassene Raumstation, die von bisher unbekannten Lebewesen'/* bewohnt wurde. Nach eingehender Untersuchung musste man allerdings feststellen, dass es sich um den ausgeklügelten Scherz einer bereits ausgestorbenen Lebensform handelte. Die Crew zerstörte die hämischen Botschaften, konnte ansonsten aber nichts entdecken.'*/,
        /*'Num planeta solitário e selvagem, a tripulação deparou-se com uma estação de */'pesquisa liderada por uma IA de alta tecnologia'/*. Infelizmente, a porta da estação estava protegida por uma palavra-passe e a IA recusou-se a cooperar. A tripulação passou dias a tentar decifrar a palavra-passe. Os mantimentos estavam prestes a esgotar-se quando um dos membros mais discretos descobriu a combinação. Para sua tristeza, a estação foi uma deceção: a IA era pouco mais do que um elaborado sistema de gestão de casas. A tripulação decidiu regressar ao planeta de origem.'*/,
        /*'Um erro técnico no módulo de navegação conduziu a Nave de Exploração até perigosamente */'perto do horizonte de eventos de um buraco negro'/*. A tripulação conseguiu inverter a trajetória a tempo, mas com um enorme custo para os níveis de combustível. Por este motivo, a busca por novas formas de vida teve de ser interrompida e terminou sem sucesso.'*/,
        /*TODO: pt 'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
        /*TODO: pt 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'A tripulação da Nave de Exploração contactou com sucesso uma */'espécie alienígena até agora desconhecida'/*. As primeiras impressões sugeriram que se tratava de uma espécie benevolente. No entanto, os relatórios dos nossos emissários e da nossa tripulação tinham um tom cada vez mais eufórico, o que nos leva a assumir que foram alvo de uma qualquer forma de hipnose. O último relatório que recebemos era uma proclamação extremamente feliz, em nome de toda a tripulação, das suas intenções de permanecerem para sempre na companhia destes alienígenas amigáveis. A nave e a tripulação desapareceram sem deixar rasto.'*/,
        /*TODO: pt 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /*TODO: pt 'Das Erkundungsschiff schaffte es zwar, eine intelligente Alienspezies aufzuspüren, */'diese erwies sich jedoch als feindselig'/*. Dem letzten Funkspruch der Crew ist zu entnehmen, dass sie von den Außerirdischen als Gefangene abtransportiert wurden. Jeglicher Versuch, den weiteren Verbleib des Schiffes und seiner Besatzung aufzuklären, blieb leider erfolglos.'*/,
        /*TODO: pt 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*TODO: pt 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*TODO: pt 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*TODO: pt 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*TODO: pt 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*TODO: pt 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /nas coordenadas .+ e adicionada ao menu Formas de Vida/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /*TODO: pt *//Dennoch konnten unsere Botschafter unser Wissen über sie um (?<xp>\d+) Erfahrung verbessern/g,
};