import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const pt_br: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'No início de sua exploração, eles */'conseguiram decifrar algumas coordenadas promissoras que obtiveram'/* de uma mensagem misteriosa. Mas quando a Nave de Exploração chegou ao setor das coordenadas mencionadas, tudo o que a tripulação encontrou foi um gigantesco campo de destroços deixado para trás após uma batalha. A busca por sobreviventes acabou sendo infrutífera.'*/,
        /*'Um */'campo magnético de asteróide estava interrompendo'/* os scanners. O que parecia ser um sinal promissor de vida extraterrestre inteligente foi apenas uma interrupção nos instrumentos de medição e nenhuma nova forma de vida pôde ser encontrada.'*/,
        /*'Assim que a Nave de Exploração interceptou um sinal de rádio promissor, */'todos os seus sistemas de comunicação caíram de repente'/* . Dadas as circunstâncias, não era apenas impossível fazer contato com potenciais formas de vida inteligentes, mas também seria perigoso continuar a missão. Assim, a tripulação voltou para casa desapontada, mas ilesa.'*/,
        /*LOCA: pt-br 'In einem noch größtenteils unerforschten Planetensystem */'wurde ein kosmischer Nebel mit Bewusstsein entdeckt'/* ! Die intergalaktischen Botschafter gerieten in helle Aufregung, weshalb unter großer medialer Aufmerksamkeit eine Sonde entsandt wurde. Beim Kommunikationsversuch mit dem Nebel stellte sich aber schnell heraus, dass seine Intelligenz kaum über der von einfachen Insekten lag. Die Aufregung schwand und es wurde beschlossen, einen Mantel des Schweigens über die ganze Aktion zu breiten.'*/,
        /*'Em busca de novas formas de vida, a Nave de Exploração seguiu alguns sinais misteriosos que pareciam vir do */'outro lado de um planeta desconhecido'/* . Os enviados intergalácticos a bordo já haviam recuperado o pacote de saudação e ativado o computador de tradução, mas se descobriu que o sinal vinha de um naufrágio. A nave é claramente de origem extraterrestre, mas infelizmente não há sinais de tripulação. Isso significava que nenhuma nova forma de vida foi encontrada.'*/,
        /*LOCA: pt-br 'Das Erkundungsschiff war einige Zeit unterwegs, bis sich herausstellte, dass sich ein */'fataler Bug in die Scan-Software eingeschlichen'/* hatte. So konnte leider keine neue Lebensform aufgespürt werden.'*/,
        /*'Nossos emissários visitaram um planeta com uma */'espécie insetóide extremamente limpa'/* , supondo que eles deveriam ser inteligentes, eles ficaram desapontados com o que descobriram. Depois de vê-los mastigar o conteúdo do compactador de lixo da nave, foi decidido devolver eles ao seu planeta, apesar da sugestão de alguns tripulantes de manter um casal a bordo.'*/,
        /*LOCA: pt-br 'Vollkommen begeistert fanden die Forscher des Erkundungsschiffes */'ein neuronales Netzwerk mitten in einem Asteroidenfeld'/*. Die Enttäuschung war groß, als sich herausstellte, dass es sich lediglich um ein Cluster verfangener Nachrichten mit jahrhundertealten Sportergebnissen handelte, die das Eigenleben eines schlecht informierten Stammtisches entwickelt hatten. Die Crew kehrte niedergeschlagen und ohne signifikante Ergebnisse zurück.'*/,
        /*'A tripulação da nave de exploração estava na lua quando os resultados dos */'testes nos esporos de fungos sugeriram que haviam encontrado'/* vida inteligente. Infelizmente, descobriram que alguém manipulou os resultados do teste apenas para constranger um pesquisador rival. Os esporos, na realidade, não eram mais inteligentes do que aqueles encontrados atrás do micro-ondas na cozinha. O encrenqueiro foi suspenso e deixado no planeta mais próximo, antes que a nave voltasse para casa.'*/,
        /*'Sinais promissores guiaram a Nave de Exploração até uma */'misteriosa esfera dourada flutuando sozinha nas profundezas'/* do espaço. Apesar de todos os esforços dos enviados, eles não conseguiram encontrar uma entrada ou fazer qualquer tipo de contato com o objeto estranho antes que ele fosse para longe'*/,
        /*'Em um planeta inexplorado, a nave de exploração descobriu um sistema floral que era muito mais inteligente do que parecia à primeira vista. Quando a tripulação tentou investigar, no entanto, */'estranhos robôs de guarda uniformizados apareceram'/* e os avisaram que as plantas eram propriedade privada. Ignorando as potenciais para quebrar as leis de invasão intergaláctica, os pesquisadores fortaleceram sua determinação e extraíram algumas amostras durante uma operação secreta, antes de ir rapidamente para a órbita. Infelizmente, a operação foi claramente um pouco secreta e de volta a bordo da nave eles descobriram que suas amostras adquiridas arriscadamente não eram nada mais do que plantas domésticas comuns.'*/,
        /*'Em sua busca por inteligência extraterrestre, a nave de exploração já havia passado meses em vão vasculhando a galáxia, quando finalmente descobriram o */'equivalente alienígena de um paramécio'/* ! Não se encaixava exatamente nos critérios de vida inteligente, mas depois de tantos meses monótonos de busca, a tripulação decidiu considerar a descoberta de vida ainda não inteligente como um sucesso e voltou para casa sem nenhuma notícia notável.'*/,
        /*'Os sinais altamente promissores que a Nave de Exploração */'rastreou foram tristemente perdidos em uma névoa cósmica'/* . Eles continuaram a busca por mais algum tempo, mas não conseguiram encontrar nenhuma nova forma de vida'*/,
        /*'Após uma busca intensiva, a tripulação da nave de exploração */'descobriu uma espécie luminescente de ameba gigante'/* ! Infelizmente, os organismos unicelulares tiveram alguns problemas ao tentar passar nos testes de inteligência padrão. Dada a pouca atenção que deram as amebas pelos pesquisadores, não é surpresa que essa descoberta tenha sido igualmente considerada insignificante.'*/,
        /*'Uma névoa hipnótica atraiu toda a tripulação da Nave de Exploração sob seu feitiço. As cores e desenhos estranhos parecem interferir no cérebro humano de alguma forma, em vez de procurar vida extraterrestre, a tripulação se preocupou em responder à pergunta "*/'Os alienígenas realmente comem cachorro-quente verde'/* ?" Desnecessário dizer que eles não encontraram nenhuma nova forma de vida.'*/,
        /*LOCA: pt-br 'Bei der Suche nach außerirdischem Leben */'geriet das Erkundungsschiff in einen kosmischen Vortex'/*, der die Außenhülle schwer beschädigte. Durch ein riskantes Flugmanöver konnten Crew und Schiff gerettet werden, mussten jedoch die Erkundung aufgeben und ohne Ergebnisse zurückkehren.'*/,
        /*'A nave de exploração encontrou uma */'estação espacial antiga e abandonada que já foi tripulada por algumas'/* espécies anteriormente desconhecidas. Após um estudo mais intensivo, no entanto, logo ficou claro que a estação era apenas uma farsa elaborada de uma forma de vida extinta. A tripulação destruiu as mensagens, mas não conseguiu descobrir mais nada digno de nota.'*/,
        /*LOCA: pt-br 'Auf einem wilden Planeten */'entdeckte die Crew eine hochmoderne Forschungsstation'/*, die von einer künstlichen Intelligenz gesteuert und bewacht wurde. Die Tür zur Station war allerdings durch ein Passwort geschützt und die KI verweigerte die Kommunikation. Nachdem nach tagelangen Ratespielen die Vorräte knapp wurden, gelang es einem bisher eher unscheinbaren Mitglied der Crew, das Passworträtsel zu entschlüsseln. Im Inneren der Anlage stellte sich aber leider heraus, dass die KI nur ein elaboriertes Home-Management-System war und die Crew machte sich enttäuscht auf den Heimweg.'*/,
        /*'Um erro técnico no módulo de navegação levou a Nave de Exploração muito */'próximo do horizonte de eventos de um buraco negro'/* . A tripulação conseguiu dar a volta bem a tempo, mas acabou drenando seus suprimentos de combustível e teve que interromper a busca por novas formas de vida sem sucesso.'*/,
        /*'A nave de exploração relatou com entusiasmo que havia */'encontrado uma nave idêntica de um universo paralelo'/* . A tripulação desta dimensão tinha até os mesmos nomes. Mas as semelhanças pararam por aí: na festa de boas-vindas, os convidados eram tão grosseiros que a tripulação os expulsou do nosso universo. Decepcionada, mas ao mesmo tempo aliviada, a tripulação voltou para casa.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*LOCA: pt-br 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
        /*'A tripulação da nave de exploração fez */'contato com sucesso com uma espécie alienígena anteriormente'/* desconhecida. As primeiras impressões sugeriam que eles eram benevolentes. No entanto, os relatórios do nosso emissário e da tripulação foram cada vez mais eufóricos, devemos supor que foram submetidos a algum tipo de hipnose. O relatório final que recebemos foi uma proclamação alegre em nome de toda a tripulação que eles permanecem ficar com esses alienígenas amigáveis. A nave e sua tripulação desapareceram sem deixar vestígios.'*/,
        /*'Em sua busca por formas de vida inteligentes, a nave parou em uma lua anteriormente inexplorada. Pelo menos, a lua nunca havia sido relatada. Logo ficou claro o motivo. A tripulação conseguiu emitir um sinal de socorro, embora já fosse tarde demais. Despertados pela chegada da nave, */'gigantescos vermes de magma devoraram nave e sua tripulação'/* em poucos minutos.'*/,
        /*LOCA: pt-br 'Das Erkundungsschiff schaffte es zwar, eine intelligente Alienspezies aufzuspüren, */'diese erwies sich jedoch als feindselig'/*. Dem letzten Funkspruch der Crew ist zu entnehmen, dass sie von den Außerirdischen als Gefangene abtransportiert wurden. Jeglicher Versuch, den weiteren Verbleib des Schiffes und seiner Besatzung aufzuklären, blieb leider erfolglos.'*/,
        /*LOCA: pt-br 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*LOCA: pt-br 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*LOCA: pt-br 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*LOCA: pt-br 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*LOCA: pt-br 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*LOCA: pt-br 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    
    [LifeformDiscoveryEventType.newLifeformFound]: /A forma de vida .+ foi descoberto nas coordenadas .+ e adicionado ao menu Formas de vida/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /enviados foram capazes de melhorar nosso conhecimento sobre eles por (?<xp>\d+) XP/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*'A Nave de Exploração encontrou */'alguns artefactos mas não pode recolhê-los porque'/* o teu armazenamento está cheio.'*/,
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'A Nave de Exploração encontrou */'uma pequena quantidade de artefatos',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'A Nave de Exploração encontrou */'uma grande quantidade de artefatos',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*A Nave de Exploração encontrou */'uma enorme quantidade de artefactos',
        },
        numberOfArtifacts: /Artefatos encontrados:\s*(?<artifacts>\d+)/i,
    },
};