import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const ro: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'La începutul explorării lor, au reușit să */'descifreze câteva coordonate promițătoare'/* pe care le-au obținut dintr-un mesaj misterios. Dar când nava de explorare a ajuns în sectorul coordonatele menționate, tot ce echipajul a găsit a fost un câmp de rămășițe uriaș lăsat în urmă după o bătălie. Căutarea supraviețuitorilor a fost în cele din urmă fără rezultate.'*/,
        /*'Un câmp de */'asteroizi magnetici perturba scanerele'/* . Ceea ce părea a fi un semnal promițător al vieții extraterestre inteligente a fost doar o defecțiune a instrumentelor de măsurare și nu au putut fi găsite noi forme de viață.'*/,
        /*'Tocmai când Nava de Explorare a interceptat un semnal radio promițător, */'toate sistemele lor de comunicații au căzut brusc'/* . Date fiind circumstanțele, nu numai că era imposibil să ia contact cu potențiale forme de viață inteligente, dar ar fi fost și periculos să continue misiunea. Așa că echipajul s-a întors acasă dezamăgit, dar nevătămat.'*/,
        /*'O */'nebuloasă cu o anumită formă de conștiință a fost'/* descoperită într-un colț în mare parte neexplorat al sistemului nostru! Emisarii noștri intergalactici au fost depășiți și a existat un circ mediatic serios când sonda a fost trimisă în nori. Încercările de a comunica cu nebuloasa au dezvăluit în curând că inteligența sa era undeva la egalitate cu cea a unui gândac. Emoția a dispărut și s-a decis să înlăture întregul episod.'*/,
        /*'Căutând noi forme de viață, nava de explorare a urmat câteva semnale misterioase care păreau să vină din */'partea îndepărtată a unei planete necunoscute'/* . Trimișii intergalactici de la bord preluaseră deja pachetul de salut și activaseră computerul de traducere, dar s-a dovedit că semnalul venea de la un o navă naufragiată. Nava este în mod clar de origine extraterestră, dar, din păcate, nu există semne ale unui echipaj. Aceasta însemna că nu a fost găsită nicio formă de viață nouă.'*/,
        /*'Nava de explorare era în zbor de ceva vreme când a ieșit la iveală că un */'bug fatal se strecurase în software-ul de scanare'/* . Acest lucru a însemnat, din păcate, că nu au putut fi găsite noi forme de viață.'*/,
        /*'Emisarii noștri intergalactici au vizitat o planetă cu o */'specie de insectoid extrem de curată'/* , presupunând că trebuie să fie inteligenți, dar au fost dezamăgiți de ceea ce au descoperit. După ce i-au văzut ronțăind conținutul compactorului de gunoi al navei, s-au decis să-i trimită pe planeta lor, în ciuda sugestiei câtorva colegi de echipaj de a păstra un cuplu la bord.'*/,
        /*'Cercetătorii de la bordul navei de explorare au fost încântați să descopere o */'rețea neuronală în mijlocul unui câmp de asteroizi'/* . De aceea, au fost cu atât mai dezamăgiți când s-a dovedit a fi nimic altceva decât un grup de știri interceptate despre rezultate sportive vechi de secole, care își dezvoltaseră o viață proprie ca un fel de expert pe canapeaua spațială. Echipajul s-a întors supărat, fără să afle ceva mai semnificativ decât cine a câștigat ultima dată niște cenușă sau altceva.'*/,
        /*'Echipajul navei de explorare era peste lună când */'rezultatele testelor asupra sporilor fungici au sugerat'/* că au găsit viață inteligentă. Din păcate, s-a dovedit că un glumeț manipulase rezultatele testelor doar pentru a face de rușine un cercetător rival. Sporii nu erau în realitate mai inteligenți decât cei găsiți în spatele cuptorului cu microunde în bucătărie. Creatorul de probleme a fost suspendat și lăsat pe cea mai apropiată planetă, înainte ca nava să se întoarcă acasă.'*/,
        /*'Semnale promițătoare au ghidat nava de */'explorare către o misterioasă sferă aurie care plutea'/* singură în adâncurile spațiului. În ciuda tuturor eforturilor trimișilor intergalactici de la bord, aceștia nu au reușit să găsească o intrare sau să facă vreun fel de contact cu obiectul ciudat înainte ca acesta să dispară brusc.'*/,
        /*'Pe o planetă neexplorată, nava de explorare a descoperit un sistem floral care era mult mai inteligent decât părea la început. Când echipajul a încercat să investigheze, totuși, au */'apărut roboți ciudați de pază în uniformă'/* și i-au avertizat că plantele sunt proprietate privată. Ignorând potențialele dificultăți de încălcare a legilor intergalactice, cercetătorii și-au întărit hotărârea și au extras câteva mostre în timpul unei operațiuni ascunse sub acoperirea întunericului, înainte de a pleca rapid pe orbită. Din păcate, operațiunea a fost în mod clar un pic PREA ascunsă pentru o grămadă de oameni de știință, iar la bordul navei au descoperit că mostrele obținute riscant nu erau altceva decât plante obișnuite de casă.'*/,
        /*'În căutarea inteligenței extraterestre, nava de explorare a petrecut deja luni inutile cutreierând fără scop galaxia, când au descoperit în sfârșit */'echivalentul extraterestru al unui parameci'/* ! Nu se potrivea exact cu criteriile vieții inteligente, dar după atâtea luni monotone de căutări, echipajul a decis să această descoperire a vieții mai puțin inteligente este un succes și s-a întors acasă fără nicio veste notabilă.'*/,
        /*'Semnalele extrem de promițătoare pe care le-a urmărit nava de explorare s-au */'pierdut, din păcate, într-o ceață cosmică'/* . Au continuat căutarea pentru o perioadă mai îndelungată, dar nu au putut găsi forme de viață noi.'*/,
        /*'După căutări intense, echipajul navei de explorare a */'descoperit o specie luminiscentă de amibă gigantică'/* ! Din păcate, organismele unicelulare au avut unele probleme în încercarea de a trece testele standard de inteligență. Având în vedere cât de puțină atenție este acordată amibelor de către cercetători, nu este surprinzător faptul că această descoperire a fost considerată în mod similar nesemnificativă.'*/,
        /*'O ceață hipnotică a atras sub vraja întregul echipaj al navei de explorare. Culorile și desenele ciudate par să interfereze cumva cu creierul uman, ceea ce a însemnat că, în loc să caute viața extraterestră, echipajul s-a preocupat în schimb să răspundă la întrebarea „*/'Extratereștrii mănâncă cu adevărat hotdogs verzi'/* ?” Inutil să mai spun că nu au găsit forme de viață noi.'*/,
        /*'În timp ce căuta viața extraterestră, nava de explorare a */'ajuns într-un vortex cosmic care a deteriorat grav carcasa'/* exterioară. Echipajul și nava au fost salvate de o manevră de zbor riscantă, dar au fost nevoiți să renunțe la explorare și să se întoarcă cu mâinile goale.'*/,
        /*'Nava de explorare a dat peste o */'stație spațială veche și abandonată, care a fost odată condusă'/* de niște specii necunoscute anterior. Cu toate acestea, după un studiu mai intens, a devenit curând clar că stația era doar o farsă elaborată de la o formă de viață dispărută. Echipajul a distrus mesajele derizorii, dar nu a putut descoperi altceva nimic.'*/,
        /*'Echipajul a dat peste o */'stație de cercetare de înaltă tehnologie, condusă de inteligență artificială'/* , pe o planetă singură și sălbatică. Din păcate, ușa stației era protejată prin parolă, iar inteligență artificială a refuzat să coopereze. Echipajul a petrecut zile întregi încercând să descifreze parola, iar proviziile începeau să scadă, când unul dintre membrii echipajului mai indiscret a dat peste combinație și a spart codul. Din păcate, stația s-a dovedit a fi o dezamăgire, iar inteligența artificială nu a fost altceva decât un sistem elaborat de management al casei. Echipajul a decis să se întoarcă acasă.'*/,
        /*'O */'eroare tehnică în modulul de navigare a adus nava de explorare periculos'/* de aproape de orizontul evenimentelor unei găuri negre. Echipajul a reușit să se întoarcă exact la timp, dar a ajuns să-și epuizeze rezervele de combustibil și, astfel, a trebuit să întrerupă căutarea de noi forme de viață fără succes.'*/,
        /*'Nava de explorare a raportat cu entuziasm că a */'întâlnit o navă identică dintr-un univers paralel'/* . Echipajul din această dimensiune avea chiar aceleași nume. Dar asemănările s-au oprit aici: la petrecerea de bun venit, oaspeții au fost atât de plictisitori, încât echipajul i-a alungat curând din universul nostru. Dezamăgit, dar în același timp ușurat, echipajul s-a întors acasă.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*TODO: ro 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
        /*'Echipajul navei de explorare a intrat cu succes în */'contact cu o specie extraterestră necunoscută anterior'/* . Primele impresii sugerau că erau binevoitori. Cu toate acestea, din rapoartele emisarului nostru, se pare că echipajul era din ce în ce mai euforic, motiv pentru care putem să presupunem că a fost supus unui fel de hipnoză. Raportul final pe care l-am primit a fost o proclamație fericită din partea întregului echipaj, ei ar prefera să rămână cu acești extratereștri prieteni. Nava și echipajul său au dispărut fără urmă.'*/,
        /*'În căutarea formelor de viață inteligente, nava s-a oprit pe o lună neexplorată anterior. Cel puțin, luna nu fusese niciodată raportată. Curând a devenit clar de ce. Echipajul a reușit să scape de un semnal de alarmă, dar era prea târziu. Treziți de sosirea navei, */'gigantici viermi de magmă au devorat nava și echipajul'/* său în câteva minute.'*/,
        /*'Nava de explorare a reușit să urmărească o specie extraterestră inteligentă, */'dar aceasta s-a dovedit a fi ostilă'/* . Judecând după ultimul semnal trimis de echipaj, s-ar părea că extratereștrii i-au luat prizonieri. Fiecare încercare ulterioară de a localiza nava și echipajul acesteia a eșuat.'*/,
        /*'Nava de explorare s-a oprit pe o planetă necunoscută în călătoria sa pentru a se aproviziona. Planeta era învăluită într-o ceață ciudată, pe care */'echipajul a reușit să o identifice rapid drept gaz dormit'/* . Dar, la o inspecție ulterioară, a devenit în curând evident că gazul era atât de puternic încât atât nava, cât și echipajul ei erau de nesalvat.'*/,
        /*'Echipajul acestei nave de explorare și-a câștigat deja o reputație ca o ținută oarecum neconformă, curajoși până la punctul de a exagera, motiv pentru care păreau a fi potrivirea perfectă pentru această misiune. Poate au crezut că ar */'putea zbura direct prin câmpul de asteroizi'/* ? Din păcate, va fi dificil să găsești răspunsuri din epava navei lor.'*/,
        /*'Se pare că nava de explorare s-a */'pierdut într-o singularitate necunoscută până acum'/* . Nu a mai fost niciun semn de viață din partea echipajului.'*/,
        /*'Flota de explorare a */'zburat într-o ambuscadă întinsă de o specie extraterestră beligerantă'/* . Ei au pulverizat complet nava de explorare înainte de a putea fi stabilit contactul iniția'*/,
        /*TODO: ro 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*'Navigatorul navei trebuie să fi fost atât de profund concentrat să urmărească semnalul ciudat, încât a pierdut din vedere */'faptul că aceștia operau lângă o gaură neagră'/* . Nava s-a apropiat prea mult de adâncurile gravitaționale și, în ciuda eforturilor depuse de echipaj, nimic nu a putut să-i împiedice să fie atrași înăuntru. Pentru a evita alte astfel de pierderi inutile, raportul sugerează ca în viitor alarmele automate pentru găuri negre să fie integrate ca standard.'*/,
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /a fost descoperită la coordonatele.+ și a fost adăugată la meniul Forme de viață/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Știam deja despre această formă de viață. Cu toate acestea, trimișii noștri au putut să ne îmbunătățească cunoștințele despre ei cu\s*(?<xp>\d+) XP/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*TODO: ro 'Das Erkundungsschiff hat zwar ein paar Artefakte gefunden, */'konnte sie aber nicht mitnehmen, da deine Lager voll sind',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'Nava de Explorare a găsit */'un mic număr de artefacte',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Nava de Explorare a găsit */'o mare cantitate de artefacte',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*'Nava de Explorare a găsit un */'tezaur uriaș de artefacte',
        },
        numberOfArtifacts: /Artefacte găsite:\s*(?<artifacts>\d+)/i,
    },
};