import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const si: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*LOCA: si 'Zu Beginn der Erkundung konnten einige */'vielversprechende Koordinaten aus einer geheimnisvollen Nachricht'/* entschlüsselt werden. Als das Erkundungsschiff jedoch den angegebenen Sektor erreichte, fand die Crew nur noch das riesige Trümmerfeld eines bewaffneten Konflikts vor. Die Suche nach Überlebenden blieb erfolglos.'*/,
        /*LOCA: si 'Ein */'magnetisches Asteroidenfeld störte ungünstigerweise die Scanner'/*. Was wie ein vielversprechendes Signal intelligenten außerirdischen Lebens aussah, war nur eine Störung der Messinstrumente und es konnte keine neue Lebensform gefunden werden.'*/,
        /*LOCA: si 'Gerade als das Erkundungsschiff einen vielversprechenden Funkspruch auffangen konnte, */'kam es zu einem Totalausfall sämtlicher Kommunikationssysteme'/*. Unter diesen Umständen war nicht nur jede Kontaktaufnahme mit eventuellen intelligenten Lebensformen ausgeschlossen, ein Fortführen der Mission wäre auch gefährlich gewesen. Deshalb kehrte die Crew enttäuscht, aber unversehrt zurück.'*/,
        /*LOCA: si 'In einem noch größtenteils unerforschten Planetensystem */'wurde ein kosmischer Nebel mit Bewusstsein entdeckt'/* ! Die intergalaktischen Botschafter gerieten in helle Aufregung, weshalb unter großer medialer Aufmerksamkeit eine Sonde entsandt wurde. Beim Kommunikationsversuch mit dem Nebel stellte sich aber schnell heraus, dass seine Intelligenz kaum über der von einfachen Insekten lag. Die Aufregung schwand und es wurde beschlossen, einen Mantel des Schweigens über die ganze Aktion zu breiten.'*/,
        /*LOCA: si 'Bei der Suche nach neuen Lebensformen folgte das Erkundungsschiff einigen mysteriösen Signalen, die */'von der Rückseite eines unbekannten Planeten zu stammen'/* schienen. Die intergalaktischen Botschafter an Bord hatten schon das Begrüßungspaket geholt und den Übersetzungscomputer aktiviert, doch es stellte sich heraus, dass das Signal von einem Schiffswrack stammt. Das Schiff ist eindeutig außerirdischer Herkunft, aber von den Piloten fehlt leider jede Spur. So konnte keine neue Lebensform entdeckt werden.'*/,
        /*LOCA: si 'Das Erkundungsschiff war einige Zeit unterwegs, bis sich herausstellte, dass sich ein */'fataler Bug in die Scan-Software eingeschlichen'/* hatte. So konnte leider keine neue Lebensform aufgespürt werden.'*/,
        /*LOCA: si 'Leider erwies sich die insektoide Alienspezies, die unsere */'intergalaktischen Botschafter wegen der außerordentlichen Sauberkeit'/* ihres Heimatplaneten zunächst für intelligent hielten, doch als eher einfach gestrickt. Nachdem sie den Inhalt der Bord-Müllpresse gefressen hatten, wurden sie deshalb wieder auf ihrem Planeten ausgesetzt, trotz eines Votums der Crew, doch ein paar Exemplare zu behalten.'*/,
        /*LOCA: si 'Vollkommen begeistert fanden die Forscher des Erkundungsschiffes */'ein neuronales Netzwerk mitten in einem Asteroidenfeld'/*. Die Enttäuschung war groß, als sich herausstellte, dass es sich lediglich um ein Cluster verfangener Nachrichten mit jahrhundertealten Sportergebnissen handelte, die das Eigenleben eines schlecht informierten Stammtisches entwickelt hatten. Die Crew kehrte niedergeschlagen und ohne signifikante Ergebnisse zurück.'*/,
        /*LOCA: si 'Die Crew des Erkundungsschiffes war hellauf begeistert, als */'Untersuchungen von Schimmelsporen intelligentes Leben versprachen'/*. Leider stellte sich heraus, dass ein Witzbold die Forschungsergebnisse manipuliert hatte, um einen rivalisierenden Forscher bloßzustellen. Die untersuchten Sporen waren in Wahrheit kein bisschen intelligenter als der durchschnittliche Schimmelpilz in der Bordküche. Der Unruhestifter wurde auf den nächstbesten Planeten beurlaubt und das Schiff kehrte ergebnislos zurück.'*/,
        /*LOCA: si 'Vielversprechende Signale führten das */'Erkundungsschiff zu einer mysteriösen goldenen Sphäre'/*, die einsam in den Tiefen des Weltalls schwebte. Trotz aller Bemühungen der intergalaktischen Botschafter an Bord konnte weder ein Eingang gefunden noch irgendwie Kontakt zu dem merkwürdigen Objekt hergestellt werden, bevor es sich mit einem Sprung davonmachte.'*/,
        /*LOCA: si 'Das Erkundungsschiff entdeckte auf einem unbekannten Planeten ein Pflanzensystem, das deutlich intelligenter als gewöhnlich erschien. Als die Crew es untersuchen wollte, wurden sie von */'mysteriösen Wachrobotern in Uniform aufgehalten'/*, die darauf hinwiesen, dass dies Privateigentum sei. Die Forscher gaben trotz Androhung intergalaktischer Gerichtsverfahren nicht auf und extrahierten in einer Nacht-und-Nebel-Aktion Proben, um sich dann schnell aus dem Staub zu machen. Offenbar war es zu dunkel und neblig, denn die gesicherten Funde stellten sich auf dem Schiff als gewöhnliche Zimmerpflanzen heraus.'*/,
        /*LOCA: si 'Bei der Suche nach außerirdischem intelligentem Leben irrte das Erkundungsschiff bereits seit Monaten durch die Galaxis, als sie */'endlich einen außerirdischen Verwandten des Pantoffeltierchens'/* fanden! Diese Lebensform war zwar nicht intelligent, aber aufgrund der langen Reise und blankliegender Nerven entschied die Crew, auch mit unintelligentem Leben vorlieb zu nehmen und ohne nennenswerte Funde zurückzukehren.'*/,
        /*LOCA: si 'Die vielversprechenden Signale, denen das Erkundungsschiff folgte, */'verloren sich leider in einem kosmischen Nebel'/*. Die Suche wurde noch eine Weile fortgesetzt, aber es konnten keine neuen Lebensformen entdeckt werden.'*/,
        /*LOCA: si 'Nach intensiver Suche fand die Crew des */'Erkundungsschiffes eine lumineszente Riesenamöbenart'/* ! Leider hatten die Amöben Schwierigkeiten bei der Bearbeitung des standardisierten Tests zur Identifikation außerirdischer Intelligenz. Deshalb und weil in Forscherkreisen Amöben leider immer noch verkannt werden, wurde diese Entdeckung als nicht relevant eingestuft.'*/,
        /*LOCA: si 'Ein hypnotischer Nebel zog die gesamte Crew des Erkundungsschiffes in seinen Bann. Die fremdartigen Farben und Muster scheinen auf ungünstige Weise mit dem menschlichen Gehirn zu interferieren, wodurch die Besatzung statt der Suche nach außerirdischem Leben der Beantwortung der Frage „*/'Essen Aliens eigentlich grüne Hotdogs'/*?“ nachging. Überflüssig zu erwähnen, dass sie keine neue Lebensform fanden.'*/,
        /*LOCA: si 'Bei der Suche nach außerirdischem Leben */'geriet das Erkundungsschiff in einen kosmischen Vortex'/*, der die Außenhülle schwer beschädigte. Durch ein riskantes Flugmanöver konnten Crew und Schiff gerettet werden, mussten jedoch die Erkundung aufgeben und ohne Ergebnisse zurückkehren.'*/,
        /*LOCA: si 'Das Erkundungsschiff stieß auf eine */'alte verlassene Raumstation, die von bisher unbekannten Lebewesen'/* bewohnt wurde. Nach eingehender Untersuchung musste man allerdings feststellen, dass es sich um den ausgeklügelten Scherz einer bereits ausgestorbenen Lebensform handelte. Die Crew zerstörte die hämischen Botschaften, konnte ansonsten aber nichts entdecken.'*/,
        /*LOCA: si 'Auf einem wilden Planeten */'entdeckte die Crew eine hochmoderne Forschungsstation'/*, die von einer künstlichen Intelligenz gesteuert und bewacht wurde. Die Tür zur Station war allerdings durch ein Passwort geschützt und die KI verweigerte die Kommunikation. Nachdem nach tagelangen Ratespielen die Vorräte knapp wurden, gelang es einem bisher eher unscheinbaren Mitglied der Crew, das Passworträtsel zu entschlüsseln. Im Inneren der Anlage stellte sich aber leider heraus, dass die KI nur ein elaboriertes Home-Management-System war und die Crew machte sich enttäuscht auf den Heimweg.'*/,
        /*LOCA: si 'Das Erkundungsschiff kam durch einen technischen Fehler im */'Navigationsmodul dem Ereignishorizont eines schwarzen Lochs bedrohlich nahe'/*. Die Crew konnte gerade noch abdrehen, verbrauchte dabei jedoch ihren Treibstoffvorrat und musste daher die Suche nach neuen Lebensformen erfolglos abbrechen.'*/,
        /*LOCA: si 'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
        /*LOCA: si 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*LOCA: si 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /*LOCA: si 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /*LOCA: si 'Das Erkundungsschiff schaffte es zwar, eine intelligente Alienspezies aufzuspüren, */'diese erwies sich jedoch als feindselig'/*. Dem letzten Funkspruch der Crew ist zu entnehmen, dass sie von den Außerirdischen als Gefangene abtransportiert wurden. Jeglicher Versuch, den weiteren Verbleib des Schiffes und seiner Besatzung aufzuklären, blieb leider erfolglos.'*/,
        /*LOCA: si 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /*LOCA: si 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /*LOCA: si 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /*LOCA: si 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*LOCA: si 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /*LOCA: si 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /*LOCA: si *//Bei den Koordinaten .+ wurde die Lebensform .+ gefunden und der Lebensformverwaltung hinzugefügt/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /*LOCA: si *//Dennoch konnten unsere Botschafter unser Wissen über sie um (?<xp>\d+) Erfahrung verbessern/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*LOCA: si 'The Exploration Ship has found some artefacts */'but cannot recover them as your storage is full',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*LOCA: si 'The Exploration Ship has */'found a small number of artefacts',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*LOCA: si 'The Exploration Ship has */'found a large quantity of artefacts',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*LOCA: si 'The Exploration Ship has */'found a huge quantity of artefacts',
        },
        numberOfArtifacts: /*LOCA: si *//Artefacts found: (?<artifacts>\d+)/i,
    },
};