import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const si: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Na začetku */'raziskovanja so lahko dešifrirali obetavne koordinate'/* , ki so jih dobili v skrivnostnem sporočilu. Ko pa je raziskovalna ladja prispela do omenjenih koordinat, je posadka našla le gigantsko polje razbitin, ki je ostalo po bitki. Iskanje preživelih je bilo neuspelo.'*/,
        'Magnetsko polje asteroida je motilo skenerje'/*. Kar je delovalo kot obetujoč signal inteligentne izvenzemljeskega življenja, je bila le motnja v meritvah intrumentov in novih življenjskih vrst ni bilo mogoče najti.'*/,
        /*'Ravno ko je raziskovalna ladja prejela obetaven radijski signal, */'so se vsi komunikacijski sistemi pokvarili'/* . Glede na okoliščine ni bilo mogoče vzpostaviti kontakta s potencialnimi inteligentnimi vrstami, obenem pa bi bilo nevarno nadaljevati z misijo. Posadka se je razočarana, a nepoškodovana, vrnila domov.'*/,
        /*'Meglica v */'obliki nekakšne zavesti je bila odkrita v večjem'/* , neodkritem delu našega sistema! Naši intergalaktični odposlanci so bili iz sebe in nastal je medijski cirkus, ko je bila sonda poslana v oblak. Poskusi komunikacije z meglico so pokazali, da je inteligenca enaka tisti od ščurka. Navdušenje je splahnelo in odločili so se, da vse tiho pometejo pod preprogo.'*/,
        /*'Med iskanjem novih življenjskih vrst je raziskovalna ladja sledila skrivnostnim signalom, */'ki so domenvno prihajali z oddaljenega neznanega planeta'/* . Intergalaktični odposlanci na krovu so že pripravili pozdravni paket in aktivirali prevajalski računalnik, izkazalo pa se je, da signal prihaja z razbitine ladje. Ladja je nedvomno nezemeljska, žal pa ni bilo znakov o posadki. To pomeni, da ni najdene nove življenjske vrste.'*/,
        /*'Raziskovalna ladja je bila na poti že nekaj časa, ko so izvedeli, da */'je hrošč v programski opremi za skeniranje'/* . To žal pomeni, da ni bilo mogoče najti nove življenjske vrste.'*/,
        /*'Naši */'intergalaktični odposlanci so obiskali planet z redko vrsto insektoidov'/* , saj so domnevali, da so inteligentni, a so bili nad odkritjem razočarani. Po opazovanju, kako jejo vsebino stiskalnika ladijskih smeti, so se odločili za vrnitev na njihov planet, čeprav so nekateri člani posadke predlagali, da jih nekaj obdržijo.'*/,
        /*'Raziskovalci na krovu raziskovalne ladje so */'bili ekstatični zaradi odkritja nevralne mreže sdeli polja asteroidov'/* . Zato so bili močno razočarani, ko se je izkazalo, da je bil to le skupek prestreženih novinarskih poročil o stoletja starih športnih rezultatih, ki je razvil svoje življenje in nekakšne kavčne strokovnjake. Posadka se je vrnila poklapana, ni se naučila ničesar bolj pomembnega od tega, kdo je osvojil pepel in podobno.'*/,
        /*'Posadka raziskovalne ladje je bila na luni, */'ko so testi spor pokazali inteligentno življenje'/* . Žal se je izkazalo, da je šaljivec manipuliral s testom, da bi osramotil rivalskega raziskovalca. Spore niso bile nič drugega kot tiste, najdene za mikrovalovno pečico v galeji. Zdrahar je bil suspendiran in odložili so ga na najbližjem planetu, potem pa se je ladja vrnila domov.'*/,
        /*'Obetavni signali so vodili raziskovalno ladjo v skrivnostno zlato sfero, */'ki je sama lebdela v globinah vesolja'/* . Kljub vsem naporom intergalaktičnih odposlancev na krovu, niso mogli najti vhoda ali ustvariti stika s čudnim predmetom, preden je nenadoma odskočil.'*/,
        /*'Na neraziskanem planetu je raziskovalna ladja našla floralni sistem , ki je bil bolj inteligenten, kot se je sprva zdelo. Ko je posadka skušala preiskovati, so se */'pojavili čudni uniformirani stražni roboti in jih posvarili'/* , da so rastline zasebna lastnina. Raziskovalci so ignorirali morebitne težave pri kršenju intergalaktičnih zakonov in ukradli nekaj vzorcev med prikrito operacijo v zavetju teme, potem pa so se umaknili v orbito. Žal je bila operacija preveč PRIKRITA za nekaj znanstvenikov in na krovu so odkrili, da so zbrani vzorci le navadne hišne rastline.'*/,
        /*'Pri iskanju nezemeljske inteligence je raziskovalna ladja brezplodno porabila mesece v galaksiji, */'ko so končno odkrili vesoljca, enakega parameciju'/* ! Ni ustrezal kriterijem inteligentnega življenja, a po monotonih mesecih iskanja se je posadka odločila, da je to odkritje neuspeh in se je vrnila domov brez obetavnih novic.'*/,
        /*'Ti obetavni signali, ki jih je zaznala raziskovalna ladja, */'so se žal izgubili v kozmični megli'/* . Nekaj časa so še nadaljevali z iskanjem, a niso mogli najti novih življenjskih vrst.'*/,
        /*'Po intenzivnem iskanju je posadka */'raziskovalne ladje odkrila luminescenčno vrsto velike amebe'/* ! Žal je imel enocelični organizem težave pri prestajanju inteligenčnih testov. Glede na to, kako malo pozornosti je imela ameba, je bilo presenečenje, da je bilo to odkritje označeno kot nepomembno.'*/,
        /*'Hipnotična megla je uročila celotno posadko in raziskovalno ladjo. Čudne barve in dizajni so se poigrali s človeškimi možgani, zato posadka ni iskala izvenzemeljskega življenja, ampak se je spraševala vprašanje ‘*/'Ali vesoljci res jejo zelene hot doge'/* ?’ Ni potrebno omenjati, da niso našli novih življenjskih vrst.'*/,
        /*'Med iskanje izvenzemeljskega */'življenja je raziskovalna ladja padla v kozmični vrtinec'/* , ki je močno poškodoval zunanji del trupa. Posadka in ladja so se rešili s tveganim manevrom, morali pa so se odreči raziskovanju in so se vrnili praznih rok.'*/,
        /*'Raziskovalna ladja */'je naletela na staro in zapuščeno vesoljsko postajo'/* , ki je bila včasih naseljena z prej neznano vrsto. Po bolj natančem preučevanju je kmalu postalo jasno, da je postaja potegavščina izumrle življenjske vrste. Posadka je uničila porogljiva sporočila, a ni mogla odkriti nič drugega.'*/,
        /*'Posadka je naletela na */'visokotehnološko AI raziskovalno postajo na samotnem in divjem'/* planetu. Žal so bila vrata posatje zaščitena z geslom in AI ni želela sodelovati. Posadka se je več dni trudila dešifrirati geslo in zaloge so začele pohajati, ko je en član posadke uganil kombinacijo in ugotovil šifro. Žal je bila postaja razočaranje in AI ni bila nič več kot domači sistem nadzora. Posadka se je odločila za vrnitev domov.'*/,
        /*'Tehnična napaka navigacijskega */'modula je pripeljala raziskovalno ladjo nevarno blizu horizontu črne luknje'/* . Posadka je uspela v zadnjem trenutku obrniti ladjo, a je to izsušilo zalogo goriva, zaradi česar so morali prekiniti iskanje novih življenjskih vrst.'*/,
        /*'Raziskovalna ladja je navdušena poročala, da so */'naleteli na identično ladjo iz paralelnega vesolja'/* . Posadka iz te dimenzije je imela celo enaka imena. Tu pa se podobnosti končajo: na zabavi dobrodošlice so bili gostje tako neoteasni, da jih je posadka kmalu izključila iz našega vesolja. Posadka se je razočarana, a nepoškodovana, vrnila domov.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /*'Posadka raziskovalne ladje je blodila, */'sčasoma pa je nastopila tišina'/* . Člani posadke, ki so obtičali, so bili locirani in rešeni, a poročajo, da so uporniki prevzeli nadzor nad ladjo in se pridružili skupini vesoljskih piratov. Kot rezultat tega dogodka, morajo vse posadke ladij zdaj vsako četrtletje opraviti seminarje in team building.'*/,
        /*'Posadka raziskovalne ladje je */'uspešno vzpostavila kontakt s prej neznano vesoljsko vrsto'/* . Prvi vtis je, da so neškodljivi. Poročila naših odposlancev in posadke pa kažejo, da so postali močno evforični, zato domnevamo, da so bili izpostavljeni nekakšni hipnozi. Zadnje prejeto poročilo je bilo vesel razglas v imenu celotne posadke, da bodo raje ostali s temi prijateljskimi vesoljci. Ladja in posadka so izginili brez sledu.'*/,
        /*'Pri iskanju inteligentnih življenjskih vrst se je ladja ustavila na prej neraziskani luni. O tej luni se še do zdaj ni poročalo. Kmalu je postalo jasno, zakaj. Posadka je uspela poslati klic v sili, a je bilo do takrat že prepozno. Ko so uvideli prihod ladje, so */'gigantski magma črvi pogoltnili ladjo s posadko'/* v nekaj minutah.'*/,
        /*'Raziskovalna */'ladja je uspela izslediti inteligentno vrsto'/* , a se je izkazalo, da so sovražni. Glede na zadnji signal posadke, deluje, da so jih vesoljci vzeli za ujetnike. Vsak nadaljnji poskus kontakta z ladjo ali posadko je spodletel.'*/,
        /*'Raziskovalna ladja se je ustavila zaradi obnove zalog na neznanem planetu. Planet je bil ovit v čudno meglo, */'ki jo je posadka hitro prepoznala kot uspavalni plin'/* . Po nadaljnjem pregledu je postalo jasno, da je bil plin tako močen, da ladje in posadke ni več mogoče rešiti.'*/,
        /*'Posadka te raziskovalne ladje si je že zaslužila ugled posebnežev, poguminih do mere, da so že nepremišljeni, za kar so delovali popolni za to misijo. Morda so mislili, */'da lahko letijo naravnost skozi polje asteroidov'/* ? Žal bo težko dobiti odgovore iz razbitin njihove ladje.'*/,
        /*'Zgleda, da je */'raziskovalna ladja izgubljena v do zdaj neznano edinstvenost'/* . Od takrat ni znakov o življenju posadke.'*/,
        /*'Raziskovalna flota je priletela v zasedo, */'ki so jo postavile agresivne vesoljske vrste'/* . Raziskovalno ladjo so dobesedno zmleli, preden bi lahko vzpostavili kontakt.'*/,
        /*'Raziskovalna ladja je zaznala obetavne signale. Po sledenju viru signala, je ta nenadoma prenehal z oddajanjem. Iskalne ekipe so bile poslane, */'a niso našle sledi lokacije ladje'/* . Verjetno je izgubljena v praznini.'*/,
        /*'Navigator na ladji je moral biti tako skoncentriran na slednje tujemu signalu, ad je spregledal dejstvo, */'da so se nahajali blizu črne luknje'/* . Ladja se je znašla preblizu vodnjaku gravitacije in kljub naporom posadke ni bilo mogoče storiti ničesar, da jih ne bi potegnilo noter. Da bi se izognili več nepotrebnim izgubam, poročilo predlaga, da se v prihodnosti vgradijo samodejni alarmi za črno luknjo.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /je bila odkrita na koordinatah .+ in je bila dodana v meni Življenjskih vrst./i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Naši odposlanci so lahko vseeno izboljšali znanje o njih za (?<xp>\d+) XP/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*'Raziskovalna ladja je našla nekaj artefaktov, */'a jih ne more pobrati zaradi polnega skladišča.',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'Raziskovalna ladja */'je našla majhno število artefaktov',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Raziskovalna ladja */'je našla veliko količino artefaktov',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*LOCA: si 'The Exploration Ship has'found a huge quantity of artefacts'*/'------------------------------------------------------------------------------------------------------------------------------',
        },
        numberOfArtifacts: /Najdeni artefakti: (?<artifacts>\d+)/i,
    },
};