import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const tr: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /*'Keşfin başında, gizemli */'bir mesajdaki umut verici bazı koordinatlar deşifre edilebildi'/* . Ancak keşif gemisi belirtilen sektöre ulaştığında, mürettebat yalnızca silahlı bir çatışmanın devasa enkaz yığınını buldu. Hayatta kalanları bulmak için yapılan arama başarısız oldu.'*/,
        'Manyetik bir asteroit alanı maalesef tarayıcıları bozuyordu'/* . Akıllı, dünya dışı yaşamın umut veren bir sinyali gibi görünen, aslında yalnızca ölçüm aletlerindeki bir arızaydı ve yeni bir canlı türü bulunamadı.'*/,
        /*'Keşif gemisi tam umut verici bir */'telsiz mesajı yakaladığı sırada tüm iletişimleri komple devre dışı kaldı'/* . Bu şartlar altında yalnızca olası zeki canlı türleriyle iletişim kurmak imkansız hale gelmiyordu, aynı zamanda göreve devam etmek de tehlikeli olacaktı. Bu nedenle mürettebat hayal kırıklığına uğramış halde ama zarar görmeden geri döndü.'*/,
        /*'Henüz büyük oranda */'araştırılmamış bir gezegen sisteminde bilinçli bir kozmik sis keşfedildi'/* ! Galaksiler arası elçiler büyük bir heyecana kapıldı, bu nedenle büyük medya ilgisi altında bir sonda gönderildi. Ancak sisle iletişim kurma denemesinde kısa sürede zekasının basit böceklerin çok üzerinde olmadığı anlaşıldı. Heyecan kayboldu ve tüm bu operasyonun üzerine bir sünger çekilmesine karar verildi.'*/,
        /*'Keşif gemisi yeni canlı türü arayışı sırasında, */'bilinmeyen bir gezegenin arkasından gelen bir takım gizemli sinyalleri'/* takip etti. Gemideki galaksiler arası elçiler selamlama paketini almış ve çeviri bilgisayarını etkinleştirmişti bile ama sinyalin bir gemi enkazından geldiği anlaşıldı. Geminin dünya dışı kökenli olduğu açık ama pilottan hiçbir iz yok. Bu nedenle yeni canlı türleri keşfedilemedi.'*/,
        /*'Tarama yazılımına ciddi bir arıza sızdığı */'ortaya çıkana kadar keşif gemisi epeyce yol almıştı'/* . Bu nedenle maalesef yeni canlı türü bulunamadı.'*/,
        /*'Galaksiler arası */'elçimizin Böcektoidleri anayurtları olan gezegenin olağanüstü'/* temizliğinden yola çıkarak akıllı zannetse de sonrasında biraz alık oldukları ortaya çıktı. Gemideki çöp değirmeninin içindekileri yedikten sonra mürettebatın yine de birkaç örneği saklama görüşü reddedilerek gezegenlerine bırakıldılar.'*/,
        /*'Keşif gemisinin araştırmacıları büyük bir hayranlıkla, bir */'asteroit alanının ortasında bir nöron ağı buldu'/* . Bunun yüzlerce yıllık spor sonuçlarını içeren, iç içe geçmiş haberlerden oluşan ve kötü bilgilendirilmiş bir içki masasının bağımsız yaşamını geliştirmiş bir yığından oluştuğu ortaya çıktığında büyük bir hayal kırıklığı yaşandı. Mürettebat üzgün ve kayda değer sonuçlar olmadan geri döndü.'*/,
        /*'Küf */'sporlarının araştırması akıllı yaşam vaat ettiğinde'/* Keşif Gemisinin mürettebatı büyük bir sevinç yaşadı. Maalesef bir soytarının, rakip bir araştırmacıyı zor duruma düşürmek için araştırma sonuçlarını manipüle ettiği ortaya çıktı. Araştırılan sporlar gerçekte gemi mutfağındaki küf mantarlarından birazcık bile daha akıllı değildi. Bozguncu en yakın gezegende işten çıkarıldı ve gemi sonuç alamadan geri döndü.'*/,
        /*'Umut veren sinyaller keşif gemisini, */'uzayın derinliklerinde tek başına süzülen, gizemli'/* , altın bir küreye götürdü. Gemideki galaksiler arası elçilerin tüm çabalarına rağmen, bir sıçramayla ortadan kaybolmadan önce ne bir giriş bulunabildi, ne de bu tuhaf cisimle herhangi bir iletişim kurulabildi.'*/,
        /*'Keşif Gemisi bilinmeyen bir gezegende, normalden belirgin bir şekilde daha zeki görünen bir bitki sistemi keşfetti. Mürettebat sistemi araştırmak istediğinde, buranın özel mülk olduğuna işaret eden, */'üniformalı bekçi robotlar durduruldular'/* . Araştırmacılar galaksiler arası mahkeme davası tehdidine rağmen pes etmedi ve karanlık ve puslu bir operasyonla numuneler çıkardı ve ardından hızla ortadan kayboldu. Anlaşılan ortam fazla karanlık ve pusluydu, çünkü gemide, elde edilen bulguların sıradan süs bitkileri olduğu anlaşıldı.'*/,
        /*'Dünya dışı akıllı yaşam arayışında Keşif Gemisi nihayet terliksi hayvanın dünya dışı bir */'akrabasına rastlamadan önce aylarca galakside yol almıştı'/* . Gerçi bu canlı türleri akıllı değildi ama uzun yolculuk ve yıpranan sinirler yüzünden mürettebat akıllı olmayan canlıları da tercih etmeye ve kayda değer bulgular olmadan da geri dönmeye karar verdi.'*/,
        /*'Keşif gemisinin takip ettiği umut veren */'sinyaller maalesef kozmik bir sisin içinde kayboldu'/* . Aramaya bir süre daha devam edildi ama yeni canlı türleri keşfedilemedi.'*/,
        /*'Yoğun bir aramadan sonra Keşif Gemisinin */'mürettebatı ışık yayan dev bir amip türü buldu'/* ! Maalesef amipler dünya dışı zekanın tanımlanması amaçlı standart testi yapmakta zorlandı. Bu nedenle ve araştırma çevrelerinde amipler maalesef hala önemsenmediği için bu keşif önemsiz olarak sınıflandırıldı.'*/,
        /*'Hipnotik bir sis keşif gemisinin tüm mürettebatını etkisi altına aldı. Yabancı renkler ve desenler İnsan beyniyle uygunsuz bir şekilde etkileşime geçiyor gibi görünüyor, bu nedenle mürettebat dünya dışı yaşam araması yerine "*/'Acaba uzaylılar yeşil sosisliler mi yiyor?'/* " sorusunun peşinden gitti. Yeni canlı türü bulamadıklarını söylemeye gerek yok.'*/,
        /*'Dünya dışı yaşam araması */'sırasında keşif gemisi, dış gövdeye ağır hasar veren'/* , kozmik bir girdaba yakalandı. Mürettebat ve gemi riskli bir uçuş manevrasıyla kurtarılabildi, ancak keşiften vazgeçmek ve sonuç alamadan geri dönmek zorunda kaldı.'*/,
        /*'Keşif Gemisi, */'içinde şimdiye kadar bilinmeyen canlıların yaşadığı eski'/* , terk edilmiş bir uzay istasyonuna rastladı. Ancak ayrıntılı bir araştırmadan sonra bunun soyu tükenmiş bir canlı türünün pişkince bir şakası olduğu anlaşıldı. Mürettebat neşeli mesajları imha etti ama bunun dışında başka bir şey bulamadı.'*/,
        /*'Mürettebat yapay zeka tarafından yönetilen ve gözlem */'altında tutulan vahşi bir gezegende çok modern bir araştırma istasyonu keşfetti'/* . Ancak istasyona açılan kapı bir şifreyle korunuyordu ve YZ iletişim kurmayı reddediyordu. Günler süren bir bilmece oyunundan sonra stoklar azaldıkça o güne dek mürettebatın pek de göze çarpmayan bir üyesi şifreyi çözmeyi başardı. Ancak tesisin içine girdiklerinde YZ’nin sadece detaylandırılmış bir ev yönetim sistemi olduğu ortaya çıktı mürettebat hayal kırıklığıyla eve dönüş yoluna koyuldu.'*/,
        /*'Keşif gemisi navigasyon modülündeki teknik bir */'arıza nedeniyle bir kara deliğin olay ufkuna tehlikeli derecede yaklaştı'/* . Mürettebat son anda yön değiştirebildi, ancak bu sırada yakıt stokunu tüketti ve bu nedenle yeni canlı türü aramasını başarısız bir şekilde iptal etmek zorunda kaldı.'*/,
        /* TODO tr 'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
        /* match unbekannt, später checken!'Keşif gemisi umut */'vadeden sinyaller takip ederken bir uzay korsanının tuzağına düştü'/* . Mürettebat kahramanca bu tehdide karşı mücadele etti ancak korsanlar çok iyi organize olmuştu ve firar şansı pek görünmüyordu. Neyse ki tam zamanında mürettebatı destekleyen uzaylı bir filo yetişti. Böylece korsanlar defedildi. Bu uzaylıları tanıyoruz ancak geminin köprü üstündeki kutlama yine de harikaydı.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /* TODO tr 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
        /* TODO tr 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /* TODO tr 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /* TODO tr 'Das Erkundungsschiff schaffte es zwar, eine intelligente Alienspezies aufzuspüren, */'diese erwies sich jedoch als feindselig'/*. Dem letzten Funkspruch der Crew ist zu entnehmen, dass sie von den Außerirdischen als Gefangene abtransportiert wurden. Jeglicher Versuch, den weiteren Verbleib des Schiffes und seiner Besatzung aufzuklären, blieb leider erfolglos.'*/,
        /*'Keşif gemisi yolculuğu sırasında bilinmeyen bir gezegende stoklarını doldurmak için durdu. Gezegen */'mürettebatın uyku gazı olduğunu tespit edebildiği gizemli bir sisle sarılıydı'/* . Durum daha ayrıntılı şekilde incelendiğinde gazın fazlasıyla güçlü olduğu ortaya çıktı ve ne mürettebat ne de gemi kurtarılamadı.'*/,
        /*'Bu keşif gemisinin mürettebatı atılgan hamleleriyle meşhurdu, tüm filolar tarafından ne kadar korkusuz olduğu bilinirdi ve bu misyon için en doğru seçimdi. Büyük */'olasılıkla tam da bu nedenle asteroid alanının tam ortasından'/* uçabileceklerini düşündüler. Ne yazık ki bu hamle biraz fazla gözü karaydı ve gemiden geri kalan sadece enkaz oldu.'*/,
        /* TODO tr 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /* TODO tr 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /*'Keşif gemisi büyük umutlar vaat eden sinyaller aldı. Coşkuyla bu enerjik izleri takip */'ederken birden bağlantı koptu ve tekrar sağlanamadı'/* . Gönderilen arama birlikleri gemiye dair hiçbir iz bulamadı. Büyük ihtimalle uzayın sonsuz derinliğinde kayboldu.'*/,
        /* TODO tr 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /.+ koordinatlarında canlı türü .+bulundu ve canlı türü yönetimi eklendi/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Buna rağmen elçilerimiz bunlar hakkındaki bilgilerimizi (?<xp>\d+) tecrübeyle geliştirebildi/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /*'Keşif */'gemisi birkaç eser buldu ama depoların dolu olduğu'/* için onları alamadı.'*/,
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'Keşif */'gemisi birkaç eser buldu',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Keşif */'gemisi büyük miktarda eser buldu',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /*'Keşif */'gemisi devasa bir eser koleksiyonu buldu!',
        },
        numberOfArtifacts: /Bulunan eserler: (?<artifacts>\d+)/i,
    },
};