import { LifeformDiscoveryEventArtifactFindingSize } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventArtifactFindingSize";
import { LifeformDiscoveryEventType } from "@/shared/models/lifeform-discoveries/LifeformDiscoveryEventType";
import { LifeformDiscoveryMessages } from "./types";

export const tr: LifeformDiscoveryMessages = {
    [LifeformDiscoveryEventType.nothing]: [
        /* TODO tr 'Zu Beginn der Erkundung konnten einige */'vielversprechende Koordinaten aus einer geheimnisvollen Nachricht'/* entschlüsselt werden. Als das Erkundungsschiff jedoch den angegebenen Sektor erreichte, fand die Crew nur noch das riesige Trümmerfeld eines bewaffneten Konflikts vor. Die Suche nach Überlebenden blieb erfolglos.'*/,
        'Manyetik bir asteroit alanı maalesef tarayıcıları bozuyordu'/* . Akıllı, dünya dışı yaşamın umut veren bir sinyali gibi görünen, aslında yalnızca ölçüm aletlerindeki bir arızaydı ve yeni bir canlı türü bulunamadı.'*/,
        /*'Keşif gemisi tam umut verici bir */'telsiz mesajı yakaladığı sırada tüm iletişimleri komple devre dışı kaldı'/* . Bu şartlar altında yalnızca olası zeki canlı türleriyle iletişim kurmak imkansız hale gelmiyordu, aynı zamanda göreve devam etmek de tehlikeli olacaktı. Bu nedenle mürettebat hayal kırıklığına uğramış halde ama zarar görmeden geri döndü.'*/,
        /* TODO tr 'In einem noch größtenteils unerforschten Planetensystem */'wurde ein kosmischer Nebel mit Bewusstsein entdeckt'/* ! Die intergalaktischen Botschafter gerieten in helle Aufregung, weshalb unter großer medialer Aufmerksamkeit eine Sonde entsandt wurde. Beim Kommunikationsversuch mit dem Nebel stellte sich aber schnell heraus, dass seine Intelligenz kaum über der von einfachen Insekten lag. Die Aufregung schwand und es wurde beschlossen, einen Mantel des Schweigens über die ganze Aktion zu breiten.'*/,
        /* TODO tr 'Bei der Suche nach neuen Lebensformen folgte das Erkundungsschiff einigen mysteriösen Signalen, die */'von der Rückseite eines unbekannten Planeten zu stammen'/* schienen. Die intergalaktischen Botschafter an Bord hatten schon das Begrüßungspaket geholt und den Übersetzungscomputer aktiviert, doch es stellte sich heraus, dass das Signal von einem Schiffswrack stammt. Das Schiff ist eindeutig außerirdischer Herkunft, aber von den Piloten fehlt leider jede Spur. So konnte keine neue Lebensform entdeckt werden.'*/,
        /* TODO tr 'Das Erkundungsschiff war einige Zeit unterwegs, bis sich herausstellte, dass sich ein */'fataler Bug in die Scan-Software eingeschlichen'/* hatte. So konnte leider keine neue Lebensform aufgespürt werden.'*/,
        /* TODO tr 'Leider erwies sich die insektoide Alienspezies, die unsere */'intergalaktischen Botschafter wegen der außerordentlichen Sauberkeit'/* ihres Heimatplaneten zunächst für intelligent hielten, doch als eher einfach gestrickt. Nachdem sie den Inhalt der Bord-Müllpresse gefressen hatten, wurden sie deshalb wieder auf ihrem Planeten ausgesetzt, trotz eines Votums der Crew, doch ein paar Exemplare zu behalten.'*/,
        /* TODO tr 'Vollkommen begeistert fanden die Forscher des Erkundungsschiffes */'ein neuronales Netzwerk mitten in einem Asteroidenfeld'/*. Die Enttäuschung war groß, als sich herausstellte, dass es sich lediglich um ein Cluster verfangener Nachrichten mit jahrhundertealten Sportergebnissen handelte, die das Eigenleben eines schlecht informierten Stammtisches entwickelt hatten. Die Crew kehrte niedergeschlagen und ohne signifikante Ergebnisse zurück.'*/,
        /*'Küf */'sporlarının araştırması akıllı yaşam vaat ettiğinde'/* Keşif Gemisinin mürettebatı büyük bir sevinç yaşadı. Maalesef bir soytarının, rakip bir araştırmacıyı zor duruma düşürmek için araştırma sonuçlarını manipüle ettiği ortaya çıktı. Araştırılan sporlar gerçekte gemi mutfağındaki küf mantarlarından birazcık bile daha akıllı değildi. Bozguncu en yakın gezegende işten çıkarıldı ve gemi sonuç alamadan geri döndü.'*/,
        /*'Umut veren sinyaller keşif gemisini, */'uzayın derinliklerinde tek başına süzülen, gizemli'/* , altın bir küreye götürdü. Gemideki galaksiler arası elçilerin tüm çabalarına rağmen, bir sıçramayla ortadan kaybolmadan önce ne bir giriş bulunabildi, ne de bu tuhaf cisimle herhangi bir iletişim kurulabildi.'*/,
        /*'Keşif Gemisi bilinmeyen bir gezegende, normalden belirgin bir şekilde daha zeki görünen bir bitki sistemi keşfetti. Mürettebat sistemi araştırmak istediğinde, buranın özel mülk olduğuna işaret eden, */'üniformalı bekçi robotlar durduruldular'/* . Araştırmacılar galaksiler arası mahkeme davası tehdidine rağmen pes etmedi ve karanlık ve puslu bir operasyonla numuneler çıkardı ve ardından hızla ortadan kayboldu. Anlaşılan ortam fazla karanlık ve pusluydu, çünkü gemide, elde edilen bulguların sıradan süs bitkileri olduğu anlaşıldı.'*/,
        /*'Dünya dışı akıllı yaşam arayışında Keşif Gemisi nihayet terliksi hayvanın dünya dışı bir */'akrabasına rastlamadan önce aylarca galakside yol almıştı'/* . Gerçi bu canlı türleri akıllı değildi ama uzun yolculuk ve yıpranan sinirler yüzünden mürettebat akıllı olmayan canlıları da tercih etmeye ve kayda değer bulgular olmadan da geri dönmeye karar verdi.'*/,
        /*'Keşif gemisinin takip ettiği umut veren */'sinyaller maalesef kozmik bir sisin içinde kayboldu'/* . Aramaya bir süre daha devam edildi ama yeni canlı türleri keşfedilemedi.'*/,
        /* TODO tr 'Nach intensiver Suche fand die Crew des */'Erkundungsschiffes eine lumineszente Riesenamöbenart'/* ! Leider hatten die Amöben Schwierigkeiten bei der Bearbeitung des standardisierten Tests zur Identifikation außerirdischer Intelligenz. Deshalb und weil in Forscherkreisen Amöben leider immer noch verkannt werden, wurde diese Entdeckung als nicht relevant eingestuft.'*/,
        /*'Hipnotik bir sis keşif gemisinin tüm mürettebatını etkisi altına aldı. Yabancı renkler ve desenler İnsan beyniyle uygunsuz bir şekilde etkileşime geçiyor gibi görünüyor, bu nedenle mürettebat dünya dışı yaşam araması yerine "*/'Acaba uzaylılar yeşil sosisliler mi yiyor?'/* " sorusunun peşinden gitti. Yeni canlı türü bulamadıklarını söylemeye gerek yok.'*/,
        /* TODO tr 'Bei der Suche nach außerirdischem Leben */'geriet das Erkundungsschiff in einen kosmischen Vortex'/*, der die Außenhülle schwer beschädigte. Durch ein riskantes Flugmanöver konnten Crew und Schiff gerettet werden, mussten jedoch die Erkundung aufgeben und ohne Ergebnisse zurückkehren.'*/,
        /* TODO tr 'Das Erkundungsschiff stieß auf eine */'alte verlassene Raumstation, die von bisher unbekannten Lebewesen'/* bewohnt wurde. Nach eingehender Untersuchung musste man allerdings feststellen, dass es sich um den ausgeklügelten Scherz einer bereits ausgestorbenen Lebensform handelte. Die Crew zerstörte die hämischen Botschaften, konnte ansonsten aber nichts entdecken.'*/,
        /* TODO tr 'Auf einem wilden Planeten */'entdeckte die Crew eine hochmoderne Forschungsstation'/*, die von einer künstlichen Intelligenz gesteuert und bewacht wurde. Die Tür zur Station war allerdings durch ein Passwort geschützt und die KI verweigerte die Kommunikation. Nachdem nach tagelangen Ratespielen die Vorräte knapp wurden, gelang es einem bisher eher unscheinbaren Mitglied der Crew, das Passworträtsel zu entschlüsseln. Im Inneren der Anlage stellte sich aber leider heraus, dass die KI nur ein elaboriertes Home-Management-System war und die Crew machte sich enttäuscht auf den Heimweg.'*/,
        /*'Keşif gemisi navigasyon modülündeki teknik bir */'arıza nedeniyle bir kara deliğin olay ufkuna tehlikeli derecede yaklaştı'/* . Mürettebat son anda yön değiştirebildi, ancak bu sırada yakıt stokunu tüketti ve bu nedenle yeni canlı türü aramasını başarısız bir şekilde iptal etmek zorunda kaldı.'*/,
        /* TODO tr 'Das Erkundungsschiff meldete voller Aufregung, dass die Crew auf ein */'baugleiches Erkundungsschiff aus einem Spiegeluniversum'/* gestoßen war. Überraschenderweise hatte die Crew aus der anderen Dimension sogar die gleichen Vornamen. Doch dabei blieb es mit den Ähnlichkeiten, denn die Gäste aus der anderen Welt führten sich bei kurzfristig anberaumten Begrüßungsparty dermaßen rüpelhaft auf, dass man sie des Universums verwies. Enttäuscht, aber auch irgendwie erleichtert, kehrte die Crew unseres Erkundungsschiffes wieder zurück.'*/,
        /* match unbekannt, später checken!'Keşif gemisi umut */'vadeden sinyaller takip ederken bir uzay korsanının tuzağına düştü'/* . Mürettebat kahramanca bu tehdide karşı mücadele etti ancak korsanlar çok iyi organize olmuştu ve firar şansı pek görünmüyordu. Neyse ki tam zamanında mürettebatı destekleyen uzaylı bir filo yetişti. Böylece korsanlar defedildi. Bu uzaylıları tanıyoruz ancak geminin köprü üstündeki kutlama yine de harikaydı.'*/,
    ],
    [LifeformDiscoveryEventType.lostShip]: [
        /* TODO tr 'Die Crew des Erkundungsschiffes war erheblichen inneren Konflikten ausgesetzt, */'die schließlich zu einer Meuterei führten'/*. Die ausgesetzten Crewmitglieder konnten gefunden und geborgen werden, sie berichteten jedoch, dass die Gegenseite das Schiff übernommen und sich einer Bande von Raumpiraten angeschlossen hat. Als Konsequenz dieses Vorfalls wurden nun für alle Schiffsbesatzungen vierteljährliche Teambuilding-Seminare verordnet.'*/,
        /* TODO tr 'Die Crew des Erkundungsschiffs schaffte es, */'Kontakt zu einer bisher unbekannten außerirdischen Spezies'/* aufzunehmen, die sich auf den ersten Blick als freundlich herauszustellen schien. Die Nachrichten unserer Botschafter und der Crew wurden jedoch schnell unmäßig euphorisch, weshalb wir davon ausgehen müssen, dass sie unter einen hypnotischen Einfluss geraten waren. Ihr letztes Lebenszeichen war die freudige Ankündigung der gesamten Crew, dass sie dauerhaft bei den freundlichen Aliens bleiben würden. Schiff und Besatzung sind seitdem verschollen.'*/,
        /* TODO tr 'Bei der Suche nach intelligenten Lebensformen legte das Schiff auf einem bisher unerforschten Mond eine Zwischenlandung ein. Es stellte sich schnell heraus, warum bisher niemand über ihn berichtete. Der Crew gelang es noch, einen Hilferuf auszusenden, aber leider zu spät. Die vom Landemanöver */'aufgescheuchten riesigen Magmawürmer verschlangen das Schiff'/* und seine gesamte Besatzung innerhalb von Minuten.'*/,
        /* TODO tr 'Das Erkundungsschiff schaffte es zwar, eine intelligente Alienspezies aufzuspüren, */'diese erwies sich jedoch als feindselig'/*. Dem letzten Funkspruch der Crew ist zu entnehmen, dass sie von den Außerirdischen als Gefangene abtransportiert wurden. Jeglicher Versuch, den weiteren Verbleib des Schiffes und seiner Besatzung aufzuklären, blieb leider erfolglos.'*/,
        /* TODO tr 'Das Erkundungsschiff hielt auf seiner Reise auf einem unbekannten Planeten, um seine Vorräte aufzustocken. Der Planet war von einem mysteriösen Nebel eingehüllt, den */'die Crew aus erster Hand als Schlafgas identifizieren'/* konnte. Dieser stellte sich bei näherer Nachforschung als so stark heraus, dass sowohl die Crew als auch das Schiff nicht geborgen werden konnten.'*/,
        /* TODO tr 'Die Crew dieses Erkundungsschiffes war schon immer für waghalsige Manöver bekannt und galt in der gesamten Flotte als vollkommen unerschrocken, weshalb sie für diese Mission wie die perfekte Besatzung erschien. Vermutlich waren sie deshalb der Meinung, */'dass sie das Asteroidenfeld direkt durchfliegen können'/*. Leider stellte sich dies als etwas zu tollkühn heraus und von ihrem Schiff blieben nur noch Trümmer übrig.'*/,
        /* TODO tr 'Es scheint, als wäre das */'Erkundungsschiff in einer bis dahin unbekannten Singularität'/* verloren gegangen. Es konnten keine Lebenszeichen der Crew mehr empfangen werden.'*/,
        /* TODO tr 'Die Erkundungsflotte */'geriet auf ihrer Mission in den Hinterhalt einer feindlichen Alienspezies'/*. Wir vermuten, dass sie intelligent ist, aber leider war sie auch höchst aggressiv und vernichtete das Erkundungsschiff, bevor ein Kontakt überhaupt zustande kommen konnte.'*/,
        /* TODO tr 'Das Erkundungsschiff hatte vielversprechende Signale aufgefangen. Nachdem sie begeistert den energetischen Spuren folgten, */'brach plötzlich die Verbindung ab und konnte nicht wieder hergestellt'/* werden. Ausgeschickte Suchtrupps fanden keinerlei Hinweise auf den Verbleib des Schiffes. Es ist wohl in den Weiten des Alls verloren gegangen.'*/,
        /* TODO tr 'Bei der Verfolgung starker kosmischer Signale war der Navigator offenbar so abgelenkt, dass er das in der */'Nähe befindliche schwarze Loch vollkommen aus den Augen'/* verlor. Das Schiff geriet in das Gravitationsfeld und alle Anstrengungen der Crew konnten nicht verhindern, dass es hineingesogen wurde. Um einen weiteren Verlust dieser Art zu vermeiden, wurde vorgeschlagen, automatische Warnsignale vor schwarzen Löchern als Standard zu integrieren.'*/
    ],
    [LifeformDiscoveryEventType.newLifeformFound]: /.+ koordinatlarında canlı türü .+bulundu ve canlı türü yönetimi eklendi/i,
    [LifeformDiscoveryEventType.knownLifeformFound]: /Buna rağmen elçilerimiz bunlar hakkındaki bilgilerimizi (?<xp>\d+) tecrübeyle geliştirebildi/i,
    [LifeformDiscoveryEventType.artifacts]: {
        size: {
            [LifeformDiscoveryEventArtifactFindingSize.storageFull]: /* TODO tr 'Das Erkundungsschiff hat zwar ein paar Artefakte gefunden, */'konnte sie aber nicht mitnehmen, da deine Lager voll sind',
            [LifeformDiscoveryEventArtifactFindingSize.small]: /*'Keşif */'gemisi birkaç eser buldu',
            [LifeformDiscoveryEventArtifactFindingSize.medium]: /*'Keşif*/' gemisi büyük miktarda eser buldu',
            [LifeformDiscoveryEventArtifactFindingSize.large]: /* TODO tr 'Das Erkundungsschiff hat */'eine riesige Sammlung von Artefakten gefunden',
        },
        numberOfArtifacts: /Bulunan eserler: (?<artifacts>\d+)/i,
    },
};