import { LifeformType } from "./LifeformType";

export enum LifeformBuildingType {
    // humans
    residentialSector = 11_101,
    biosphereFarm = 11_102,
    researchCentre = 11_103,
    academyOfSciences = 11_104,
    neuroCalibrationCentre = 11_105,
    highEnergySmelting = 11_106,
    foodSilo = 11_107,
    fusionPoweredProduction = 11_108,
    skyscraper = 11_109,
    biotechLab = 11_110,
    metropolis = 11_111,
    planetaryShield = 11_112,

    // rocktal
    meditationEnclave = 12_101,
    crystalFarm = 12_102,
    runeTechnologium = 12_103,
    runeForge = 12_104,
    oriktorium = 12_105,
    magmaForge = 12_106,
    disruptionChamber = 12_107,
    megalith = 12_108,
    crystalRefinery = 12_109,
    deuteriumSynthesiser = 12_110,
    mineralResearchCentre = 12_111,
    advancedRecyclingPlant = 12_112,

    // mechas
    assemblyLine = 13_101,
    fusionCellFactory = 13_102,
    roboticsResearchCentre = 13_103,
    updateNetwork = 13_104,
    quantumComputerCentre = 13_105,
    automatisedAssemblyCentre = 13_106,
    highPerformanceTransformer = 13_107,
    microchipAssemblyLine = 13_108,
    productionAssemblyHall = 13_109,
    highPerformanceSynthesiser = 13_110,
    chipMassProduction = 13_111,
    nanoRepairBots = 13_112,

    // kaelesh
    sanctuary = 14_101,
    antimatterCondenser = 14_102,
    vortexChamber = 14_103,
    hallsOfRealisation = 14_104,
    forumOfTranscendence = 14_105,
    antimatterConvector = 14_106,
    cloningLaboratory = 14_107,
    chrysalisAccelerator = 14_108,
    bioModifier = 14_109,
    psionicModulator = 14_110,
    shipManufacturingHall = 14_111,
    supraRefractor = 14_112,
}

export const LifeformBuildingTypes: LifeformBuildingType[] = [
    LifeformBuildingType.residentialSector,
    LifeformBuildingType.biosphereFarm,
    LifeformBuildingType.researchCentre,
    LifeformBuildingType.academyOfSciences,
    LifeformBuildingType.neuroCalibrationCentre,
    LifeformBuildingType.highEnergySmelting,
    LifeformBuildingType.foodSilo,
    LifeformBuildingType.fusionPoweredProduction,
    LifeformBuildingType.skyscraper,
    LifeformBuildingType.biotechLab,
    LifeformBuildingType.metropolis,
    LifeformBuildingType.planetaryShield,

    LifeformBuildingType.meditationEnclave,
    LifeformBuildingType.crystalFarm,
    LifeformBuildingType.runeTechnologium,
    LifeformBuildingType.runeForge,
    LifeformBuildingType.oriktorium,
    LifeformBuildingType.magmaForge,
    LifeformBuildingType.disruptionChamber,
    LifeformBuildingType.megalith,
    LifeformBuildingType.crystalRefinery,
    LifeformBuildingType.deuteriumSynthesiser,
    LifeformBuildingType.mineralResearchCentre,
    LifeformBuildingType.advancedRecyclingPlant,

    LifeformBuildingType.assemblyLine,
    LifeformBuildingType.fusionCellFactory,
    LifeformBuildingType.roboticsResearchCentre,
    LifeformBuildingType.updateNetwork,
    LifeformBuildingType.quantumComputerCentre,
    LifeformBuildingType.automatisedAssemblyCentre,
    LifeformBuildingType.highPerformanceTransformer,
    LifeformBuildingType.microchipAssemblyLine,
    LifeformBuildingType.productionAssemblyHall,
    LifeformBuildingType.highPerformanceSynthesiser,
    LifeformBuildingType.chipMassProduction,
    LifeformBuildingType.nanoRepairBots,

    LifeformBuildingType.sanctuary,
    LifeformBuildingType.antimatterCondenser,
    LifeformBuildingType.vortexChamber,
    LifeformBuildingType.hallsOfRealisation,
    LifeformBuildingType.forumOfTranscendence,
    LifeformBuildingType.antimatterConvector,
    LifeformBuildingType.cloningLaboratory,
    LifeformBuildingType.chrysalisAccelerator,
    LifeformBuildingType.bioModifier,
    LifeformBuildingType.psionicModulator,
    LifeformBuildingType.shipManufacturingHall,
    LifeformBuildingType.supraRefractor,
];

export const LifeformBuildingTypesByLifeform: Record<LifeformType, LifeformBuildingType[]> = {
    [LifeformType.none]: [],

    [LifeformType.humans]: [
        LifeformBuildingType.residentialSector,
        LifeformBuildingType.biosphereFarm,
        LifeformBuildingType.researchCentre,
        LifeformBuildingType.academyOfSciences,
        LifeformBuildingType.neuroCalibrationCentre,
        LifeformBuildingType.highEnergySmelting,
        LifeformBuildingType.foodSilo,
        LifeformBuildingType.fusionPoweredProduction,
        LifeformBuildingType.skyscraper,
        LifeformBuildingType.biotechLab,
        LifeformBuildingType.metropolis,
        LifeformBuildingType.planetaryShield,
    ],
    [LifeformType.rocktal]: [
        LifeformBuildingType.meditationEnclave,
        LifeformBuildingType.crystalFarm,
        LifeformBuildingType.runeTechnologium,
        LifeformBuildingType.runeForge,
        LifeformBuildingType.oriktorium,
        LifeformBuildingType.magmaForge,
        LifeformBuildingType.disruptionChamber,
        LifeformBuildingType.megalith,
        LifeformBuildingType.crystalRefinery,
        LifeformBuildingType.deuteriumSynthesiser,
        LifeformBuildingType.mineralResearchCentre,
        LifeformBuildingType.advancedRecyclingPlant,
    ],
    [LifeformType.mechas]: [
        LifeformBuildingType.assemblyLine,
        LifeformBuildingType.fusionCellFactory,
        LifeformBuildingType.roboticsResearchCentre,
        LifeformBuildingType.updateNetwork,
        LifeformBuildingType.quantumComputerCentre,
        LifeformBuildingType.automatisedAssemblyCentre,
        LifeformBuildingType.highPerformanceTransformer,
        LifeformBuildingType.microchipAssemblyLine,
        LifeformBuildingType.productionAssemblyHall,
        LifeformBuildingType.highPerformanceSynthesiser,
        LifeformBuildingType.chipMassProduction,
        LifeformBuildingType.nanoRepairBots,
    ],
    [LifeformType.kaelesh]: [
        LifeformBuildingType.sanctuary,
        LifeformBuildingType.antimatterCondenser,
        LifeformBuildingType.vortexChamber,
        LifeformBuildingType.hallsOfRealisation,
        LifeformBuildingType.forumOfTranscendence,
        LifeformBuildingType.antimatterConvector,
        LifeformBuildingType.cloningLaboratory,
        LifeformBuildingType.chrysalisAccelerator,
        LifeformBuildingType.bioModifier,
        LifeformBuildingType.psionicModulator,
        LifeformBuildingType.shipManufacturingHall,
        LifeformBuildingType.supraRefractor,
    ],
};