export enum LifeformTechnologyType {
    // humans
    intergalacticEnvoys = 11_201,
    highPerformanceExtractors = 11_202,
    fusionDrives = 11_203,
    stealthFieldGenerator = 11_204,
    orbitalDen = 11_205,
    researchAI = 11_206,
    highPerformanceTerraformer = 11_207,
    enhancedProductionTechnologies = 11_208,
    lightFighterMkII = 11_209,
    cruiserMkII = 11_210,
    improvedLabTechnology = 11_211,
    plasmaTerraformer = 11_212,
    lowTemperatureDrives = 11_213,
    bomberMkII = 11_214,
    destroyerMkII = 11_215,
    battlecruiserMkII = 11_216,
    robotAssistants = 11_217,
    supercomputer = 11_218,

    // rocktal
    volcanicBatteries = 12_201,
    acousticScanning = 12_202,
    highEnergyPumpSystems = 12_203,
    cargoHoldExpansion_CivilianShips = 12_204,
    magmaPoweredProduction = 12_205,
    geothermalPowerPlants = 12_206,
    depthSounding = 12_207,
    ionCrystalEnhancement_heavyFighter = 12_208,
    improvedStellarator = 12_209,
    hardenedDiamondDrillHeads = 12_210,
    seismicMiningTechnology = 12_211,
    magmaPoweredPumpSystems = 12_212,
    ionCrystalModules = 12_213,
    optimisedSiloConstructionMethod = 12_214,
    diamondEnergyTransmitter = 12_215,
    obsidianShieldReinforcement = 12_216,
    runeShields = 12_217,
    rocktalCollectorEnhancement = 12_218,

    // mechas
    catalyserTechnology = 13_201,
    plasmaDrive = 13_202,
    efficiencyModule = 13_203,
    depotAI = 13_204,
    generalOverhaul_lightFighter = 13_205,
    automatedTransportLines = 13_206,
    improvedDroneAI = 13_207,
    experimentalRecyclingTechnology = 13_208,
    generalOverhaul_cruiser = 13_209,
    slingshotAutopilot = 13_210,
    highTemperatureSuperconductors = 13_211,
    generalOverhaul_battleship = 13_212,
    artificialSwarmIntelligence = 13_213,
    generalOverhaul_battlecruiser = 13_214,
    generalOverhaul_bomber = 13_215,
    generalOverhaul_destroyer = 13_216,
    experimentalWeaponsTechnology = 13_217,
    mechanGeneralEnhancement = 13_218,

    // kaelesh
    heatRecovery = 14_201,
    sulphideProcess = 14_202,
    psionicNetwork = 14_203,
    telekineticTractorBeam = 14_204,
    enhancedSensorTechnology = 14_205,
    neuromodalCompressor = 14_206,
    neuroInterface = 14_207,
    interplanetaryAnalysisNetwork = 14_208,
    overclocking_heavyFighter = 14_209,
    telekineticDrive = 14_210,
    sixthSense = 14_211,
    psychoharmoniser = 14_212,
    efficientSwarmIntelligence = 14_213,
    overclocking_largeCargo = 14_214,
    gravitationSensors = 14_215,
    overclocking_battleship = 14_216,
    psionicShieldMatrix = 14_217,
    kaeleshDiscovererEnhancement = 14_218,
}

export const LifeformTechnologyTypes: LifeformTechnologyType[] = [
    LifeformTechnologyType.intergalacticEnvoys,
    LifeformTechnologyType.highPerformanceExtractors,
    LifeformTechnologyType.fusionDrives,
    LifeformTechnologyType.stealthFieldGenerator,
    LifeformTechnologyType.orbitalDen,
    LifeformTechnologyType.researchAI,
    LifeformTechnologyType.highPerformanceTerraformer,
    LifeformTechnologyType.enhancedProductionTechnologies,
    LifeformTechnologyType.lightFighterMkII,
    LifeformTechnologyType.cruiserMkII,
    LifeformTechnologyType.improvedLabTechnology,
    LifeformTechnologyType.plasmaTerraformer,
    LifeformTechnologyType.lowTemperatureDrives,
    LifeformTechnologyType.bomberMkII,
    LifeformTechnologyType.destroyerMkII,
    LifeformTechnologyType.battlecruiserMkII,
    LifeformTechnologyType.robotAssistants,
    LifeformTechnologyType.supercomputer,

    LifeformTechnologyType.volcanicBatteries,
    LifeformTechnologyType.acousticScanning,
    LifeformTechnologyType.highEnergyPumpSystems,
    LifeformTechnologyType.cargoHoldExpansion_CivilianShips,
    LifeformTechnologyType.magmaPoweredProduction,
    LifeformTechnologyType.geothermalPowerPlants,
    LifeformTechnologyType.depthSounding,
    LifeformTechnologyType.ionCrystalEnhancement_heavyFighter,
    LifeformTechnologyType.improvedStellarator,
    LifeformTechnologyType.hardenedDiamondDrillHeads,
    LifeformTechnologyType.seismicMiningTechnology,
    LifeformTechnologyType.magmaPoweredPumpSystems,
    LifeformTechnologyType.ionCrystalModules,
    LifeformTechnologyType.optimisedSiloConstructionMethod,
    LifeformTechnologyType.diamondEnergyTransmitter,
    LifeformTechnologyType.obsidianShieldReinforcement,
    LifeformTechnologyType.runeShields,
    LifeformTechnologyType.rocktalCollectorEnhancement,

    LifeformTechnologyType.catalyserTechnology,
    LifeformTechnologyType.plasmaDrive,
    LifeformTechnologyType.efficiencyModule,
    LifeformTechnologyType.depotAI,
    LifeformTechnologyType.generalOverhaul_lightFighter,
    LifeformTechnologyType.automatedTransportLines,
    LifeformTechnologyType.improvedDroneAI,
    LifeformTechnologyType.experimentalRecyclingTechnology,
    LifeformTechnologyType.generalOverhaul_cruiser,
    LifeformTechnologyType.slingshotAutopilot,
    LifeformTechnologyType.highTemperatureSuperconductors,
    LifeformTechnologyType.generalOverhaul_battleship,
    LifeformTechnologyType.artificialSwarmIntelligence,
    LifeformTechnologyType.generalOverhaul_battlecruiser,
    LifeformTechnologyType.generalOverhaul_bomber,
    LifeformTechnologyType.generalOverhaul_destroyer,
    LifeformTechnologyType.experimentalWeaponsTechnology,
    LifeformTechnologyType.mechanGeneralEnhancement,

    LifeformTechnologyType.heatRecovery,
    LifeformTechnologyType.sulphideProcess,
    LifeformTechnologyType.psionicNetwork,
    LifeformTechnologyType.telekineticTractorBeam,
    LifeformTechnologyType.enhancedSensorTechnology,
    LifeformTechnologyType.neuromodalCompressor,
    LifeformTechnologyType.neuroInterface,
    LifeformTechnologyType.interplanetaryAnalysisNetwork,
    LifeformTechnologyType.overclocking_heavyFighter,
    LifeformTechnologyType.telekineticDrive,
    LifeformTechnologyType.sixthSense,
    LifeformTechnologyType.psychoharmoniser,
    LifeformTechnologyType.efficientSwarmIntelligence,
    LifeformTechnologyType.overclocking_largeCargo,
    LifeformTechnologyType.gravitationSensors,
    LifeformTechnologyType.overclocking_battleship,
    LifeformTechnologyType.psionicShieldMatrix,
    LifeformTechnologyType.kaeleshDiscovererEnhancement,
];